<?php
require_once __DIR__ . '/seed_helpers.php';
$conn->exec("SET FOREIGN_KEY_CHECKS=0");
$L16=createLesson($conn,4,16,'Bai 16: You mo rang sheng huo geng mei hao','Uoc muon va hy vong. Dong tu "lien" + "dou". Cau truc "ji...you...".','["Uoc mo","Hy vong","Tuong lai"]','Uoc mo','medium','HSK4 Bai 16: Tu vung ve uoc mo va hy vong. Cach dung 连...都 (ngay ca...cung). Cau truc 既...又... (vua...vua...).');
$v16=0;
$v16_1=v($conn,$L16,4,'幽默','you mo','hai huoc','hài hước','他很幽默。','Ta hen you mo.','Anh ay rat hai huoc.','adj','Khieu hai huoc.',++$v16);
$v16_2=v($conn,$L16,4,'笑话','xiao hua','chuyen cuoi','chuyện cười','讲一个笑话。','Jiang yi ge xiao hua.','Ke mot cau chuyen cuoi.','noun','Chuyen hai.',++$v16);
$v16_3=v($conn,$L16,4,'笑','xiao','cuoi','cười','大家都笑了。','Da jia dou xiao le.','Moi nguoi deu cuoi.','verb','Nu cuoi.',++$v16);
$v16_4=v($conn,$L16,4,'开心','kai xin','vui ve','vui vẻ','我很开心。','Wo hen kai xin.','Toi rat vui.','adj','Cam xuc vui.',++$v16);
$v16_5=v($conn,$L16,4,'放松','fang song','thu gian','thư giãn','听听音乐放松一下。','Ting ting yin yue fang song yi xia.','Nghe nhac thu gian mot chut.','verb','Giam cang thang.',++$v16);
$v16_6=v($conn,$L16,4,'心情','xin qing','tam trang','tâm trạng','心情很好。','Xin qing hen hao.','Tam trang rat tot.','noun','Cam xuc tam ly.',++$v16);
$v16_7=v($conn,$L16,4,'快乐','kuai le','vui ve','vui vẻ','祝你快乐。','Zhu ni kuai le.','Chuc ban vui ve.','adj','Hanh phuc vui.',++$v16);
$v16_8=v($conn,$L16,4,'生活','sheng huo','cuoc song','cuộc sống','生活很美好。','Sheng huo hen mei hao.','Cuoc song rat dep.','noun','Doi song hang ngay.',++$v16);
$v16_9=v($conn,$L16,4,'压力','ya li','ap luc','áp lực','压力很大。','Ya li hen da.','Ap luc rat lon.','noun','Gay suc ep.',++$v16);
$v16_10=v($conn,$L16,4,'面对','mian dui','doi mat','đối mặt','面对困难。','Mian dui kun nan.','Doi mat kho khan.','verb','Truoc mat.',++$v16);
$v16_11=v($conn,$L16,4,'积极','ji ji','tich cuc','tích cực','积极的态度。','Ji ji de tai du.','Thai do tich cuc.','adj','Cach nghi tot.',++$v16);
$v16_12=v($conn,$L16,4,'态度','tai du','thai do','thái độ','态度很重要。','Tai du hen zhong yao.','Thai do rat quan trong.','noun','Cach nhin nhan.',++$v16);
$g16_1=g($conn,$L16,'连...都 + V','连 + Danh tu/Nguoi + 都 + V','Ngay ca...cung','连...都 nhan manh, nghia la "ngay ca...cung". Thuong dung phu dinh.','连小孩子都懂 = Ngay ca tre con cung hieu.','Nhan manh.',1);
ge($conn,$g16_1,'他连一个笑话都不会讲。','Ta lian yi ge xiao hua dou bu hui jiang.','Anh ay ngay ca chuyen cuoi cung ko biet ke.',1);
ge($conn,$g16_1,'连老师都被他逗笑了。','Lian lao shi dou bei ta dou xiao le.','Ngay co giao cung bi anh ay cho cuoi.',2);
$g16_2=g($conn,$L16,'Cau truc 既...又...','既 + A + 又 + B','Vua...vua...','Lien tu song doi. Ca A va B deu dung.','既幽默又聪明 = Vua hai huoc vua thong minh.','Song song.',2);
ge($conn,$g16_2,'他既幽默又聪明。','Ta ji you mo you cong ming.','Anh ay vua hai huoc vua thong minh.',1);
ge($conn,$g16_2,'生活既要有努力也要有放松。','Sheng huo ji yao you nu li ye yao you fang song.','Cuoc song vua can co gang vua can thu gian.',2);
$g16_3=g($conn,$L16,'Cau truc 把 + O + V + 一下','把 + O + V + 一下','Lam cai gi mot chut','Cau truc 把 + O + V + 一下 lam viec gi trong thoi gian ngan.','把心情放松一下 = Thu gian tam trang.','Thoi gian ngan.',3);
ge($conn,$g16_3,'把心情放松一下。','Ba xin qing fang song yi xia.','Hay thu gian tam trang mot chut.',1);
ge($conn,$g16_3,'把房间收拾一下。','Ba fang jian shou shi yi xia.','Don dep phong mot chut.',2);
$g16_4=g($conn,$L16,'Cau truc 越...越...','越 + V/Tinh tu + 越 + V/Tinh tu','Cang...cang...','Su thay doi ti le thuan.','越笑越开心 = Cang cuoi cang vui.','Tuong quan.',4);
ge($conn,$g16_4,'越笑越开心。','Yue xiao yue kai xin.','Cang cuoi cang vui.',1);
ge($conn,$g16_4,'越努力越幸运。','Yue nu li yue xing yun.','Cang co gang cang may man.',2);
$d16_1=d($conn,$L16,'Chuyen cuoi','Ke chuyen cuoi.',1);
ds($conn,$d16_1,'Minh','你会讲笑话吗？','Ni hui jiang xiao hua ma?','Ban biet ke chuyen cuoi ko?',1);
ds($conn,$d16_1,'Lan','会啊，我经常讲。','Hui a, wo jing chang jiang.','Co, toi thuong ke.',2);
ds($conn,$d16_1,'Minh','讲一个听听吧。','Jiang yi ge ting ting ba.','Ke mot cai nghe thu.',3);
ds($conn,$d16_1,'Lan','有一天，一只兔子对乌龟说...大家都笑了。','You yi tian, yi zhi tu zi dui wu gui shuo...Da jia dou xiao le.','Mot ngay, tho noi voi rua...Moi nguoi deu cuoi.',4);
$d16_2=d($conn,$L16,'Ung xu hai huoc','Thai do song.',2);
ds($conn,$d16_2,'Hoang','幽默的人更容易交到朋友。','You mo de ren geng rong yi jiao dao peng you.','Nguoi hai huoc de ket ban hon.',1);
ds($conn,$d16_2,'Minh','对，大家都喜欢和有趣的人在一起。','Dui, da jia dou xi huan he you qu de ren zai yi qi.','Dung, ai cung thich o gan nguoi vui.',2);
ds($conn,$d16_2,'Hoang','而且幽默能让人放松。','Er qie you mo neng rang ren fang song.','Va hai huoc giup nguoi ta thu gian.',3);
ds($conn,$d16_2,'Minh','是的，生活需要幽默。','Shi de, sheng huo xu yao you mo.','Dung, cuoc song can hai huoc.',4);
$d16_3=d($conn,$L16,'Doc sach hai huoc','Sach vui.',3);
ds($conn,$d16_3,'Lan','你在看什么书？','Ni zai kan shen me shu?','Ban dang doc sach gi?',1);
ds($conn,$d16_3,'Minh','一本幽默故事书。','Yi ben you mo gu shi shu.','Sach chuyen cuoi.',2);
ds($conn,$d16_3,'Lan','好看吗？','Hao kan ma?','Hay ko?',3);
ds($conn,$d16_3,'Minh','很好看，笑得肚子疼。','Hen hao kan, xiao de du zi teng.','Hay lam, cuoi dau bung.',4);
ds($conn,$d16_3,'Lan','看完借我看看。','Kan wan jie wo kan kan.','Doc xong cho toi muon.',5);
ds($conn,$d16_3,'Minh','没问题。','Mei wen ti.','Ko van de.',6);
r($conn,$L16,'Uoc mo va hy vong','生活中有很多压力，但幽默能让生活更美好。幽默不是讲笑话的能力，而是一种积极的生活态度。一个幽默的人，能让周围的人感到快乐和放松。在困难面前，如果能用幽默的方式面对，压力就会变小。连小孩子都懂得，笑能让心情变好。所以，我们既要努力工作，也要学会用幽默调节生活。越积极，越快乐。让幽默成为生活的一部分，你会发现世界变得更美好了。','Sheng huo zhong you hen duo ya li, dan you mo neng rang sheng huo geng mei hao. You mo bu shi jiang xiao hua de neng li, er shi yi zhong ji ji de sheng huo tai du. Yi ge you mo de ren, neng rang zhou wei de ren gan dao kuai le he fang song. Zai kun nan mian qian, ru guo neng yong you mo de fang shi mian dui, ya li jiu hui bian xiao. Lian xiao hai zi dou dong de, xiao neng rang xin qing bian hao. Suo yi, wo men ji yao nu li gong zuo, ye yao xue hui yong you mo tiao jie sheng huo. Yue ji ji, yue kuai le. Rang you mo cheng wei sheng huo de yi bu fen, ni hui fa xian shi jie bian de geng mei hao le.','Cuoc song co nhieu ap luc, nhung hai huoc lam cuoc song tot hon. Hai huoc ko phai khieu ke chuyen ma la thai do song tich cuc. Nguoi hai huoc khien nguoi khac vui va thu gian. Truoc kho khan, dung hai huoc doi mat, ap luc se nho di. Ngay tre con cung biet cuoi lam tam trang tot. Vua can co gang lam vua can thu gian. Cang tich cuc cang vui. De hai huoc thanh phan cua cuoc song, ban se thay dep hon.','medium',190,1);
$L16l=l($conn,$L16,'Hai huoc','A: Ban co thich nguoi hai huoc ko? B: Co, toi thich. A: Tai sao? B: Vi ho khien toi cuoi va thu gian. A: Ban co biet ke chuyen cuoi ko? B: Biet mot chut, toi thuong ke cho ban be.','A: Ni xi huan you mo de ren ma? B: Xi huan. A: Wei shen me? B: Yin wei ta men rang wo xiao he fang song. A: Ni hui jiang xiao hua ma? B: Hui yi dian, wo chang gei peng you jiang.','A: Ban thich nguoi hai huoc ko? B: Thich. A: Sao? B: Vi ho khien toi cuoi va thu gian. A: Ban biet ke chuyen cuoi ko? B: Biet chut, toi thuong ke cho ban.','1');
lq($conn,$L16l,'Tai sao B thich nguoi hai huoc?','{"A":"Ho dep trai","B":"Ho khien toi cuoi va thu gian","C":"Ho giau co"}','Ho khien toi cuoi va thu gian','Vi ho khien toi cuoi va thu gian.','multiple_choice',1);
lq($conn,$L16l,'B co biet ke chuyen cuoi ko?','{"A":"Ko biet","B":"Biet nhieu","C":"Biet mot chut"}','Biet mot chut','Hui yi dian.','multiple_choice',2);
lq($conn,$L16l,'B thuong ke chuyen cuoi cho ai?','{"A":"Dong nghiep","B":"Ban be","C":"Gia dinh"}','Ban be','Chang gei peng you jiang.','multiple_choice',3);
$E16_1=e($conn,$L16,'Chon dap an','"幽默" la?','multiple_choice','easy',1,'B',1);
eo($conn,$E16_1,'Nghiem tuc','A',0,1); eo($conn,$E16_1,'Hai huoc','B',1,2); eo($conn,$E16_1,'Buon','C',0,3);
$E16_2=e($conn,$L16,'Dich','"Yue xiao yue kai xin."','translation','medium',1,'越笑越开心。',2);
$E16_3=e($conn,$L16,'Dien tu','他很___，大家都喜欢他。','fill_blank','medium',1,'幽默',3);
$E16_4=e($conn,$L16,'Sap xep','幽默 / 生活 / 让 / 美好 / 更','sentence_order','medium',1,'幽默让生活更美好。',4);
$E16_5=e($conn,$L16,'Dung sai','"压力" la "ap luc".','true_false','easy',1,'true',5);
eo($conn,$E16_5,'Dung','A',1,1); eo($conn,$E16_5,'Sai','B',0,2);
$E16_6=e($conn,$L16,'Dien tu','Jiang yi ge xiao ___ ba.','fill_blank','medium',1,'话',6);
$E16_7=e($conn,$L16,'Chon dap an','"连...都" chi?','multiple_choice','medium',1,'C',7);
eo($conn,$E16_7,'Dia diem','A',0,1); eo($conn,$E16_7,'Thoi gian','B',0,2); eo($conn,$E16_7,'Nhan manh','C',1,3);
$E16_8=e($conn,$L16,'Dien tu','生活既要有努力也___有放松。','fill_blank','medium',1,'要',8);
$E16_9=e($conn,$L16,'Chon dap an','"既...又..." co nghia?','multiple_choice','easy',1,'B',9);
eo($conn,$E16_9,'Hoac...hoac...','A',0,1); eo($conn,$E16_9,'Vua...vua...','B',1,2); eo($conn,$E16_9,'Ko...cung ko...','C',0,3);
$E16_10=e($conn,$L16,'Dien tu','___极的人更快乐。','fill_blank','medium',1,'积极',10);
foreach ([$v16_1,$v16_2,$v16_3,$v16_4,$v16_5,$v16_6,$v16_7,$v16_8,$v16_9,$v16_10,$v16_11,$v16_12] as $i=>$vid) if ($vid) rv($conn,$L16,$vid,'core',$i+1);
echo " HSK4 L16 done: $v16 vocab, 4 grammar, 3 dialogues, 1 reading, 1 listening, 10 exercises\n";

$L17=createLesson($conn,4,17,'Bai 17: Xue xi fang fa hen zhong yao','Phuong phap hoc tap. Cach dung "ba" + O + V. Phó tu "zai" + "ye" + phu dinh.','["Hoc tap","Phuong phap","Kien thuc"]','Hoc tap','medium','HSK4 Bai 17: Tu vung phuong phap hoc tap. Cau truc 把 + O + V. 再...也 + phu dinh.');
$v17=0;
$v17_1=v($conn,$L17,4,'方法','fang fa','phuong phap','phương pháp','学习方法很重要。','Xue xi fang fa hen zhong yao.','Phuong phap hoc tap rat quan trong.','noun','Cach lam viec.',++$v17);
$v17_2=v($conn,$L17,4,'知识','zhi shi','kien thuc','kiến thức','学了很多知识。','Xue le hen duo zhi shi.','Hoc duoc nhieu kien thuc.','noun','Hieu biet.',++$v17);
$v17_3=v($conn,$L17,4,'复习','fu xi','on tap','ôn tập','复习功课。','Fu xi gong ke.','On tap bai.','verb','Doc lai bai.',++$v17);
$v17_4=v($conn,$L17,4,'习惯','xi guan','thoi quen','thói quen','好习惯很重要。','Hao xi guan hen zhong yao.','Thoi quen tot rat quan trong.','noun','Hanh vi lap di lap lai.',++$v17);
$v17_5=v($conn,$L17,4,'笔记','bi ji','ghi chep','ghi chép','记笔记。','Ji bi ji.','Ghi chep.','noun','Ghi lai.',++$v17);
$v17_6=v($conn,$L17,4,'练习','lian xi','luyen tap','luyện tập','多练习。','Duo lian xi.','Luyen tap nhieu.','verb','Thuc hanh.',++$v17);
$v17_7=v($conn,$L17,4,'提高','ti gao','nang cao','nâng cao','提高水平。','Ti gao shui ping.','Nang cao trinh do.','verb','Lam tot hon.',++$v17);
$v17_8=v($conn,$L17,4,'努力','nu li','co gang','cố gắng','努力学习。','Nu li xue xi.','Co gang hoc.','adj/adv','Het suc.',++$v17);
$v17_9=v($conn,$L17,4,'坚持','jian chi','kien tri','kiên trì','坚持下去。','Jian chi xia qu.','Kien tri tiep.','verb','Ko bo cuoc.',++$v17);
$v17_10=v($conn,$L17,4,'进步','jin bu','tien bo','tiến bộ','进步很快。','Jin bu hen kuai.','Tien bo rat nhanh.','noun/verb','Phat trien.',++$v17);
$v17_11=v($conn,$L17,4,'理解','li jie','hieu','hiểu','理解课文。','Li jie ke wen.','Hieu bai.','verb','Nam ro.',++$v17);
$g17_1=g($conn,$L17,'Cau truc 把 + O + V','把 + O + Dong tu (làm gi đo vơi O)','Lam gi cho O','Dong tu sau 把 phai co tac dong len tan ngu.','把笔记写完 = Viet xong ghi chep.','Xu ly O.',1);
ge($conn,$g17_1,'把作业做完再看电视。','Ba zuo ye zuo wan zai kan dian shi.','Lam xong bai tap roi xem TV.',1);
ge($conn,$g17_1,'把课文读一遍。','Ba ke wen du yi bian.','Doc bai khoa mot lan.',2);
$g17_2=g($conn,$L17,'再...也 + phu dinh','再 + Tinh tu + 也 + bu + V','Du the nao cung ko','Chi su viec ko the thay doi du, du co gang cach nao.','再难也要学 = Du kho cung phai hoc.','Bat chap.',2);
ge($conn,$g17_2,'再难也要坚持下去。','Zai nan ye yao jian chi xia qu.','Du kho cung phai kien tri.',1);
ge($conn,$g17_2,'再忙也要复习。','Zai mang ye yao fu xi.','Du ban cung phai on tap.',2);
$g17_3=g($conn,$L17,'Cau truc 除了...以外，都...','除了 + O 以外 + 都 + V','Ngoai...ra deu...','Ngoai phan do ra, nhung phan con lai deu...','除了生词以外，都懂了 = Ngoai tu moi ra deu hieu.','Phan loai.',3);
ge($conn,$g17_3,'除了听力以外，我都有了进步。','Chu le ting li yi wai, wo dou you le jin bu.','Ngoai nghe ra, toi deu tien bo.',1);
ge($conn,$g17_3,'除了语法，都复习了。','Chu le yu fa, dou fu xi le.','Ngoai ngu phap ra deu on tap.',2);
$d17_1=d($conn,$L17,'Phuong phap hoc','Cach hoc.',1);
ds($conn,$d17_1,'Lan','你怎么学中文？','Ni zen me xue zhong wen?','Ban hoc tieng Trung the nao?',1);
ds($conn,$d17_1,'Minh','每天背生词，听录音。','Mei tian bei sheng ci, ting lu yin.','Moi ngay hoc tu moi, nghe ghi am.',2);
ds($conn,$d17_1,'Lan','还有呢？','Hai you ne?','Con nua ko?',3);
ds($conn,$d17_1,'Minh','把学过的内容复习一遍。','Ba xue guo de nei rong fu xi yi bian.','On tap lai noi dung da hoc.',4);
ds($conn,$d17_1,'Lan','方法很好，坚持下去。','Fang fa hen hao, jian chi xia qu.','Phuong phap tot, kien tri nhe.',5);
$d17_2=d($conn,$L17,'Hoc tu','Hoc tu vung.',2);
ds($conn,$d17_2,'Minh','你记笔记吗？','Ni ji bi ji ma?','Ban ghi chep ko?',1);
ds($conn,$d17_2,'Lan','记啊，但有时候看不懂自己写的。','Ji a, dan you shi hou kan bu dong zi ji xie de.','Co, nhung co luc ko doc duoc minh viet.',2);
ds($conn,$d17_2,'Minh','哈哈哈，我也是。','Ha ha ha, wo ye shi.','Ha ha, toi cung vay.',3);
ds($conn,$d17_2,'Lan','你有什么好方法？','Ni you shen me hao fang fa?','Ban co phuong phap nao hay ko?',4);
ds($conn,$d17_2,'Minh','把笔记整理成表格。','Ba bi ji zheng li cheng biao ge.','Sap xep ghi chep thanh bang.',5);
$d17_3=d($conn,$L17,'Quyet tam hoc','Kien tri.',3);
ds($conn,$d17_3,'Lan','我最近进步慢，不想学了。','Wo zui jin jin bu man, bu xiang xue le.','Toi gan day tien bo cham, ko muon hoc.',1);
ds($conn,$d17_3,'Minh','再难也要坚持啊。','Zai nan ye yao jian chi a.','Du kho cung phai kien tri.',2);
ds($conn,$d17_3,'Lan','可是太累了。','Ke shi tai lei le.','Nhung met qua.',3);
ds($conn,$d17_3,'Minh','把目标定小一点，每天进步一点点。','Ba mu biao ding xiao yi dian, mei tian jin bu yi dian dian.','Dat muc tieu nho hon, moi ngay tien bo mot chut.',4);
$r17=r($conn,$L17,'Phuong phap hoc','学习需要方法和坚持。每个人都有适合自己的学习方法。有的人喜欢早上背生词，有的人喜欢晚上复习。重要的不是学多久，而是怎么学。首先，要养成好习惯，每天花一点时间学习。其次，要记笔记，把重点记下来。第三，要多练习，把学过的内容运用到生活中。第四，要定期复习，不然学了就忘。最后，再难也不要放弃。坚持是最重要的。只要有正确的方法和努力，你的中文水平一定会提高的。','Xue xi xu yao fang fa he jian chi. Mei ge ren dou you shi he zi ji de xue xi fang fa. You de ren xi huan zao shang bei sheng ci, you de ren xi huan wan shang fu xi. Zhong yao de bu shi xue duo jiu, er shi zen me xue. Shou xian, yao yang cheng hao xi guan, mei tian hua yi dian shi jian xue xi. Qi ci, yao ji bi ji, ba zhong dian ji xia lai. Di san, yao duo lian xi, ba xue guo de nei rong yun yong dao sheng huo zhong. Di si, yao ding qi fu xi, bu ran xue le jiu wang. Zui hou, zai nan ye bu yao fang qi. Jian chi shi zui zhong yao de. Zhi yao you zheng que de fang fa he nu li, ni de zhong wen shui ping yi ding hui ti gao de.','Hoc can phuong phap va kien tri. Moi nguoi co cach phu hop. Nguoi thich hoc tu sang, nguoi thich on toi. Quan trong ko phai hoc bao lau ma la hoc the nao. Truoc het tao thoi quen tot. Tiep theo ghi chep trong tam. Thu ba luyen tap nhieu. Thu tu on tap dinh ky. Cuoi cung du kho cung ko bo cuoc. Kien tri la quan trong nhat. Co phuong phap va co gang, trinh do ban se len.','medium',200,1);
$L17l=l($conn,$L17,'Phuong phap hoc','A: Ban co phuong phap hoc tieng Trung nao hay ko? B: Co, toi ghi chep va on tap hang ngay. A: Ban co kien tri ko? B: Co gang kien tri. A: Nho chia se voi toi nhe. B: Ko van de.','A: Ni you xue xi fang fa ma? B: You, wo ji bi ji he fu xi. A: Ni jian chi ma? B: Nu li jian chi. A: Qing fen xiang gei wo. B: Mei wen ti.','A: Ban co phuong phap hoc tieng Trung ko? B: Co, toi ghi chep va on tap. A: Ban co kien tri ko? B: Co gang kien tri. A: Hay chia se cho toi. B: Ko van de.','1');
lq($conn,$L17l,'B hoc tieng Trung bang phuong phap gi?','{"A":"Xem phim","B":"Ghi chep va on tap","C":"Di choi"}','Ghi chep va on tap','Wo ji bi ji he fu xi.','multiple_choice',1);
lq($conn,$L17l,'B co kien tri hoc ko?','{"A":"Ko","B":"Co gang","C":"Hoan toan ko"}','Co gang','Nu li jian chi.','multiple_choice',2);
lq($conn,$L17l,'A nho B lam gi?','{"A":"Chia se phuong phap","B":"Di an","C":"Doc sach"}','Chia se phuong phap','Qing fen xiang gei wo.','multiple_choice',3);
$E17_1=e($conn,$L17,'Chon dap an','"复习" la?','multiple_choice','easy',1,'B',1);
eo($conn,$E17_1,'Hoc moi','A',0,1); eo($conn,$E17_1,'On tap','B',1,2); eo($conn,$E17_1,'Nghi','C',0,3);
$E17_2=e($conn,$L17,'Dich','"Kien tri la quan trong nhat."','translation','medium',1,'坚持是最重要的。',2);
$E17_3=e($conn,$L17,'Dien tu','每天覆___功课。','fill_blank','medium',1,'习',3);
$E17_4=e($conn,$L17,'Sap xep','方法 / 学习 / 重要 / 很','sentence_order','medium',1,'学习方法很重要。',4);
$E17_5=e($conn,$L17,'Dung sai','"笔记" la "ve tranh".','true_false','easy',1,'false',5);
eo($conn,$E17_5,'Dung','A',0,1); eo($conn,$E17_5,'Sai','B',1,2);
$E17_6=e($conn,$L17,'Dien tu','Ba gong ke zuo ___ yao kan dian shi.','fill_blank','medium',1,'完',6);
$E17_7=e($conn,$L17,'Chon dap an','"把" la cau truc gi?','multiple_choice','medium',1,'A',7);
eo($conn,$E17_7,'Xu ly tan ngu','A',1,1); eo($conn,$E17_7,'So sanh','B',0,2); eo($conn,$E17_7,'Thoi gian','C',0,3);
$E17_8=e($conn,$L17,'Dien tu','除了语法以外，都___了。','fill_blank','medium',1,'复习',8);
$E17_9=e($conn,$L17,'Chon dap an','"再难也要坚持" la gi?','multiple_choice','medium',1,'B',9);
eo($conn,$E17_9,'De qua ko can co gang','A',0,1); eo($conn,$E17_9,'Du kho cung kien tri','B',1,2); eo($conn,$E17_9,'Bo cuoc la tot','C',0,3);
$E17_10=e($conn,$L17,'Dien tu','Zai mang ye yao fu ___.','fill_blank','medium',1,'习',10);
foreach ([$v17_1,$v17_2,$v17_3,$v17_4,$v17_5,$v17_6,$v17_7,$v17_8,$v17_9,$v17_10,$v17_11] as $i=>$vid) if ($vid) rv($conn,$L17,$vid,'core',$i+1);
echo " HSK4 L17 done: $v17 vocab, 3 grammar, 3 dialogues, 1 reading, 1 listening, 10 exercises\n";

$L18=createLesson($conn,4,18,'Bai 18: Wang luo gai bian sheng huo','Internet thay doi cuoc song. Cau truc "bu...bu..." + V. Phó tu "ji hu" + V. Lien tu "ran hou".','["Internet","Cong nghe","Xa hoi"]','Internet','medium','HSK4 Bai 18: Tu vung internet. Cau truc 不...不... + V (ko...ko...). 几乎 + V (hau nhu). 然后 (sau do).');
$v18=0;
$v18_1=v($conn,$L18,4,'网络','wang luo','mang internet','mạng internet','网络很方便。','Wang luo hen fang bian.','Internet rat tien loi.','noun','Internet.',++$v18);
$v18_2=v($conn,$L18,4,'上网','shang wang','len mang','lên mạng','每天上网。','Mei tian shang wang.','Moi ngay len mang.','verb','Dung internet.',++$v18);
$v18_3=v($conn,$L18,4,'信息','xin xi','thong tin','thông tin','很多信息。','Hen duo xin xi.','Nhieu thong tin.','noun','Du lieu.',++$v18);
$v18_4=v($conn,$L18,4,'电脑','dian nao','may tinh','máy tính','用电脑工作。','Yong dian nao gong zuo.','Dung may tinh lam viec.','noun','Thiet bi dien tu.',++$v18);
$v18_5=v($conn,$L18,4,'手机','shou ji','dien thoai','điện thoại','看手机。','Kan shou ji.','Xem dien thoai.','noun','Dien thoai di dong.',++$v18);
$v18_6=v($conn,$L18,4,'方便','fang bian','tien loi','tiện lợi','很方便。','Hen fang bian.','Rat tien loi.','adj','De dang.',++$v18);
$v18_7=v($conn,$L18,4,'聊天','liao tian','tron chuyen','trò chuyện','网上聊天。','Wang shang liao tian.','Tron chuyen tren mang.','verb','Noi chuyen.',++$v18);
$v18_8=v($conn,$L18,4,'游戏','you xi','tro choi','trò chơi','玩网络游戏。','Wan wang luo you xi.','Choi game online.','noun','Game.',++$v18);
$v18_9=v($conn,$L18,4,'购物','gou wu','mua sam','mua sắm','网上购物。','Wang shang gou wu.','Mua sam online.','verb','Mua hang.',++$v18);
$v18_10=v($conn,$L18,4,'支付','zhi fu','thanh toan','thanh toán','手机支付。','Shou ji zhi fu.','Thanh toan dien thoai.','verb','Tra tien.',++$v18);
$v18_11=v($conn,$L18,4,'安全','an quan','an toan','an toàn','网络安全很重要。','Wang luo an quan hen zhong yao.','An toan mang rat quan trong.','adj/noun','Ko nguy hiem.',++$v18);
$v18_12=v($conn,$L18,4,'影响','ying xiang','anh huong','ảnh hưởng','网络影响生活。','Wang luo ying xiang sheng huo.','Internet anh huong cuoc song.','verb/noun','Su tac dong.',++$v18);
$g18_1=g($conn,$L18,'Cau truc 不...不... + V','不 + V1 + 不 + V2','Ko...ko...','Dien ta bat buoc hoac dieu kien can thiet.','不能不学 = Ko the ko hoc.','Bat buoc.',1);
ge($conn,$g18_1,'现在不能不上网。','Xian zai bu neng bu shang wang.','Bay gio ko the ko len mang.',1);
ge($conn,$g18_1,'不能不相信网络的作用。','Bu neng bu xiang xin wang luo de zuo yong.','Ko the ko tin tac dung cua internet.',2);
$g18_2=g($conn,$L18,'Phó tu 几乎 + V','几乎 + V/Phu dinh','Hau nhu','几乎 chi "gan nhu, xap xi". Thuong truoc dong tu.','几乎人人都上网 = Hau nhu ai cung len mang.','Muc do cao.',2);
ge($conn,$g18_2,'几乎人人都用手机支付。','Ji hu ren ren dou yong shou ji zhi fu.','Hau nhu ai cung dung DT thanh toan.',1);
ge($conn,$g18_2,'我几乎每天都要用电脑。','Wo ji hu mei tian dou yao yong dian nao.','Toi hau nhu moi ngay dung may tinh.',2);
$g18_3=g($conn,$L18,'Lien tu 然后 + V','先 + V1 + 然后 + V2','Truoc...sau do...','Chi thu tu hanh dong.','先上网，然后睡觉 = Len mang truoc, ngu sau.','Thu tu.',3);
ge($conn,$g18_3,'先查资料，然后写文章。','Xian cha zi liao, ran hou xie wen zhang.','Tra tai lieu truoc, sau do viet bai.',1);
ge($conn,$g18_3,'先付款，然后发货。','Xian fu kuan, ran hou fa huo.','Tra tien truoc, sau do gui hang.',2);
$d18_1=d($conn,$L18,'Su dung mang','Dung mang.',1);
ds($conn,$d18_1,'Lan','你每天上网多久？','Ni mei tian shang wang duo jiu?','Ban moi ngay len mang bao lau?',1);
ds($conn,$d18_1,'Minh','大概三四个小时。','Da gai san si ge xiao shi.','Khoang 3-4 tieng.',2);
ds($conn,$d18_1,'Lan','上网做什么？','Shang wang zuo shen me?','Len mang lam gi?',3);
ds($conn,$d18_1,'Minh','查资料、聊天、看新闻。','Cha zi liao, liao tian, kan xin wen.','Tra tai lieu, tro chuyen, doc tin.',4);
$d18_2=d($conn,$L18,'Mua sam online','Mua hang mang.',2);
ds($conn,$d18_2,'Lan','你经常网上购物吗？','Ni jing chang wang shang gou wu ma?','Ban hay mua sam online ko?',1);
ds($conn,$d18_2,'Minh','经常啊，很方便。','Jing chang a, hen fang bian.','Thuong xuyen, rat tien.',2);
ds($conn,$d18_2,'Lan','不怕不安全吗？','Bu pa bu an quan ma?','Ko so mat an toan a?',3);
ds($conn,$d18_2,'Minh','选择正规的网站就可以了。','Xuan ze zheng gui de wang zhan jiu ke yi le.','Chon web uy tin la duoc.',4);
$d18_3=d($conn,$L18,'Anh huong mang','Tac dong mang.',3);
ds($conn,$d18_3,'Minh','我最近玩游戏太多了。','Wo zui jin wan you xi tai duo le.','Gan day toi choi game nhieu qua.',1);
ds($conn,$d18_3,'Lan','不要沉迷网络啊。','Bu yao chen mi wang luo a.','Dung dam me mang nhe.',2);
ds($conn,$d18_3,'Minh','我知道，但控制不住。','Wo zhi dao, dan kong zhi bu zhu.','Toi biet nhung ko kiem che duoc.',3);
ds($conn,$d18_3,'Lan','先安排好时间，然后严格执行。','Xian an pai hao shi jian, ran hou yan ge zhi xing.','Xep lich truoc, sau do thuc hien.',4);
r($conn,$L18,'Mang thay doi song','网络改变了我们的生活。以前，人们要出门买东西、去银行转账、去图书馆查资料。现在，几乎人人都用手机和电脑。足不出户就能做很多事情。先打开手机，然后轻轻一点，就可以购物、支付、聊天。网络让生活更便捷了。但是，网络也有一些负面影响。比如，有人沉迷网络游戏，影响了工作和学习。还有人担心网络安全问题。所以，我们要合理使用网络，不能不上网，也不能整天上网。网络只是工具，我们的生活才是重点。','Wang luo gai bian le wo men de sheng huo. Yi qian, ren men yao chu men mai dong xi, qu yin hang zhuan zhang, qu tu shu guan zha zi liao. Xian zai, ji hu ren ren dou yong shou ji he dian nao. Zu bu chu hu jiu neng zuo hen duo shi qing. Xian da kai shou ji, ran hou qing qing yi dian, jiu ke yi gou wu, zhi fu, liao tian. Wang luo rang sheng huo geng bian jie le. Dan shi, wang luo ye you yi xie fu ying xiang. Bi ru, you ren chen mi wang luo you xi, ying xiang le gong zuo he xue xi. Hai you ren dan xin wang luo an quan wen ti. Suo yi, wo men yao he li shi yong wang luo, bu neng bu shang wang, ye bu neng zheng tian shang wang. Wang luo zhi shi gong ju, wo men de sheng huo cai shi zhong dian.','Mang thay doi song chung ta. Truoc day, nguoi ta phai ra ngoai mua do, di ngan hang, den thu vien. Nay, hau nhu ai cung dung DT va may tinh. Ko can ra ngoai ma lam duoc nhieu viec. Mo DT len roi cham mot cai la mua, thanh toan, tro chuyen. Internet tien loi hon. Nhung cung co mat trai. Nhu dam me game, anh huong cong viec. Rang lo an toan mang. Can dung mang hop ly. Internet chi la cong cu, cuoc song moi la chinh.','medium',200,1);
$L18l=l($conn,$L18,'Mang internet','A: Ban hay dung mang lam gi? B: Toi hay mua sam va xem tin tuc. A: Ban co so mat an toan ko? B: Co, nhung toi chon web uy tin. A: Nho dung mang hop ly nhe. B: Cam on, toi biet roi.','A: Ni jing chang yong wang luo zuo shen me? B: Wo jing chang gou wu he kan xin wen. A: Ni dan xin an quan ma? B: Dan xin, dan wo xuan zheng gui wang zhan. A: Ji de he li yong wang luo. B: Xie xie, wo zhi dao.','A: Ban hay dung mang lam gi? B: Toi hay mua sam va xem tin. A: Ban lo an toan ko? B: Co, nhung toi chon web uy tin. A: Nho dung mang hop ly. B: Cam on, toi biet.','1');
lq($conn,$L18l,'B thuong dung mang lam gi?','{"A":"Hoc bai","B":"Mua sam va xem tin","C":"Cau ca"}','Mua sam va xem tin','Wo jing chang gou wu he kan xin wen.','multiple_choice',1);
lq($conn,$L18l,'B co lo ve an toan mang ko?','{"A":"Ko lo gi","B":"Co lo","C":"Ko biet"}','Co lo','Dan xin, dan wo xuan zheng gui wang zhan.','multiple_choice',2);
lq($conn,$L18l,'A khuyen B dieu gi?','{"A":"Dung mang nhieu hon","B":"Dung mang hop ly","C":"Ko dung mang nua"}','Dung mang hop ly','Ji de he li yong wang luo.','multiple_choice',3);
$E18_1=e($conn,$L18,'Chon dap an','"上网" la?','multiple_choice','easy',1,'B',1);
eo($conn,$E18_1,'Xuong mang','A',0,1); eo($conn,$E18_1,'Len mang','B',1,2); eo($conn,$E18_1,'Tat mang','C',0,3);
$E18_2=e($conn,$L18,'Dich','"Wang luo hen fang bian."','translation','medium',1,'网络很方便。',2);
$E18_3=e($conn,$L18,'Dien tu','网上购___很方便。','fill_blank','medium',1,'物',3);
$E18_4=e($conn,$L18,'Sap xep','网络 / 改变 / 生活 / 了','sentence_order','medium',1,'网络改变了生活。',4);
$E18_5=e($conn,$L18,'Dung sai','"几乎" la "hau nhu".','true_false','easy',1,'true',5);
eo($conn,$E18_5,'Dung','A',1,1); eo($conn,$E18_5,'Sai','B',0,2);
$E18_6=e($conn,$L18,'Dien tu','Xian zai ji hu ren ren dou yong shou ji zhi ___.','fill_blank','medium',1,'付',6);
$E18_7=e($conn,$L18,'Chon dap an','"然后" chi?','multiple_choice','medium',1,'B',7);
eo($conn,$E18_7,'Nguyen nhan','A',0,1); eo($conn,$E18_7,'Thu tu','B',1,2); eo($conn,$E18_7,'Ket qua','C',0,3);
$E18_8=e($conn,$L18,'Dien tu','先付款，___后发货。','fill_blank','medium',1,'然',8);
$E18_9=e($conn,$L18,'Chon dap an','"不能不" co nghia?','multiple_choice','medium',1,'C',9);
eo($conn,$E18_9,'Co the ko','A',0,1); eo($conn,$E18_9,'Ko can','B',0,2); eo($conn,$E18_9,'Ko the ko','C',1,3);
$E18_10=e($conn,$L18,'Dien tu','___络安全很重要。','fill_blank','medium',1,'网',10);
foreach ([$v18_1,$v18_2,$v18_3,$v18_4,$v18_5,$v18_6,$v18_7,$v18_8,$v18_9,$v18_10,$v18_11,$v18_12] as $i=>$vid) if ($vid) rv($conn,$L18,$vid,'core',$i+1);
echo " HSK4 L18 done: $v18 vocab, 3 grammar, 3 dialogues, 1 reading, 1 listening, 10 exercises\n";

$L19=createLesson($conn,4,19,'Bai 19: Ti yu duan lian shen ti','The thao ren luyen co the. Cau truc "le...le..." + V. Phó tu "gang" + V. Cau truc "yue lai yue" + tinh tu.','["The thao","Suc khoe","Van dong"]','The thao','medium','HSK4 Bai 19: Tu vung the thao. Cau truc 了...了... + V (da roi). Phó tu 刚 (vua moi). 越来越 + tinh tu.');
$v19=0;
$v19_1=v($conn,$L19,4,'体育','ti yu','the thao','thể thao','我喜欢体育。','Wo xi huan ti yu.','Toi thich the thao.','noun','Mon the thao.',++$v19);
$v19_2=v($conn,$L19,4,'锻炼','duan lian','ren luyen','rèn luyện','每天锻炼。','Mei tian duan lian.','Ren luyen moi ngay.','verb','Tap luyen.',++$v19);
$v19_3=v($conn,$L19,4,'身体','shen ti','co the','cơ thể','身体很健康。','Shen ti hen jian kang.','Co the rat khoe.','noun','Than the con nguoi.',++$v19);
$v19_4=v($conn,$L19,4,'健康','jian kang','suc khoe','sức khỏe','祝你健康。','Zhu ni jian kang.','Chuc ban suc khoe.','adj/noun','Tinh trang tot.',++$v19);
$v19_5=v($conn,$L19,4,'运动','yun dong','van dong','vận động','运动一下。','Yun dong yi xia.','Van dong mot chut.','verb/noun','Hoat dong co the.',++$v19);
$v19_6=v($conn,$L19,4,'跑步','pao bu','chay bo','chạy bộ','每天早上跑步。','Mei tian zao shang pao bu.','Moi sang chay bo.','verb','Chay nhanh.',++$v19);
$v19_7=v($conn,$L19,4,'游泳','you yong','boi','bơi','去游泳。','Qu you yong.','Di boi.','verb','Mon boi loc.',++$v19);
$v19_8=v($conn,$L19,4,'比赛','bi sai','thi dau','thi đấu','看比赛。','Kan bi sai.','Xem thi dau.','noun/verb','Tran dau.',++$v19);
$v19_9=v($conn,$L19,4,'参加','can jia','tham gia','tham gia','参加运动会。','Can jia yun dong hui.','Tham gia hoi thao.','verb','Gia nhap.',++$v19);
$v19_10=v($conn,$L19,4,'坚持','jian chi','kien tri','kiên trì','坚持锻炼。','Jian chi duan lian.','Kien tri ren luyen.','verb','Ko bo.',++$v19);
$v19_11=v($conn,$L19,4,'减肥','jian fei','giam can','giảm cân','在减肥。','Zai jian fei.','Giam can.','verb','Giam trong luong.',++$v19);
$v19_12=v($conn,$L19,4,'效果','xiao guo','hieu qua','hiệu quả','效果很好。','Xiao guo hen hao.','Hieu qua rat tot.','noun','Ket qua.',++$v19);
$g19_1=g($conn,$L19,'Cau truc 了...了 + V...了','了 + V + (Tan ngu) + 了','Da...roi','Dien ta hanh dong da hoan thanh.','跑了步了 = Da chay bo roi.','Ket qua.',1);
ge($conn,$g19_1,'我跑了步了。','Wo pao le bu le.','Toi da chay bo roi.',1);
ge($conn,$g19_1,'他游了泳了。','Ta you le yong le.','Anh ay da boi roi.',2);
$g19_2=g($conn,$L19,'Phó tu 刚 + V (xay ra truoc)','刚 + V + (thoi/gio) + le','Vua moi','刚 chi hanh dong vua moi xay ra, thuong +了.','刚吃完饭 = Vua an xong.','Gan day.',2);
ge($conn,$g19_2,'我刚跑完步。','Wo gang pao wan bu.','Toi vua chay bo xong.',1);
ge($conn,$g19_2,'他刚参加了比赛。','Ta gang can jia le bi sai.','Anh ay vua tham gia tran dau.',2);
$g19_3=g($conn,$L19,'越来越 + Tinh tu','越来越 + Tinh tu','Ngay cang','Su thay doi lien tuc.','越来越健康 = Ngay cang khoe.','Tang dan.',3);
ge($conn,$g19_3,'身体越来越好了。','Shen ti yue lai yue hao le.','Co the ngay cang tot.',1);
ge($conn,$g19_3,'跑步越来越快了。','Pao bu yue lai yue kuai le.','Chay ngay cang nhanh.',2);
$d19_1=d($conn,$L19,'Thoi quen the thao','Thoi quen tap.',1);
ds($conn,$d19_1,'Lan','你平时做什么运动？','Ni ping shi zuo shen me yun dong?','Ban thuong tap gi?',1);
ds($conn,$d19_1,'Minh','我喜欢跑步和游泳。','Wo xi huan pao bu he you yong.','Toi thich chay bo va boi.',2);
ds($conn,$d19_1,'Lan','多久一次？','Duo jiu yi ci?','Bao lau mot lan?',3);
ds($conn,$d19_1,'Minh','每周三次。','Mei zhou san ci.','Moi tuan 3 lan.',4);
$d19_2=d($conn,$L19,'Giam can','Giam can.',2);
ds($conn,$d19_2,'Minh','我最近胖了，想减肥。','Wo zui jin pang le, xiang jian fei.','Toi gan day beo, muon giam can.',1);
ds($conn,$d19_2,'Lan','那你多运动啊。','Na ni duo yun dong a.','The ban tap nhieu di.',2);
ds($conn,$d19_2,'Minh','我每天跑步，但效果不明显。','Wo mei tian pao bu, dan xiao guo bu ming xian.','Toi chay moi ngay nhung ko ro.',3);
ds($conn,$d19_2,'Lan','坚持就会有效果的。','Jian chi jiu hui you xiao guo de.','Kien tri se co hieu qua.',4);
$d19_3=d($conn,$L19,'Xem thi dau','Thi dau.',3);
ds($conn,$d19_3,'Lan','你看奥运会吗？','Ni kan ao yun hui ma?','Ban xem Olympic ko?',1);
ds($conn,$d19_3,'Minh','看啊，特别是游泳比赛。','Kan a, te bie shi you yong bi sai.','Co, nhat la boi.',2);
ds($conn,$d19_3,'Lan','我最喜欢看跑步。','Wo zui xi huan kan pao bu.','Toi thich xem chay nhat.',3);
ds($conn,$d19_3,'Minh','运动让人健康又快乐。','Yun dong rang ren jian kang you kuai le.','Van dong lam nguoi khoe va vui.',4);
r($conn,$L19,'The thao suc khoe','生命在于运动。运动对健康非常重要。每天坚持运动，身体会越来越好。运动的方式有很多，比如跑步、游泳、打球、散步等。刚开始运动时，不要太累，要慢慢来。我每天早晨都跑步。跑了步了以后，感觉一整天都很有精神。运动不仅能让身体更健康，还能让心情更好。压力大的时候，运动一下，可以放松心情。减肥的人更需要运动。刚运动完可能很累，但坚持一段时间，效果就出来了。运动最重要的是坚持。越来越多人开始意识到运动的好处。让我们一起动起来吧！','Sheng ming zai yu yun dong. Yun dong dui jian kang fei chang zhong yao. Mei tian jian chi yun dong, shen ti hui yue lai yue hao. Yun dong de fang shi you hen duo, bi ru pao bu, you yong, da qiu, san bu deng. Gang kai shi yun dong shi, bu yao tai lei, yao man man lai. Wo mei tian zao chen dou pao bu. Pao le bu le yi hou, gan jue yi zheng tian dou hen you jing shen. Yun dong bu jin neng rang shen ti geng jian kang, hai neng rang xin qing geng hao. Ya li da de shi hou, yun dong yi xia, ke yi fang song xin qing. Jian fei de ren geng xu yao yun dong. Gang yun dong wan ke neng hen lei, dan jian chi yi duan shi jian, xiao guo jiu chu lai le. Yun dong zui zhong yao de shi jian chi. Yue lai yue duo ren kai shi yi shi dao yun dong de hao chu. Rang wo men yi qi dong qi lai ba!','Song la van dong. Van dong voi suc khoe rat quan trong. Moi ngay tap, co the ngay cang tot. Nhieu cach tap: chay bo, boi, da bong, di bo. Moi bat dau dung met qua, tu tu den. Toi moi sang deu chay bo. Chay xong, cam giac ca ngay co tinh than. Van dong ko chi khoe ma con vui. Luc ap luc, van dong de thu gian. Nguoi giam can can van dong hon. Vua tap xong co the met, nhung kien tri se co hieu qua. Quan trong nhat la kien tri. Ngay cang nhieu nguoi nhan ra loi ich cua van dong. Hay cung van dong!','medium',210,1);
$L19l=l($conn,$L19,'The thao','A: Ban thich mon the thao nao? B: Toi thich chay bo va boi. A: Ban thuong tap khi nao? B: Buoi sang, khoang 30 phut. A: Tot qua, van dong tot cho suc khoe. B: Dung the, ban cung nen tap.','A: Ni xi huan shen me ti yu? B: Wo xi huan pao bu he you yong. A: Ni jing chang shen me shi hou duan lian? B: Zao shang, da gai san shi fen zhong. A: Zhen hao, yun dong dui jian kang hao. B: Shi de, ni ye ying gai duan lian.','A: Ban thich the thao nao? B: Toi thich chay bo va boi. A: Ban hay tap luc nao? B: Buoi sang, khoang 30 phut. A: Tot qua, tap tot cho suc khoe. B: Dung, ban cung nen tap.','1');
lq($conn,$L19l,'B thich mon the thao nao?','{"A":"Da bong","B":"Chay bo va boi","C":"Cau long"}','Chay bo va boi','Wo xi huan pao bu he you yong.','multiple_choice',1);
lq($conn,$L19l,'B tap luc nao?','{"A":"Chieu","B":"Buoi sang","C":"Toi"}','Buoi sang','Zao shang.','multiple_choice',2);
lq($conn,$L19l,'Tap trong bao lau?','{"A":"15 phut","B":"30 phut","C":"1 tieng"}','30 phut','Da gai san shi fen zhong.','multiple_choice',3);
$E19_1=e($conn,$L19,'Chon dap an','"跑步" la?','multiple_choice','easy',1,'A',1);
eo($conn,$E19_1,'Chay bo','A',1,1); eo($conn,$E19_1,'Di bo','B',0,2); eo($conn,$E19_1,'Nhay','C',0,3);
$E19_2=e($conn,$L19,'Dich','"Shen ti yue lai yue hao."','translation','medium',1,'身体越来越好了。',2);
$E19_3=e($conn,$L19,'Dien tu','每天段___身体好。','fill_blank','medium',1,'炼',3);
$E19_4=e($conn,$L19,'Sap xep','健康 / 运动 / 重要 / 很 / 对','sentence_order','medium',1,'运动对健康很重要。',4);
$E19_5=e($conn,$L19,'Dung sai','"游泳" la "boi".','true_false','easy',1,'true',5);
eo($conn,$E19_5,'Dung','A',1,1); eo($conn,$E19_5,'Sai','B',0,2);
$E19_6=e($conn,$L19,'Dien tu','Wo gang pao wan ___.','fill_blank','medium',1,'步',6);
$E19_7=e($conn,$L19,'Chon dap an','"刚" chi?','multiple_choice','medium',1,'A',7);
eo($conn,$E19_7,'Vua moi','A',1,1); eo($conn,$E19_7,'Sap toi','B',0,2); eo($conn,$E19_7,'Dang','C',0,3);
$E19_8=e($conn,$L19,'Dien tu','___来___健康了。','fill_blank','medium',1,'越来越',8);
$E19_9=e($conn,$L19,'Chon dap an','"了...了" dien ta?','multiple_choice','medium',1,'C',9);
eo($conn,$E19_9,'Dang lam','A',0,1); eo($conn,$E19_9,'Sap lam','B',0,2); eo($conn,$E19_9,'Da xong','C',1,3);
$E19_10=e($conn,$L19,'Dien tu','Jian chi jiu hui you xiao ___.','fill_blank','medium',1,'果',10);
foreach ([$v19_1,$v19_2,$v19_3,$v19_4,$v19_5,$v19_6,$v19_7,$v19_8,$v19_9,$v19_10,$v19_11,$v19_12] as $i=>$vid) if ($vid) rv($conn,$L19,$vid,'core',$i+1);
echo " HSK4 L19 done: $v19 vocab, 3 grammar, 3 dialogues, 1 reading, 1 listening, 10 exercises\n";

$L20=createLesson($conn,4,20,'Bai 20: Gan xie sheng huo zhong de mei yi jian shi','Biet on cuoc song. Cau truc "dui...you yong" + "...hen gan xie". Phó tu "yi jing" + V. Cau truc "shou xian...ran hou...zui hou...".','["Biet on","Hanh phuc","Cuoc song"]','Biet on','medium','HSK4 Bai 20: Tu vung biet on. Cau truc 对...有用 (co ich cho...). Phó tu 已经 + V (da). 首先...然后...最后... (dau tien...sau do...cuoi cung...).');
$v20=0;
$v20_1=v($conn,$L20,4,'感谢','gan xie','cam on','cảm ơn','感谢你的帮助。','Gan xie ni de bang zhu.','Cam on su giup do cua ban.','verb','Biet on.',++$v20);
$v20_2=v($conn,$L20,4,'帮助','bang zhu','giup do','giúp đỡ','互相帮助。','Hu xiang bang zhu.','Giup do lan nhau.','verb/noun','Su tro giup.',++$v20);
$v20_3=v($conn,$L20,4,'礼物','li wu','qua tang','quà tặng','送礼物。','Song li wu.','Tang qua.','noun','Mon qua.',++$v20);
$v20_4=v($conn,$L20,4,'感动','gan dong','cam dong','cảm động','很感动。','Hen gan dong.','Rat cam dong.','adj/verb','Tac dong tinh cam.',++$v20);
$v20_5=v($conn,$L20,4,'幸福','xing fu','hanh phuc','hạnh phúc','你很幸福。','Ni hen xing fu.','Ban rat hanh phuc.','adj/noun','Cam giac vui.',++$v20);
$v20_6=v($conn,$L20,4,'珍惜','zhen xi','tran trong','trân trọng','珍惜时间。','Zhen xi shi jian.','Tran trong thoi gian.','verb','Quy trong.',++$v20);
$v20_7=v($conn,$L20,4,'友谊','you yi','tinh ban','tình bạn','友谊万岁。','You yi wan sui.','Tinh ban muon nam.','noun','Tinh cam ban be.',++$v20);
$v20_8=v($conn,$L20,4,'关心','guan xin','quan tam','quan tâm','关心别人。','Guan xin bie ren.','Quan tam nguoi khac.','verb','De y.',++$v20);
$v20_9=v($conn,$L20,4,'支持','zhi chi','ung ho','ủng hộ','支持你的决定。','Zhi chi ni de jue ding.','Ung ho quyet dinh ban.','verb','Dong tinh.',++$v20);
$v20_10=v($conn,$L20,4,'努力','nu li','co gang','cố gắng','谢谢你努力。','Xie xie ni nu li.','Cam on co gang cua ban.','adj/adv','Het suc.',++$v20);
$v20_11=v($conn,$L20,4,'希望','xi wang','hy vong','hy vọng','希望你好。','Xi wang ni hao.','Hy vong ban tot.','verb/noun','Mong muon.',++$v20);
$v20_12=v($conn,$L20,4,'未来','wei lai','tuong lai','tương lai','未来更美好。','Wei lai geng mei hao.','Tuong lai dep hon.','noun','Thoi gian sap toi.',++$v20);
$g20_1=g($conn,$L20,'Cau truc 对...有用','对 + Nguoi/vat + 有用','Co ich cho','Dien ta mot viec co loi cho ai do.','对学习有用 = Co ich cho viec hoc.','Loi ich.',1);
ge($conn,$g20_1,'这本书对学习中文很有用。','Zhe ben shu dui xue xi zhong wen hen you yong.','Cuon sach nay co ich cho hoc tieng Trung.',1);
ge($conn,$g20_1,'运动对身体很有用。','Yun dong dui shen ti hen you yong.','The thao co ich cho co the.',2);
$g20_2=g($conn,$L20,'Phó tu 已经 + V','已经 + V + le','Da roi','Thoi hanh dong da hoan thanh truoc thoi diem noi.','已经学完了 = Da hoc xong roi.','Hoan thanh.',2);
ge($conn,$g20_2,'我已经学完HSK4了。','Wo yi jing xue wan HSK4 le.','Toi da hoc xong HSK4 roi.',1);
ge($conn,$g20_2,'他已经帮助了很多人。','Ta yi jing bang zhu le hen duo ren.','Anh ay da giup nhieu nguoi.',2);
$g20_3=g($conn,$L20,'首先...然后...最后...','首先 + V...然后 + V...最后 + V...','Dau tien...sau do...cuoi cung...','Trinh tu cac buoc.','首先复习，然后考试，最后总结 = On tap, thi, tong ket.','Tinh tu.',3);
ge($conn,$g20_3,'首先感谢父母，然后感谢老师，最后感谢朋友。','Shou xian gan xie fu mu, ran hou gan xie lao shi, zui hou gan xie peng you.','Dau tien cam on cha me, roi cam on thay co, cuoi cung cam on ban be.',1);
ge($conn,$g20_3,'首先制定计划，然后执行，最后总结。','Shou xian zhi ding ji hua, ran hou zhi xing, zui hou zong jie.','Dau tien lap ke hoach, roi thuc hien, cuoi cung tong ket.',2);
$d20_1=d($conn,$L20,'Cam on gia dinh','Biet on gia dinh.',1);
ds($conn,$d20_1,'Lan','你最想感谢谁？','Ni zui xiang gan xie shei?','Ban muon cam on ai nhat?',1);
ds($conn,$d20_1,'Minh','父母。没有他们的支持，就没有今天的我。','Fu mu. Mei you ta men de zhi chi, jiu mei you jin tian de wo.','Cha me. Ko co ho ung ho, ko co toi hom nay.',2);
ds($conn,$d20_1,'Lan','是啊，父母的爱最伟大。','Shi a, fu mu de ai zui wei da.','Dung, tinh yeu cha me vi dai nhat.',3);
ds($conn,$d20_1,'Minh','所以我一定要努力学习回报他们。','Suo yi wo yi ding yao nu li xue xi hui bao ta men.','Nen toi nhat dinh hoc de bao dap.',4);
$d20_2=d($conn,$L20,'Biet on ban be','Cam on ban.',2);
ds($conn,$d20_2,'Lan','你觉得友谊是什么？','Ni jue de you yi shi shen me?','Ban nghi tinh ban la gi?',1);
ds($conn,$d20_2,'Minh','友谊就是在你需要的时候，有人关心你。','You yi jiu shi zai ni xu yao de shi hou, you ren guan xin ni.','Tinh ban la khi ban can, co nguoi quan tam ban.',2);
ds($conn,$d20_2,'Lan','说得好。有朋友很幸福。','Shuo de hao. You peng you hen xing fu.','Noi hay. Co ban la HP.',3);
ds($conn,$d20_2,'Minh','对，要珍惜每一个朋友。','Dui, yao zhen xi mei yi ge peng you.','Dung, tran trong moi nguoi ban.',4);
$d20_3=d($conn,$L20,'Tuong lai tuoi sang','Ve tuong lai.',3);
ds($conn,$d20_3,'Minh','毕业以后你有什么打算？','Bi ye yi hou ni you shen me da suan?','Sau tot nghiep ban dinh lam gi?',1);
ds($conn,$d20_3,'Lan','先找工作，然后存钱去旅游。','Xian zhao gong zuo, ran hou cun qian qu lv you.','Tim viec truoc, roi tiet kiem di du lich.',2);
ds($conn,$d20_3,'Minh','不错，你对未来充满希望。','Bu cuo, ni dui wei lai chong man xi wang.','Tot, ban day hy vong ve tuong lai.',3);
ds($conn,$d20_3,'Lan','谢谢。希望我们的未来都更美好。','Xie xie. Xi wang wo men de wei lai dou geng mei hao.','Cam on. Hy vong tuong lai chung ta deu dep hon.',4);
r($conn,$L20,'Biet on cuoc song','感谢是一种美好的情感。生活中，我们要感谢很多人和事。首先，要感谢父母，感谢他们给了我们生命和无私的爱。其次，要感谢老师，感谢他们的教导和关心。还要感谢朋友，感谢他们的陪伴和支持。最后，也要感谢生活中遇到的困难和挑战，因为它们让我们成长。一个懂得感谢的人，一定是一个幸福的人。他们已经学会了珍惜身边的一切。感恩让我们的心灵更丰富，让人际关系更美好。不要等到失去才懂得珍惜，从现在开始，对身边的人说一声"谢谢"吧。生活已经给了我们很多，要学会感恩。','Gan xie shi yi zhong mei hao de qing gan. Sheng huo zhong, wo men yao gan xie hen duo ren he shi. Shou xian, yao gan xie fu mu, gan xie ta men gei le wo men sheng ming he wu si de ai. Qi ci, yao gan xie lao shi, gan xie ta men de jiao dao he guan xin. Hai yao gan xie peng you, gan xie ta men de pei ban he zhi chi. Zui hou, ye yao gan xie sheng huo zhong yu dao de kun nan he tiao zhan, yin wei ta men rang wo men cheng zhang. Yi ge dong de gan xie de ren, yi ding shi yi ge xing fu de ren. Ta men yi jing xue hui le zhen xi shen bian de yi qie. Gan en rang wo men de xin ling geng feng fu, rang ren ji guan xi geng mei hao. Bu yao deng dao shi qu cai dong de zhen xi, cong xian zai kai shi, dui shen bian de ren shuo yi sheng "xie xie" ba. Sheng huo yi jing gei le wo men hen duo, yao xue hui gan en.','Cam on la cam xuc dep. Trong song, ta cam on nhieu nguoi va viec. Truoc het, cam on cha me da cho ta song va tinh yeu. Ke tiep, cam on thay co da day va quan tam. Va cam on ban be da ben canh ung ho. Cuoi cung, cam on kho khan vi chung giup ta lon. Nguoi biet cam on la nguoi HP. Ho da biet tran trong moi thu. Biet on giup tam hon phong phu. Dung cho den khi mat moi biet quy. Hom nay hay noi "cam on" voi nguoi than. Song cho ta nhieu, hay biet on.','medium',220,1);
$L20l=l($conn,$L20,'Loi cam on','A: Ban muon cam on ai nhat? B: Toi muon cam on cha me toi. A: Vi sao? B: Vi ho da giup toi rat nhieu. A: Ban co noi voi ho chua? B: Da noi roi, hom qua toi vua noi.','A: Ni zui xiang gan xie shei? B: Wo zui xiang gan xie wo de fu mu. A: Wei shen me? B: Yin wei ta men bang zhu le wo hen duo. A: Ni dui ta men shuo le ma? B: Shuo le, zuo tian gang shuo.','A: Ban cam on ai nhat? B: Cha me toi. A: Sao? B: Vi ho giup toi nhieu. A: Ban noi voi ho chua? B: Noi roi, hom qua vua noi.','1');
lq($conn,$L20l,'B muon cam on ai nhat?','{"A":"Ban be","B":"Cha me","C":"Thay co"}','Cha me','Wo zui xiang gan xie wo de fu mu.','multiple_choice',1);
lq($conn,$L20l,'Tai sao B cam on ho?','{"A":"Ho cho tien","B":"Ho giup toi nhieu","C":"Ho dep"}','Ho giup toi nhieu','Yin wei ta men bang zhu le wo hen duo.','multiple_choice',2);
lq($conn,$L20l,'B da noi voi ho chua?','{"A":"Chua","B":"Da noi","C":"Ko dinh noi"}','Da noi','Shuo le, zuo tian gang shuo.','multiple_choice',3);
$E20_1=e($conn,$L20,'Chon dap an','"感谢" la?','multiple_choice','easy',1,'C',1);
eo($conn,$E20_1,'Ghet','A',0,1); eo($conn,$E20_1,'Quen','B',0,2); eo($conn,$E20_1,'Cam on','C',1,3);
$E20_2=e($conn,$L20,'Dich','"Zhen xi shi jian."','translation','medium',1,'珍惜时间。',2);
$E20_3=e($conn,$L20,'Dien tu','我很感___你的帮助。','fill_blank','medium',1,'谢',3);
$E20_4=e($conn,$L20,'Sap xep','感谢 / 要 / 父母 / 我们','sentence_order','medium',1,'我们要感谢父母。',4);
$E20_5=e($conn,$L20,'Dung sai','"支持" nghia la "ung ho".','true_false','easy',1,'true',5);
eo($conn,$E20_5,'Dung','A',1,1); eo($conn,$E20_5,'Sai','B',0,2);
$E20_6=e($conn,$L20,'Dien tu','Zhe ben shu dui xue xi hen you ___.','fill_blank','medium',1,'用',6);
$E20_7=e($conn,$L20,'Chon dap an','"对...有用" co nghia?','multiple_choice','medium',1,'B',7);
eo($conn,$E20_7,'Co hai','A',0,1); eo($conn,$E20_7,'Co ich','B',1,2); eo($conn,$E20_7,'Khong tot','C',0,3);
$E20_8=e($conn,$L20,'Dien tu','Wo yi jing xue wan HSK4 ___.','fill_blank','medium',1,'了',8);
$E20_9=e($conn,$L20,'Chon dap an','"首先...然后...最后..." chi?','multiple_choice','medium',1,'A',9);
eo($conn,$E20_9,'Trinh tu','A',1,1); eo($conn,$E20_9,'Nguyen nhan','B',0,2); eo($conn,$E20_9,'Tuong phan','C',0,3);
$E20_10=e($conn,$L20,'Dien tu','___谢你努力。','fill_blank','medium',1,'感谢',10);
foreach ([$v20_1,$v20_2,$v20_3,$v20_4,$v20_5,$v20_6,$v20_7,$v20_8,$v20_9,$v20_10,$v20_11,$v20_12] as $i=>$vid) if ($vid) rv($conn,$L20,$vid,'core',$i+1);
echo " HSK4 L20 done: $v20 vocab, 3 grammar, 3 dialogues, 1 reading, 1 listening, 10 exercises\n";
