<?php
require_once __DIR__ . '/seed_helpers.php';
$conn->exec("SET FOREIGN_KEY_CHECKS=0");
$L1=createLesson($conn,4,1,'Bai 1: Jian dan de ai qing','Tinh yeu gian di. Phó tu "cong lai" + phu dinh. Cau truc "dui...lai shuo".','["Tinh yeu","Hon nhan","Quan he"]','Tinh yeu','medium','HSK4 Bai 1: Tu vung tinh yeu. Phó tu 从来 (chua bao gio) chi dung cau phu dinh. Cau truc 对...来说.');
$v1=0;
$v1_1=v($conn,$L1,4,'爱情','ai qing','tinh yeu','tinh yeu','他们的爱情很美好。','Ta men de ai qing hen mei hao.','Tinh yeu cua ho rat dep.','noun','Tinh cam nam nu.',++$v1);
$v1_2=v($conn,$L1,4,'简单','jian dan','don gian','don gian','生活很简单。','Sheng huo hen jian dan.','Cuoc song rat don gian.','adj','Trai nghia: fu za.',++$v1);
$v1_3=v($conn,$L1,4,'幸福','xing fu','hanh phuc','hanh phuc','一家人很幸福。','Yi jia ren hen xing fu.','Ca nha rat hanh phuc.','adj/noun','Trang thai tot dep.',++$v1);
$v1_4=v($conn,$L1,4,'从来','cong lai','tu truoc den nay','chua tung','我从来不喜欢。','Wo cong lai bu xi huan.','Toi chua bao gio thich.','adv','Chi dung cau phu dinh.',++$v1);
$v1_5=v($conn,$L1,4,'结婚','jie hun','ket hon','cuoi','他们去年结婚了。','Ta men qu nian jie hun le.','Ho nam ngoai ket hon.','verb','Phan ly dong tu.',++$v1);
$v1_6=v($conn,$L1,4,'感情','gan qing','tinh cam','tinh cam','感情很好。','Gan qing hen hao.','Tinh cam rat tot.','noun','Cam xuc giua nguoi.',++$v1);
$v1_7=v($conn,$L1,4,'浪漫','lang man','lang man','lang man','很浪漫的约会。','Hen lang man de yue hui.','Buoi hen rat lang man.','adj','Tu vay muon.',++$v1);
$v1_8=v($conn,$L1,4,'永远','yong yuan','mai mai','mai mai','永远爱你。','Yong yuan ai ni.','Mai mai yeu em.','adv','Thoi gian vo tan.',++$v1);
$v1_9=v($conn,$L1,4,'温柔','wen rou','diu dang','diu dang','她很温柔。','Ta hen wen rou.','Co ay rat diu dang.','adj','Tinh cach hien diu.',++$v1);
$v1_10=v($conn,$L1,4,'相信','xiang xin','tin tuong','tin','我相信你。','Wo xiang xin ni.','Toi tin ban.','verb','Tin vao ai do.',++$v1);
$v1_11=v($conn,$L1,4,'感动','gan dong','cam dong','cam dong','很感动的故事。','Hen gan dong de gu shi.','Cau chuyen rat cam dong.','verb/adj','Xuc dong sau sac.',++$v1);
$v1_12=v($conn,$L1,4,'责任','ze ren','trach nhiem','trac nhiem','爱情需要责任。','Ai qing xu yao ze ren.','Tinh yeu can trach nhiem.','noun','Nghia vu phai lam.',++$v1);
$g1_1=g($conn,$L1,'Phó tu 从来 + phu dinh','从来 + dōu/yĕ + bù/méi + Đông tu','Chua bao gio','从来 chi dung cau phu dinh, nhan manh chua tung xay ra.','从来不喜欢 = chua bao gio thich.','Phu dinh hoan toan.',1);
ge($conn,$g1_1,'我从来不相信一见钟情。','Wo cong lai bu xiang xin yi jian zhong qing.','Toi chua bao gio tin set danh.',1);
ge($conn,$g1_2,'他从来没说过爱我。','Ta cong lai mei shuo guo ai wo.','Anh ay chua tung noi yeu toi.',2);
$g1_2=g($conn,$L1,'Cau truc 对...来说','对 + Nguoi + 来说','Doi voi ma noi','对...来说 dua ra danh gia tu goc nhin.','对我来说，幸福很简单 = Voi toi HP don gian.','Goc nhin.',2);
ge($conn,$g1_2,'对我来说，幸福很简单。','Dui wo lai shuo, xing fu hen jian dan.','Voi toi, HP rat don gian.',1);
ge($conn,$g1_2,'对年轻人来说，爱情很重要。','Dui nian qing ren lai shuo, ai qing hen zhong yao.','Voi nguoi tre, tinh yeu quan trong.',2);
$g1_3=g($conn,$L1,'越来越','越来越 + Tinh tu','Ngay cang','越来越 dien ta su thay doi tang dan.','越来越幸福 = ngay cang HP.','Tang dan.',3);
ge($conn,$g1_3,'他们的感情越来越好。','Ta men de gan qing yue lai yue hao.','Tinh cam ho ngay cang tot.',1);
ge($conn,$g1_3,'她越来越漂亮了。','Ta yue lai yue piao liang le.','Co ay ngay cang xinh.',2);
$g1_4=g($conn,$L1,'Cau truc 不是...而是...','不是 + A + 而是 + B','Khong phai A ma la B','Phu dinh A roi khang dinh B. Nhan manh su tuong phan.','不是简单而是幸福 = Khong phai don gian ma la HP.','Tuong phan.',4);
ge($conn,$g1_4,'爱情不是浪漫而是责任。','Ai qing bu shi lang man er shi ze ren.','Tinh yeu khong phai lang man ma la trach nhiem.',1);
ge($conn,$g1_4,'幸福不是得到多而是计较少。','Xing fu bu shi de dao duo er shi ji jiao shao.','HP khong phai nhan nhieu ma la bot tinh.',2);
$d1_1=d($conn,$L1,'Quan niem tinh yeu','Ban ve tinh yeu.',1);
ds($conn,$d1_1,'Lan','你觉得什么是真正的爱情？','Ni jue de shen me shi zhen zheng de ai qing?','Ban nghi tinh yeu dich thuc la gi?',1);
ds($conn,$d1_1,'Minh','对我来说，爱情不是浪漫的约会，而是每天的关心。','Dui wo lai shuo, ai qing bu shi lang man de yue hui, er shi mei tian de guan xin.','Voi toi, tinh yeu khong phai hen ho ma la quan tam hang ngay.',2);
ds($conn,$d1_1,'Lan','你说得对。感情需要两个人一起努力。','Ni shuo de dui. Gan qing xu yao liang ge ren yi qi nu li.','Ban noi dung. Tinh cam can hai nguoi cung co gang.',3);
ds($conn,$d1_1,'Minh','是啊，简单的爱情最幸福。','Shi a, jian dan de ai qing zui xing fu.','Tinh yeu gian di la hanh phuc nhat.',4);
ds($conn,$d1_1,'Lan','你父母感情一定很好吧？','Ni fu mu gan qing yi ding hen hao ba?','Bo me ban tinh cam chac tot ha?',5);
ds($conn,$d1_1,'Minh','对，他们从来不会吵架。','Dui, ta men cong lai bu hui chao jia.','Ho chua bao gio cai nhau.',6);
$d1_2=d($conn,$L1,'Chuyen hon nhan','Noi ve hon nhan.',2);
ds($conn,$d1_2,'Minh','你和男朋友打算什么时候结婚？','Ni he nan peng you da suan shen me shi hou jie hun?','Ban va ban trai dinh khi nao cuoi?',1);
ds($conn,$d1_2,'Lan','我们还没决定。结婚是大事，不能着急。','Wo men hai mei jue ding. Jie hun shi da shi, bu neng zhao ji.','Bon minh chua quyet. Cuoi la chuyen lon.',2);
ds($conn,$d1_2,'Minh','当然要找到对的人。','Dang ran yao zhao dao dui de ren.','Phai tim dung nguoi.',3);
ds($conn,$d1_2,'Lan','我希望能和温柔体贴的人过一辈子。','Wo xi wang neng he wen rou ti tie de ren guo yi bei zi.','Toi hy vong song ca doi voi nguoi diu dang.',4);
$d1_3=d($conn,$L1,'Tinh cam gia dinh','Tinh cam gia dinh.',3);
ds($conn,$d1_3,'Lan','结婚以后，感情会变吗？','Jie hun yi hou, gan qing hui bian ma?','Sau cuoi tinh cam co thay doi?',1);
ds($conn,$d1_3,'Minh','会变，但可以越来越好。','Hui bian, dan ke yi yue lai yue hao.','Se thay doi, nhung co the tot hon.',2);
ds($conn,$d1_3,'Lan','我父母结婚二十年了，感情一直很好。','Wo fu mu jie hun er shi nian le, gan qing yi zhi hen hao.','Bo me cuoi 20 nam, tinh cam luon tot.',3);
ds($conn,$d1_3,'Minh','真让人感动。','Zhen rang ren gan dong.','That cam dong.',4);
ds($conn,$d1_3,'Lan','所以我相信婚姻可以很幸福。','Suo yi wo xiang xin hun yin ke yi hen xing fu.','Toi tin hon nhan co the hanh phuc.',5);
r($conn,$L1,'Tinh yeu gian di','很多人都认为爱情应该是浪漫的、复杂的。但是对我来说，真正的爱情其实很简单。幸福不是每天都送鲜花，而是每天早上的一句关心。真正的感情不需要永远说"我爱你"，而是生活中的相互理解和体贴。我父母结婚二十多年了，他们的感情从来没有变淡，反而越来越好。从他们身上我明白了一个道理：简单的爱情才是最幸福的。','Hen duo ren dou ren wei ai qing ying gai shi lang man de、fu za de. Dan shi dui wo lai shuo, zhen zheng de ai qing qi shi hen jian dan. Xing fu bu shi mei tian dou song xian hua, er shi mei tian zao shang de yi ju guan xin. Zhen zheng de gan qing bu xu yao yong yuan shuo "wo ai ni", er shi sheng huo zhong de xiang hu li jie he ti tie. Wo fu mu jie hun er shi duo nian le, ta men de gan qing cong lai mei you bian dan, fan er yue lai yue hao. Cong ta men shen shang wo ming bai le yi ge dao li: jian dan de ai qing cai shi zui xing fu de.','Nhieu nguoi cho rang tinh yeu phai lang man. Nhung voi toi, tinh yeu dich thuc don gian. Hanh phuc la moi sang quan tam nhau. Tinh cam khong can mai noi yeu, ma la su thau hieu. Bo me toi cuoi 20 nam, tinh cam chua nhat, nguoc lai tot hon. Toi hieu ra tinh yeu gian di moi hanh phuc.','medium',195,1);
$L1l=l($conn,$L1,'Cau chuyen tinh yeu','Nu: Ban co tin tinh yeu set danh khong? Nam: Toi chua bao gio tin. Tinh cam can tu tu hieu nhau. Nu: An tuong dau quan trong. Nam: Quan trong la cam giac khi o canh nhau. Nu: Ban noi dung. Toi va ban trai quen 3 nam moi ben nhau.','Nu: Ni xiang xin yi jian zhong qing ma? Nan: Wo cong lai bu xiang xin. Gan qing xu yao man man liao jie. Nu: Di yi yin xiang hen zhong yao. Nan: Zhong yao de bu shi di yi yin xiang, er shi xiang chu yi hou de gan jue. Nu: Ni shuo de you dao li. Wo he nan peng you ren shi le san nian cai zai yi qi.','Nu: Ban co tin tinh yeu set danh? Nam: Toi chua bao gio tin. Tinh cam can tu tu hieu nhau. Nu: An tuong dau quan trong. Nam: Quan trong la cam giac o canh nhau. Nu: Ban noi dung. Toi va ban trai quen 3 nam moi ben nhau.','1');
lq($conn,$L1l,'Nguoi nam co tin tinh yeu set danh?','{"A":"Co","B":"Khong","C":"Cung tin mot phan"}','Khong','Anh ay noi chua bao gio tin.','multiple_choice',1);
lq($conn,$L1l,'Dieu gi quan trong hon an tuong dau?','{"A":"Ngoai hinh","B":"Cam giac o canh nhau","C":"Tien bac"}','Cam giac o canh nhau','Cam giac khi o canh nhau.','multiple_choice',2);
lq($conn,$L1l,'Nguoi nu quen ban trai bao lau moi ben nhau?','{"A":"1 nam","B":"2 nam","C":"3 nam"}','3 nam','Quen ba nam.','multiple_choice',3);
$E1_1=e($conn,$L1,'Chon dap an','"从来" dung trong cau nao?','multiple_choice','medium',1,'B',1);
eo($conn,$E1_1,'Cau khang dinh','A',0,1); eo($conn,$E1_1,'Cau phu dinh','B',1,2); eo($conn,$E1_1,'Cau nghi van','C',0,3);
$E1_2=e($conn,$L1,'Dich','"Voi toi, hanh phuc rat don gian."','translation','medium',1,'对我来说，幸福很简单。',2);
$E1_3=e($conn,$L1,'Dien tu','他们的感情越___越好。','fill_blank','medium',1,'来越',3);
$E1_4=e($conn,$L1,'Sap xep','我 / 从来 / 爱情 / 不 / 相信 / 浪漫 / 的','sentence_order','medium',1,'我从来不相信浪漫的爱情。',4);
$E1_5=e($conn,$L1,'Dung sai','"幸福" la "hanh phuc".','true_false','easy',1,'true',5);
eo($conn,$E1_5,'Dung','A',1,1); eo($conn,$E1_5,'Sai','B',0,2);
$E1_6=e($conn,$L1,'Chon tu','他从来没有说___爱我。','multiple_choice','medium',1,'B',6);
eo($conn,$E1_6,'了','A',0,1); eo($conn,$E1_6,'过','B',1,2); eo($conn,$E1_6,'着','C',0,3);
$E1_7=e($conn,$L1,'Dien tu','___我来说，家庭最重要。','fill_blank','medium',1,'对',7);
$E1_8=e($conn,$L1,'Chon dap an','"对...来说" dung de gi?','multiple_choice','medium',1,'A',8);
eo($conn,$E1_8,'Dua ra quan diem','A',1,1); eo($conn,$E1_8,'Hoi dia diem','B',0,2); eo($conn,$E1_8,'Mieu ta hanh dong','C',0,3);
$E1_9=e($conn,$L1,'Dien tu','真正的幸福不是___爱而是责任。','multiple_choice','medium',1,'A',9);
eo($conn,$E1_9,'浪漫','A',1,1); eo($conn,$E1_9,'简单','B',0,2); eo($conn,$E1_9,'痛苦','C',0,3);
foreach ([$v1_1,$v1_2,$v1_3,$v1_4,$v1_5,$v1_6,$v1_7,$v1_8,$v1_9,$v1_10,$v1_11,$v1_12] as $i=>$vid) if ($vid) rv($conn,$L1,$vid,'core',$i+1);
echo " HSK4 L1 done: $v1 vocab, 4 grammar, 3 dialogues, 1 reading, 1 listening, 9 exercises\n";

$L2=createLesson($conn,4,2,'Bai 2: Zhen zheng de peng you','Nguoi ban that su. Long tin. Cau truc "wu lun...dou..." (du the nao...cung...).','["Tinh ban","Long tin","Ca tinh"]','Tinh ban','medium','HSK4 Bai 2: Tu vung tinh ban. 无论...都... (du the nao...cung...). 既...又... (vua...vua...). 只要...就... (chi can...la...). 为了 (de).');
$v2=0;
$v2_1=v($conn,$L2,4,'真正','zhen zheng','that su','that su','他是真正的朋友。','Ta shi zhen zheng de peng you.','Anh ay la ban that su.','adj','That su.',++$v2);
$v2_2=v($conn,$L2,4,'信任','xin ren','tin tuong','tin tuong','朋友之间需要信任。','Peng you zhi jian xu yao xin ren.','Ban be can tin tuong nhau.','verb/noun','Tin tuong lan nhau.',++$v2);
$v2_3=v($conn,$L2,4,'性格','xing ge','tinh cach','tinh cach','她性格很开朗。','Ta xing ge hen kai lang.','Co ay tinh cach hoa dong.','noun','Tinh cach.',++$v2);
$v2_4=v($conn,$L2,4,'无论','wu lun','du the nao','du','无论多难，我都坚持。','Wu lun duo nan, wo dou jian chi.','Du kho toi cung kien tri.','conj','Thuong dung voi 都.',++$v2);
$v2_5=v($conn,$L2,4,'友谊','you yi','tinh ban','tinh ban','友谊很珍贵。','You yi hen zhen gui.','Tinh ban quy gia.','noun','Tinh ban.',++$v2);
$v2_6=v($conn,$L2,4,'帮助','bang zhu','giup do','giup','他帮助了我很多。','Ta bang zhu le wo hen duo.','Anh ay giup toi nhieu.','verb','Giup do.',++$v2);
$v2_7=v($conn,$L2,4,'理解','li jie','thau hieu','hieu','我理解你的心情。','Wo li jie ni de xin qing.','Toi hieu tam trang ban.','verb','Thau hieu.',++$v2);
$v2_8=v($conn,$L2,4,'支持','zhi chi','ung ho','ung ho','他支持我的决定。','Ta zhi chi wo de jue ding.','Anh ay ung ho toi.','verb','Ung ho.',++$v2);
$v2_9=v($conn,$L2,4,'共同','gong tong','chung','chung','我们有共同的爱好。','Wo men you gong tong de ai hao.','Chung toi co so thich chung.','adj','Cung nhau.',++$v2);
$v2_10=v($conn,$L2,4,'分享','fen xiang','chia se','chia se','和朋友分享快乐。','He peng you fen xiang kuai le.','Cung ban chia se niem vui.','verb','Chia se.',++$v2);
$v2_11=v($conn,$L2,4,'诚实','cheng shi','thanh that','that tha','诚实很重要。','Cheng shi hen zhong yao.','Thanh that rat quan trong.','adj','Trung thuc.',++$v2);
$g2_1=g($conn,$L2,'Cau truc 无论...都...','无论 + (ai/gi) + 都 + Dong tu','Du the nao...cung...','无论 (wu lun) mang y "du the nao", ket hop 都 (dou) de nhan manh.','无论多难都不放弃 = Du kho may cung ko bo.','Dieu kien bat bien.',1);
ge($conn,$g2_1,'无论多忙，我都会联系你。','Wu lun duo mang, wo dou hui lian xi ni.','Du ban may, toi cung lien lac.',1);
ge($conn,$g2_1,'无论发生什么事，我们都在一起。','Wu lun fa sheng shen me shi, wo men dou zai yi qi.','Du gi xay ra, ta cung ben nhau.',2);
$g2_2=g($conn,$L2,'Cau truc 既...又...','既 + A + 又 + B','Vua...vua...',' 既...又... dien ta vat co ca hai thuoc tinh.','他既聪明又努力 = Anh ay vua thong minh vua cham.','Song song.',2);
ge($conn,$g2_2,'他既聪明又努力。','Ta ji cong ming you nu li.','Anh ay vua thong minh vua cham chi.',1);
ge($conn,$g2_2,'真正的朋友既会分享快乐，又会分担痛苦。','Zhen zheng de peng you ji hui fen xiang kuai le, you hui fen dan tong ku.','Ban that su biet chia se ca vui lan buon.',2);
$g2_3=g($conn,$L2,'Cau truc 只要...就...','只要 + Dieu kien + 就 + Ket qua','Chi can...la...','只要 (zhi yao) dieu kien toi thieu, 就 (jiu) dan ket qua.','只要努力就能成功 = Chi can co gang se thanh cong.','Toi thieu.',3);
ge($conn,$g2_3,'只要有信任，友谊就会长久。','Zhi yao you xin ren, you yi jiu hui chang jiu.','Chi can tin tuong, tinh ban se lau ben.',1);
ge($conn,$g2_3,'只要你需要，我就来帮你。','Zhi yao ni xu yao, wo jiu lai bang ni.','Chi can ban can, toi se giup.',2);
$g2_4=g($conn,$L2,'Cau truc 为了','为了 + Muc dich','De / vi','为了 (wei le) dat o dau cau de chi muc dich. Phan biet 因为 (nguyen nhan) va 为了 (muc dich).','为了学好汉语，我每天练习 = De hoc tot tieng Trung.','Muc dich.',4);
ge($conn,$g2_4,'为了朋友，我愿意做任何事。','Wei le peng you, wo yuan yi zuo ren he shi.','Vi ban, toi lam bat cu dieu gi.',1);
ge($conn,$g2_4,'为了健康，他开始运动了。','Wei le jian kang, ta kai shi yun dong le.','Vi suc khoe, anh ay bat dau tap.',2);
$d2_1=d($conn,$L2,'Ban that su','The nao la ban that su.',1);
ds($conn,$d2_1,'Lan','你觉得什么样的朋友才是真正的朋友？','Ni jue de shen me yang de peng you cai shi zhen zheng de peng you?','Ban the nao moi la ban that su?',1);
ds($conn,$d2_1,'Minh','对我来说，真正的朋友既会支持我，也能理解我。','Dui wo lai shuo, zhen zheng de peng you ji hui zhi chi wo, ye neng li jie wo.','Ban that su vua ung ho vua thau hieu toi.',2);
ds($conn,$d2_1,'Lan','你说得对。无论发生什么事，真正的朋友都会在你身边。','Ni shuo de dui. Wu lun fa sheng shen me shi, zhen zheng de peng you dou hui zai ni shen bian.','Ban noi dung. Du gi xay ra, ban that su ben ban.',3);
ds($conn,$d2_1,'Minh','而且朋友之间最重要的是信任和诚实。','Er qie peng you zhi jian zui zhong yao de shi xin ren he cheng shi.','Ban be can nhat la tin tuong va that tha.',4);
$d2_2=d($conn,$L2,'Giup do ban be','Giup do ban.',2);
ds($conn,$d2_2,'Lan','我最近心情不好，工作压力很大。','Wo zui jin xin qing bu hao, gong zuo ya li hen da.','Toi buon, ap luc viec lon.',1);
ds($conn,$d2_2,'Minh','别担心，有我在呢。无论你需要什么帮助，我都支持你。','Bie dan xin, you wo zai ne. Wu lun ni xu yao shen me bang zhu, wo dou zhi chi ni.','Dung lo, co toi. Du ban can gi, toi ung ho.',2);
ds($conn,$d2_2,'Lan','谢谢你一直这么理解我。','Xie xie ni yi zhi zhe me li jie wo.','Cam on ban luon hieu toi.',3);
ds($conn,$d2_2,'Minh','只要你能开心起来，我就放心了。','Zhi yao ni neng kai xin qi lai, wo jiu fang xin le.','Chi can ban vui, toi yen tam.',4);
$d2_3=d($conn,$L2,'So thich chung','Chia se so thich.',3);
ds($conn,$d2_3,'Lan','你有什么爱好？','Ni you shen me ai hao?','Ban thich gi?',1);
ds($conn,$d2_3,'Minh','我喜欢读书和旅行。我们有很多共同的爱好。','Wo xi huan du shu he lv xing. Wo men you hen duo gong tong de ai hao.','Toi thich doc va du lich. Chung ta co nhieu so thich chung.',2);
ds($conn,$d2_3,'Lan','太好了！以后我们可以一起分享读书的心得。','Tai hao le! Yi hou wo men ke yi yi qi fen xiang du shu de xin de.','Tuyet! Sau nay cung chia se cam nhan doc sach.',3);
ds($conn,$d2_3,'Minh','当然，友谊就是从分享开始的。','Dang ran, you yi jiu shi cong fen xiang kai shi de.','Tinh ban tu chia se ma ra.',4);
r($conn,$L2,'Tinh ban that su','我有一个认识十年的好朋友，叫小华。无论我开心还是难过，他总是陪在我身边。他性格很开朗，既幽默又善良。记得有一次我遇到了很大的困难，他不仅帮助我，还一直鼓励我。他对我说："只要你不放弃，我就一直支持你。" 那时候我很感动，明白了真正的友谊是什么。真正的朋友不需要天天见面，但无论距离多远，心里都会想着对方。信任和理解，是友谊的基础。','Wo you yi ge ren shi shi nian de hao peng you, jiao Xiao Hua. Wu lun wo kai xin hai shi nan guo, ta zong shi pei zai wo shen bian. Ta xing ge hen kai lang, ji you mo you shan liang. Ji de you yi ci wo yu dao le hen da de kun nan, ta bu jin bang zhu wo, hai yi zhi gu li wo. Ta dui wo shuo: "Zhi yao ni bu fang qi, wo jiu yi zhi zhi chi ni." Na shi hou wo hen gan dong, ming bai le zhen zheng de you yi shi shen me. Zhen zheng de peng you bu xu yao tian tian jian mian, dan wu lun ju li duo yuan, xin li dou hui xiang zhe dui fang. Xin ren he li jie, shi you yi de ji chu.','Toi co ban quen muoi ten Tieu Hoa. Du vui buon anh ay luon ben toi. Anh ay hoa dong, vua hoi huoc vua tot. Nho lan toi gap kho khan, anh ay giup va khuyen khich toi. Anh noi "chi can ban ko bo cuoc, toi ung ho ban". Toi cam dong. Ban that su ko can gap hang ngay, nhung du xa cach, trong long deu nho nhau. Tin tuong va thau hieu la nen tang tinh ban.','medium',200,1);
$L2l=l($conn,$L2,'Tinh ban','A: Ban co tam su? B: Toi va ban than cai nhau. A: Sao vay? B: Chuyen nho. Nhung gio toi hoi han. A: Ban that su se hieu. Chi can xin loi, anh ay se tha thu. B: Toi rat quy tinh ban nay.','A: Ni hao xiang you xin shi. B: Wo he hao peng you chao jia le. A: Zen me le? B: Yi jian xiao shi. Dan xian zai wo hen hou hui. A: Wo jue de zhen zheng de peng you hui liang jie ni. Zhi yao ni dao qian, ta hui yuan liang ni de. B: Wo hen zhen xi zhe fen you yi.','A: Ban co tam su? B: Toi va ban than cai nhau. A: Sao vay? B: Chuyen nho. Nhung gio toi hoi han. A: Ban that su se hieu. Chi can xin loi, anh ay se tha thu. B: Toi rat quy tinh ban nay.','1');
lq($conn,$L2l,'Sao nguoi B buon?','{"A":"Mat viec","B":"Cai voi ban","C":"Om"}','Cai voi ban','Cai nhau voi ban than.','multiple_choice',1);
lq($conn,$L2l,'Nguoi A khuyen B gi?','{"A":"Quen ban","B":"Xin loi","C":"Khong lam gi"}','Xin loi','Chi can xin loi.','multiple_choice',2);
lq($conn,$L2l,'Nguoi B nghi gi ve tinh ban?','{"A":"Khong quan tam","B":"Rat quy","C":"Muon ket thuc"}','Rat quy','Toi rat quy tinh ban nay.','multiple_choice',3);
$E2_1=e($conn,$L2,'Chon dap an','"无论...都..." la gi?','multiple_choice','medium',1,'C',1);
eo($conn,$E2_1,'Vi...nen...','A',0,1); eo($conn,$E2_1,'Neu...thi...','B',0,2); eo($conn,$E2_1,'Du...cung...','C',1,3);
$E2_2=e($conn,$L2,'Dich','"Chi can ban can, toi se giup."','translation','medium',1,'只要你需要，我就帮你。',2);
$E2_3=e($conn,$L2,'Dien tu','他既聪明___努力。','fill_blank','medium',1,'又',3);
$E2_4=e($conn,$L2,'Sap xep','无论 / 我 / 都 / 多忙 / 你 / 联系','sentence_order','medium',1,'无论多忙，我都会联系你。',4);
$E2_5=e($conn,$L2,'Dung sai','"为了" chi nguyen nhan.','true_false','medium',1,'false',5);
eo($conn,$E2_5,'Dung','A',0,1); eo($conn,$E2_5,'Sai','B',1,2);
$E2_6=e($conn,$L2,'Dien tu','___健康，他每天跑步。','fill_blank','medium',1,'为了',6);
$E2_7=e($conn,$L2,'Chon dap an','"既...又..." dung de?','multiple_choice','medium',1,'C',7);
eo($conn,$E2_7,'So sanh','A',0,1); eo($conn,$E2_7,'Lua chon','B',0,2); eo($conn,$E2_7,'Song song hai thuoc tinh','C',1,3);
$E2_8=e($conn,$L2,'Dien tu','真正的朋友会___你的快乐。','fill_blank','medium',1,'分享',8);
$E2_9=e($conn,$L2,'Chon tu','___多难，我都会坚持。','multiple_choice','medium',1,'A',9);
eo($conn,$E2_9,'无论','A',1,1); eo($conn,$E2_9,'虽然','B',0,2); eo($conn,$E2_9,'因为','C',0,3);
foreach ([$v2_1,$v2_2,$v2_3,$v2_4,$v2_5,$v2_6,$v2_7,$v2_8,$v2_9,$v2_10,$v2_11] as $i=>$vid) if ($vid) rv($conn,$L2,$vid,'core',$i+1);
echo " HSK4 L2 done: $v2 vocab, 4 grammar, 3 dialogues, 1 reading, 1 listening, 9 exercises\n";

$L3=createLesson($conn,4,3,'Bai 3: Ren sheng mei you cai pai','Doi khong co tap tran. "ru guo...jiu..." (neu...thi...). "ji shi...ye..." (thu the...cung...).','["Cuoc song","Lua chon","Co hoi"]','Cuoc song','medium','HSK4 Bai 3: 如果...就... (neu...thi...). 即使...也... (thu the...cung...). 只有...才... (chi...moi...). 不但...反而... (khong nhung...nguoc lai...).');
$v3=0;
$v3_1=v($conn,$L3,4,'人生','ren sheng','cuoc doi','doi','人生很短，要珍惜。','Ren sheng hen duan, yao zhen xi.','Doi ngan, hay tran trong.','noun','Cuoc song.',++$v3);
$v3_2=v($conn,$L3,4,'如果','ru guo','neu','neu','如果你来，我会很高兴。','Ru guo ni lai, wo hui hen gao xing.','Neu ban den, toi se vui.','conj','Gia dinh dieu kien.',++$v3);
$v3_3=v($conn,$L3,4,'即使','ji shi','thu the','thu the','即使下雨，我也要去。','Ji shi xia yu, wo ye yao qu.','Thu the mua, toi cung di.','conj','Gia du.',++$v3);
$v3_4=v($conn,$L3,4,'机会','ji hui','co hoi','co hoi','这是一个好机会。','Zhe shi yi ge hao ji hui.','Co hoi tot.','noun','Thoi co.',++$v3);
$v3_5=v($conn,$L3,4,'选择','xuan ze','lua chon','chon','你要做出选择。','Ni yao zuo chu xuan ze.','Ban phai chon.','verb/noun','Lua chon.',++$v3);
$v3_6=v($conn,$L3,4,'后悔','hou hui','hoi han','hoi','做了就不要后悔。','Zuo le jiu bu yao hou hui.','Lam roi dung hoi.','verb','An han.',++$v3);
$v3_7=v($conn,$L3,4,'努力','nu li','co gang','co gang','努力才有收获。','Nu li cai you shou huo.','Co gang moi co thu hoach.','verb/adv','No luc.',++$v3);
$v3_8=v($conn,$L3,4,'失败','shi bai','that bai','that bai','失败是成功之母。','Shi bai shi cheng gong zhi mu.','That bai la me cua thanh cong.','verb/noun','That bai.',++$v3);
$v3_9=v($conn,$L3,4,'经验','jing yan','kinh nghiem','kinh nghiem','他有丰富的经验。','Ta you feng fu de jing yan.','Anh ay co nhieu kinh nghiem.','noun','Trai nghiem.',++$v3);
$v3_10=v($conn,$L3,4,'珍惜','zhen xi','tran trong','tran trong','珍惜时间。','Zhen xi shi jian.','Tran trong thoi gian.','verb','Tran trong.',++$v3);
$v3_11=v($conn,$L3,4,'继续','ji xu','tiep tuc','tiep tuc','继续努力。','Ji xu nu li.','Tiep tuc co gang.','verb','Tiep tuc.',++$v3);
$g3_1=g($conn,$L3,'Cau truc 如果...就...','如果 + DK + 就 + KQ','Neu...thi...',' 如果 neu len dieu kien, 就 dan ket qua.','如果下雨，我就不去了 = Neu mua toi ko di.','Dieu kien.',1);
ge($conn,$g3_1,'如果人生有选择，你会怎么做？','Ru guo ren sheng you xuan ze, ni hui zen me zuo?','Neu doi co lua chon, ban lam the nao?',1);
ge($conn,$g3_1,'如果失败了，不要放弃，继续努力。','Ru guo shi bai le, bu yao fang qi, ji xu nu li.','Neu that bai, dung bo cuoc, tiep tuc co gang.',2);
$g3_2=g($conn,$L3,'Cau truc 即使...也...','即使 + NB + 也 + KQ','Thu the...cung...',' 即使 la gia su nhuong bo, khac voi 虽然 (mac du thuc te).','即使失败，也不后悔 = Thu the that bai cung ko hoi.','Gia su.',2);
ge($conn,$g3_2,'即使遇到困难，也不要放弃梦想。','Ji shi yu dao kun nan, ye bu yao fang qi meng xiang.','Thu the gap kho, dung bo uoc mo.',1);
ge($conn,$g3_2,'即使没有人理解，我也要坚持。','Ji shi mei you ren li jie, wo ye yao jian chi.','Thu the ko ai hieu, toi cung kien tri.',2);
$g3_3=g($conn,$L3,'Cau truc 只有...才...','只有 + DK + 才 + KQ','Chi...moi...',' 只有 dieu kien bat buoc.','只有努力才能成功 = Chi co gang moi thanh cong.','Bat buoc.',3);
ge($conn,$g3_3,'只有珍惜现在，才不会后悔未来。','Zhi you zhen xi xian zai, cai bu hui hou hui wei lai.','Chi tran trong hien tai moi ko hoi han.',1);
ge($conn,$g3_3,'只有经历过失败，才能获得真正的经验。','Zhi you jing li guo shi bai, cai neng huo de zhen zheng de jing yan.','Chi trai that bai moi co kinh nghiem.',2);
$g3_4=g($conn,$L3,'Cau truc 不但...反而...','不但 + Khong A + 反而 + B','Ko nhung ko...nguoc lai con...',' Ket qua trai nguoc mong doi.','不但不生气，反而笑了 = Ko nhung ko gian, nguoc lai cuoi.','Nguoc lai.',4);
ge($conn,$g3_4,'他不但没有放弃，反而更加努力了。','Ta bu dan mei you fang qi, fan er geng jia nu li le.','Anh ay ko nhung ko bo, nguoc lai co gap hon.',1);
ge($conn,$g3_4,'失败不但没有让他后悔，反而让他学到了很多。','Shi bai bu dan mei you rang ta hou hui, fan er rang ta xue dao le hen duo.','That bai ko hoi han ma nguoc lai hoc duoc nhieu.',2);
$d3_1=d($conn,$L3,'Cuoc song ko tap tran','Ban ve lua chon.',1);
ds($conn,$d3_1,'Lan','如果人生可以重来，你会选择不一样的路吗？','Ru guo ren sheng ke yi chong lai, ni hui xuan ze bu yi yang de lu ma?','Neu doi lam lai, ban chon duong khac?',1);
ds($conn,$d3_1,'Minh','人生没有彩排，每天都是现场直播。我从不后悔自己的选择。','Ren sheng mei you cai pai, mei tian dou shi xian chang zhi bo. Wo cong lai bu hou hui zi ji de xuan ze.','Doi ko tap tran, moi ngay truc tiep. Toi ko hoi han lua chon.',2);
ds($conn,$d3_1,'Lan','说得好。即使走错了路，也是一种经验。','Shuo de hao. Ji shi zou cuo le lu, ye shi yi zhong jing yan.','Noi hay. Thu the di nham cung la kinh nghiem.',3);
ds($conn,$d3_1,'Minh','对，只有经历过，才知道什么最重要。','Dui, zhi you jing li guo, cai zhi dao shen me zui zhong yao.','Chi trai qua roi moi biet gi quan trong.',4);
$d3_2=d($conn,$L3,'That bai va bai hoc','Noi ve that bai.',2);
ds($conn,$d3_2,'Lan','上次考试我失败了，心里很难过。','Shang ci kao shi wo shi bai le, xin li hen nan guo.','Thi truoc toi that bai, buon lam.',1);
ds($conn,$d3_2,'Minh','如果因为一次失败就放弃，那才可惜呢。','Ru guo yin wei yi ci shi bai jiu fang qi, na cai ke xi ne.','Neu vi that bai ma bo cuoc moi dang tiec.',2);
ds($conn,$d3_2,'Lan','你说得对。我不会放弃，我要继续努力。','Ni shuo de dui. Wo bu hui fang qi, wo yao ji xu nu li.','Ban dung. Toi ko bo cuoc, toi co gang tiep.',3);
ds($conn,$d3_2,'Minh','这次失败不但没有打败你，反而让你更坚强了。','Zhe ci shi bai bu dan mei you da bai ni, fan er rang ni geng jian qiang le.','That bai nay ko danh bai ban, nguoc lai ban manh me hon.',4);
$d3_3=d($conn,$L3,'Co hoi va quyet dinh','Nam bat co hoi.',3);
ds($conn,$d3_3,'Lan','有一个去中国留学的机会，我很想去。','You yi ge qu Zhong guo liu xue de ji hui, wo hen xiang qu.','Co co hoi di du hoc TQ, toi muon di.',1);
ds($conn,$d3_3,'Minh','这是好机会啊！如果想去，就不要犹豫。','Zhe shi hao ji hui a! Ru guo xiang qu, jiu bu yao you yu.','Co hoi tot! Neu muon di, dung do du.',2);
ds($conn,$d3_3,'Lan','但是我担心自己能力不够。','Dan shi wo dan xin zi ji neng li bu gou.','Nhung toi lo nang luc ko du.',3);
ds($conn,$d3_3,'Minh','即使现在不够好，去了以后会越来越好的。','Ji shi xian zai bu gou hao, qu le yi hou hui yue lai yue hao de.','Thu the chua tot, di roi se tot hon.',4);
ds($conn,$d3_3,'Lan','你说得对。那我就试试看。','Ni shuo de dui. Na wo jiu shi shi kan.','Ban dung. Toi se thu.',5);
r($conn,$L3,'Doi ko tap tran','人生没有彩排，每一天都是现场直播。我们每个人都会面临很多选择，也会经历很多失败。但是，如果因为害怕失败就不敢选择，那就会失去很多机会。我记得三年前，我有一个去北京工作的机会。那时我很犹豫，担心自己能力不够。但是朋友对我说："如果不去试试，你永远不知道自己能做到什么。" 于是我决定去了。虽然遇到了很多困难，但是我学到了很多经验，也变得更加独立。现在回想起来，我很感谢自己当初的选择。即使再难，也值得。','Ren sheng mei you cai pai, mei yi tian dou shi xian chang zhi bo. Wo men mei ge ren dou hui mian lin hen duo xuan ze, ye hui jing li hen duo shi bai. Dan shi, ru guo yin wei hai pa shi bai jiu bu gan xuan ze, na jiu hui shi qu hen duo ji hui. Wo ji de san nian qian, wo you yi ge qu Bei Jing gong zuo de ji hui. Na shi wo hen you yu, dan xin zi ji neng li bu gou. Dan shi peng you dui wo shuo: "Ru guo bu qu shi shi, ni yong yuan bu zhi dao zi ji neng zuo dao shen me." Yu shi wo jue ding qu le. Sui ran yu dao le hen duo kun nan, dan shi wo xue dao le hen duo jing yan, ye bian de geng jia du li. Xian zai hui xiang qi lai, wo hen gan xie zi ji dang chu de xuan ze. Ji shi zai nan, ye zhi de.','Doi ko tap tran. Moi nguoi deu doi mat lua chon va that bai. Neu so that bai ma ko dam chon, se mat co hoi. Ba nam truoc toi co co hoi di Bac Kinh lam viec. Toi do du, lo minh ko du nang luc. Nhung ban noi "Neu ko thu, ban ko biet minh lam duoc gi." Toi quyet di. Mac du gap kho, toi hoc duoc nhieu, tro nen doc lap. Toi cam on lua chon ngay ay. Du kho, cung dang.','medium',210,1);
$L3l=l($conn,$L3,'Lua chon','Nam: Toi phan van co nen doi viec? Viec hien tai on dinh nhung toi muon thu thach. Nu: Neu ko con phat trien, nen doi. Co hoi moi cho nhieu kinh nghiem. Nam: Nhung toi so that bai. Nu: That bai la bai hoc. Chi trai qua moi biet minh lam duoc gi.','Nan: Wo zheng zai fan yu yao bu yao huan gong zuo? Xian zai de gong zuo wen ding dan wo xiang tiao zhan zi ji. Nu: Ru guo ni gan jue bu neng zai fa zhan le, na jiu ying gai huan. Xin ji hui gei ni hen duo jing yan. Nan: Ke shi wo pa shi bai. Nu: Shi bai ye shi yi ke ke. Zhi you jing li guo, ni cai zhi dao neng zuo shen me.','Nam: Toi phan van co nen doi viec? Viec hien tai on dinh nhung toi muon thu thach. Nu: Neu ko con phat trien, nen doi. Co hoi moi cho nhieu kinh nghiem. Nam: Nhung toi so that bai. Nu: That bai la bai hoc. Chi trai qua moi biet minh lam duoc gi.','1');
lq($conn,$L3l,'Nam phan van gi?','{"A":"Doi viec","B":"Nghi hoc","C":"Chuyen nha"}','Doi viec','Phan van co nen doi viec.','multiple_choice',1);
lq($conn,$L3l,'Nu khuyen anh gi?','{"A":"O lai","B":"Tim co hoi moi","C":"Nghi ngoi"}','Tim co hoi moi','Nen tim co hoi moi.','multiple_choice',2);
lq($conn,$L3l,'Tai sao anh so?','{"A":"Luong thap","B":"So that bai","C":"Xa nha"}','So that bai','Anh ay so that bai.','multiple_choice',3);
$E3_1=e($conn,$L3,'Chon dap an','"如果...就..." la?','multiple_choice','medium',1,'A',1);
eo($conn,$E3_1,'DK - KQ','A',1,1); eo($conn,$E3_1,'Nhuong bo','B',0,2); eo($conn,$E3_1,'Tuong phan','C',0,3);
$E3_2=e($conn,$L3,'Dich','"Thu the that bai, dung bo cuoc."','translation','medium',1,'即使失败，也不要放弃。',2);
$E3_3=e($conn,$L3,'Dien tu','___你努力，就___成功。','fill_blank','medium',1,'如果...就...',3);
$E3_4=e($conn,$L3,'Sap xep','没有 / 人生 / 彩排 / 每天 / 是 / 直播','sentence_order','medium',1,'人生没有彩排，每天都是现场直播。',4);
$E3_5=e($conn,$L3,'Dung sai','"只有...才..." la dieu kien bat buoc.','true_false','medium',1,'true',5);
eo($conn,$E3_5,'Dung','A',1,1); eo($conn,$E3_5,'Sai','B',0,2);
$E3_6=e($conn,$L3,'Dien tu','___ ko ai hieu, toi cung kien tri.','fill_blank','medium',1,'即使',6);
$E3_7=e($conn,$L3,'Phan biet','"即使" vs "虽然"?','multiple_choice','medium',1,'B',7);
eo($conn,$E3_7,'Giong nhau','A',0,1); eo($conn,$E3_7,'即使 la gia su, 虽然 la thuc te','B',1,2); eo($conn,$E3_7,'即使 la qua khu','C',0,3);
$E3_8=e($conn,$L3,'Dien tu','That bai ko danh bai ban, ___ lam ban manh hon.','fill_blank','medium',1,'反而',8);
$E3_9=e($conn,$L3,'Chon tu','___ that bai, ___ biet cam giac.','multiple_choice','medium',1,'B',9);
eo($conn,$E3_9,'Chi can...moi...','A',0,1); eo($conn,$E3_9,'Chi co...moi...','B',1,2); eo($conn,$E3_9,'Chi...cung...','C',0,3);
foreach ([$v3_1,$v3_2,$v3_3,$v3_4,$v3_5,$v3_6,$v3_7,$v3_8,$v3_9,$v3_10,$v3_11] as $i=>$vid) if ($vid) rv($conn,$L3,$vid,'core',$i+1);
echo " HSK4 L3 done: $v3 vocab, 4 grammar, 3 dialogues, 1 reading, 1 listening, 9 exercises\n";

$L4=createLesson($conn,4,4,'Bai 4: Du shu shi yi zhong sheng huo','Doc sach la mot cach song. "bu jin...er qie..." (ko nhung...ma con...). "cong...zhong..." (tu...trong...).','["Doc sach","Tri thuc","Thoi quen"]','Doc sach','medium','HSK4 Bai 4: 不仅...而且... (ko nhung...ma con...). 从...中... (tu...trong...). 连...都/也... (ngay ca...cung...). 对...感兴趣 (ham thich).');
$v4=0;
$v4_1=v($conn,$L4,4,'读书','du shu','doc sach','doc','我喜欢读书。','Wo xi huan du shu.','Toi thich doc sach.','verb','Doc sach.',++$v4);
$v4_2=v($conn,$L4,4,'知识','zhi shi','tri thuc','tri thuc','知识就是力量。','Zhi shi jiu shi li liang.','Tri thuc la suc manh.','noun','Kien thuc.',++$v4);
$v4_3=v($conn,$L4,4,'不仅','bu jin','ko nhung','ko nhung','他不仅聪明，而且努力。','Ta bu jin cong ming, er qie nu li.','Anh ay ko nhung thong minh ma con cham.','conj','Thuong dung voi 而且.',++$v4);
$v4_4=v($conn,$L4,4,'而且','er qie','ma con','ma con','这件衣服便宜而且好看。','Zhe jian yi fu pian yi er qie hao kan.','Ao nay re ma con dep.','conj','Noi tiep.',++$v4);
$v4_5=v($conn,$L4,4,'兴趣','xing qu','so thich','thich','我对汉语很感兴趣。','Wo dui Han yu hen gan xing qu.','Toi thich tieng Trung.','noun','Ham thich.',++$v4);
$v4_6=v($conn,$L4,4,'习惯','xi guan','thoi quen','thoi quen','每天读书是好习惯。','Mei tian du shu shi hao xi guan.','Doc sach moi ngay la thoi quen tot.','noun','Thoi quen.',++$v4);
$v4_7=v($conn,$L4,4,'提高','ti gao','nang cao','nang cao','提高汉语水平。','Ti gao Han yu shui ping.','Nang cao trinh do.','verb','Cai thien.',++$v4);
$v4_8=v($conn,$L4,4,'内容','nei rong','noi dung','noi dung','这本书内容很丰富。','Zhe ben shu nei rong hen feng fu.','Sach nay noi dung phong phu.','noun','Noi dung.',++$v4);
$v4_9=v($conn,$L4,4,'作者','zuo zhe','tac gia','tac gia','作者是谁？','Zuo zhe shi shei?','Tac gia la ai?','noun','Nguoi viet.',++$v4);
$v4_10=v($conn,$L4,4,'思考','si kao','suy nghi','suy nghi','读书要思考。','Du shu yao si kao.','Doc can suy nghi.','verb','Tu duy.',++$v4);
$v4_11=v($conn,$L4,4,'丰富','feng fu','phong phu','phong phu','生活很丰富。','Sheng huo hen feng fu.','Cuoc song phong phu.','adj/verb','Nhieu.',++$v4);
$g4_1=g($conn,$L4,'Cau truc 不仅...而且...','不仅 + A + 而且 + B','Ko nhung...ma con...','Noi ket hai ve, ve sau bo sung tang tien.','他不仅会说汉语，而且会写汉字.',1);
ge($conn,$g4_1,'读书不仅可以增长知识，而且可以丰富生活。','Du shu bu jin ke yi zeng zhang zhi shi, er qie ke yi feng fu sheng huo.','Doc sach ko nhung tang tri thuc ma con phong phu cuoc song.',1);
ge($conn,$g4_1,'他不仅喜欢读书，而且喜欢思考。','Ta bu jin xi huan du shu, er qie xi huan si kao.','Anh ay ko nhung thich doc ma con thich suy nghi.',2);
$g4_2=g($conn,$L4,'Cau truc 从...中...','从 + N + 中 + V','Tu...trong...','Chi xuat phat tu pham vi nao do.','从书中获得知识 = Tu sach ma co tri thuc.',2);
ge($conn,$g4_2,'从读书中，我学到了很多知识。','Cong du shu zhong, wo xue dao le hen duo zhi shi.','Tu doc sach, toi hoc duoc nhieu tri thuc.',1);
ge($conn,$g4_2,'从这本书中，我了解到中国的文化。','Cong zhe ben shu zhong, wo liao jie dao Zhong guo de wen hua.','Tu sach nay, toi biet van hoa TQ.',2);
$g4_3=g($conn,$L4,'Cau truc 连...都/也...','连 + DT + 都/也 + Phu dinh','Ngay ca...cung ko...','Nhan manh truong hop ca biet.','连这么简单的字都不认识 = Ngay ca chu don gian cung ko biet.',3);
ge($conn,$g4_3,'他连周末都在读书。','Ta lian zhou mo dou zai du shu.','Anh ay ngay ca cuoi tuan cung doc.',1);
ge($conn,$g4_3,'这本书连作者都忘了写什么了。','Zhe ben shu lian zuo zhe dou wang le xie shen me le.','Sach nay ngay tac gia cung quen viet gi.',2);
$g4_4=g($conn,$L4,'Cau truc 对...感兴趣','对 + N + 感兴趣','Ham thich','Bieu thi su yeu thich.','我对历史很感兴趣 = Toi rat thich lich su.',4);
ge($conn,$g4_4,'我对中国文化很感兴趣。','Wo dui Zhong guo wen hua hen gan xing qu.','Toi thich van hoa TQ.',1);
ge($conn,$g4_4,'你对什么类型的书感兴趣？','Ni dui shen me lei xing de shu gan xing qu?','Ban thich the loai sach nao?',2);
$d4_1=d($conn,$L4,'Loi ich doc sach','Ban ve loi ich doc sach.',1);
ds($conn,$d4_1,'Lan','你平时喜欢读书吗？','Ni ping shi xi huan du shu ma?','Ban thich doc sach ko?',1);
ds($conn,$d4_1,'Minh','非常喜欢。读书不仅让我学到知识，还让我的生活更丰富。','Fei chang xi huan. Du shu bu jin rang wo xue dao zhi shi, hai rang wo de sheng huo geng feng fu.','Rat thich. Doc ko nhung co tri thuc ma con song phong phu.',2);
ds($conn,$d4_1,'Lan','我也有这个习惯。从书中能了解到不同的世界。','Wo ye you zhe ge xi guan. Cong shu zhong neng liao jie dao bu tong de shi jie.','Toi cung co thoi quen nay. Tu sach biet the gioi khac.',3);
ds($conn,$d4_1,'Minh','对，而且读书还能提高思考能力。','Dui, er qie du shu hai neng ti gao si kao neng li.','Doc con nang cao kha nang tu duy.',4);
$d4_2=d($conn,$L4,'Sach hay','Chia se sach.',2);
ds($conn,$d4_2,'Minh','我最近在读一本很有意思的书，内容非常丰富。','Wo zui jin zai du yi ben hen you yi si de shu, nei rong fei chang feng fu.','Toi dang doc sach hay, noi dung phong phu.',1);
ds($conn,$d4_2,'Lan','是什么书？作者是谁？','Shi shen me shu? Zuo zhe shi shei?','Sach gi? Tac gia ai?',2);
ds($conn,$d4_2,'Minh','是一本关于中国历史的小说，作者是著名的作家。','Shi yi ben guan yu Zhong guo li shi de xiao shuo, zuo zhe shi zhu ming de zuo jia.','Tieu thuyet lich su TQ, tac gia la nha van noi tieng.',3);
ds($conn,$d4_2,'Lan','我对中国文化也很感兴趣，能借给我看看吗？','Wo dui Zhong guo wen hua ye hen gan xing qu, neng jie gei wo kan kan ma?','Toi cung thich van hoa TQ, muon muon xem?',4);
ds($conn,$d4_2,'Minh','当然可以！','Dang ran ke yi!','Duong nhien!',5);
$d4_3=d($conn,$L4,'Thoi quen doc sach','Hinh thanh thoi quen.',3);
ds($conn,$d4_3,'Lan','我想养成每天读书的习惯，但总是坚持不下来。','Wo xiang yang cheng mei tian du shu de xi guan, dan zong shi jian chi bu xia lai.','Toi muon tao thoi quen doc, nhung ko kien tri duoc.',1);
ds($conn,$d4_3,'Minh','你可以从每天读十页开始，慢慢来。','Ni ke yi cong mei tian du shi ye kai shi, man man lai.','Hay bat dau doc 10 trang/ngay.',2);
ds($conn,$d4_3,'Lan','好主意。连周末也要坚持吗？','Hao zhu yi. Lian zhou mo ye yao jian chi ma?','Y hay. Ca cuoi tuan cung kien tri a?',3);
ds($conn,$d4_3,'Minh','对，坚持就会变成习惯。','Dui, jian chi jiu hui bian cheng xi guan.','Kien tri se thanh thoi quen.',4);
r($conn,$L4,'Doc sach va cuoc song','对我来说，读书不仅是一种学习，更是一种生活方式。从书中，我们可以了解到世界上不同地方的文化、历史和人们的思想。读一本好书，就像和一位聪明的朋友聊天，不仅能增长知识，还能丰富我们的内心世界。我每天都会花一个小时读书，这已经成为我的习惯了。无论是小说、历史还是哲学，我对各种类型的书都很感兴趣。读书让我学会了思考，也让我越来越喜欢这个世界。如果你还没有养成读书的习惯，不妨从现在开始，每天读一点，你会发现生活因为读书而变得更加美好。','Dui wo lai shuo, du shu bu jin shi yi zhong xue xi, geng shi yi zhong sheng huo fang shi. Cong shu zhong, wo men ke yi liao jie dao shi jie shang bu tong di fang de wen hua、li shi he ren men de si xiang. Du yi ben hao shu, jiu xiang he yi wei cong ming de peng you liao tian, bu jin neng zeng zhang zhi shi, hai neng feng fu wo men de nei xin shi jie. Wo mei tian dou hui hua yi ge xiao shi du shu, zhe yi jing cheng wei wo de xi guan le. Wu lun shi xiao shuo、li shi hai shi zhe xue, wo dui ge zhong lei xing de shu dou hen gan xing qu. Du shu rang wo xue hui le si kao, ye rang wo yue lai yue xi huan zhe ge shi jie. Ru guo ni hai mei you yang cheng du shu de xi guan, bu fang cong xian zai kai shi, mei tian du yi dian, ni hui fa xian sheng huo yin wei du shu er bian de geng jia mei hao.','Voi toi, doc sach ko nhung la hoc tap ma la cach song. Tu sach ta biet van hoa, lich su, tu tuong the gioi. Doc sach hay nhu noi voi ban thong minh, tang tri thuc va phong phu tam hon. Toi moi ngay doc mot tieng, thanh thoi quen. Du la gi, toi deu thich. Doc day toi suy nghi va yeu the gioi hon. Neu ban chua co thoi quen, hay bat dau ngay.','medium',215,1);
$L4l=l($conn,$L4,'Thoi quen doc','A: Ban co thoi quen doc sach? B: Co, toi doc moi ngay. A: Ban doc loai gi? B: Toi thich tieu thuyet va lich su. A: Tai sao thich? B: Vi doc ko nhung co tri thuc ma con thu gian. A: Hay qua. Toi cung muon thu.','A: Ni you du shu de xi guan ma? B: You, wo mei tian dou du shu. A: Ni xi huan du shen me lei xing? B: Wo xi huan du xiao shuo he li shi. A: Wei shen me ni xi huan du shu? B: Yin wei du shu bu jin bang wo huo de zhi shi, er qie bang wo fang song. A: Ting qi lai hen hao. Wo ye xiang shi shi.','A: Ban co thoi quen doc sach? B: Co, toi doc moi ngay. A: Ban doc loai gi? B: Toi thich tieu thuyet va lich su. A: Tai sao thich? B: Vi doc ko nhung co tri thuc ma con thu gian. A: Hay qua. Toi cung muon thu.','1');
lq($conn,$L4l,'B doc sach the nao?','{"A":"Thinh thoang","B":"Moi ngay","C":"Cuoi tuan"}','Moi ngay','Doc moi ngay.','multiple_choice',1);
lq($conn,$L4l,'B thich doc loai gi?','{"A":"Khoa hoc","B":"Tieu thuyet va lich su","C":"Kinh te"}','Tieu thuyet va lich su','Thich tieu thuyet va lich su.','multiple_choice',2);
lq($conn,$L4l,'Tai sao B thich doc?','{"A":"Kiem tien","B":"Co tri thuc va thu gian","C":"Ket ban"}','Co tri thuc va thu gian','Ko nhung tri thuc ma con thu gian.','multiple_choice',3);
$E4_1=e($conn,$L4,'Chon dap an','"不仅...而且..." la?','multiple_choice','medium',1,'C',1);
eo($conn,$E4_1,'Neu...thi...','A',0,1); eo($conn,$E4_1,'Du...cung...','B',0,2); eo($conn,$E4_1,'Ko nhung...ma con...','C',1,3);
$E4_2=e($conn,$L4,'Dich','"Doc sach ko nhung tang tri thuc ma con phong phu cuoc song."','translation','medium',1,'读书不仅可以增长知识，而且可以丰富生活。',2);
$E4_3=e($conn,$L4,'Dien tu','我___汉语很感兴趣。','fill_blank','medium',1,'对',3);
$E4_4=e($conn,$L4,'Sap xep','不仅 / 知识 / 读书 / 增长 / 可以 / 而且 / 丰富 / 生活','sentence_order','medium',1,'读书不仅可以增长知识，而且可以丰富生活。',4);
$E4_5=e($conn,$L4,'Dung sai','"从...中..." chi xuat phat.','true_false','medium',1,'true',5);
eo($conn,$E4_5,'Dung','A',1,1); eo($conn,$E4_5,'Sai','B',0,2);
$E4_6=e($conn,$L4,'Dien tu','从这本书___，我了解中国历史。','fill_blank','medium',1,'中',6);
$E4_7=e($conn,$L4,'Chon dap an','"连...都..." dung de?','multiple_choice','medium',1,'C',7);
eo($conn,$E4_7,'So sanh','A',0,1); eo($conn,$E4_7,'Dieu kien','B',0,2); eo($conn,$E4_7,'Nhan manh ca biet','C',1,3);
$E4_8=e($conn,$L4,'Dien tu','他对什么类___的书感兴趣？','fill_blank','medium',1,'型',8);
$E4_9=e($conn,$L4,'Chon tu','Du sach nhu ___ voi ban thong minh.','multiple_choice','medium',1,'B',9);
eo($conn,$E4_9,'la','A',0,1); eo($conn,$E4_9,'noi chuyen','B',1,2); eo($conn,$E4_9,'gap','C',0,3);
foreach ([$v4_1,$v4_2,$v4_3,$v4_4,$v4_5,$v4_6,$v4_7,$v4_8,$v4_9,$v4_10,$v4_11] as $i=>$vid) if ($vid) rv($conn,$L4,$vid,'core',$i+1);
echo " HSK4 L4 done: $v4 vocab, 4 grammar, 3 dialogues, 1 reading, 1 listening, 9 exercises\n";

$L5=createLesson($conn,4,5,'Bai 5: Wei shen me xue Han yu','Tai sao hoc tieng Trung. Cau truc "wei le" (de). Cau bi dong "bei". "ba" (disposal).','["Hoc tieng Trung","Muc dich","Giao tiep"]','Hoc tap','medium','HSK4 Bai 5: 为了 (de). 被 (bi). 把 (truc tiep). 通过...来... (thong qua...de...).');
$v5=0;
$v5_1=v($conn,$L5,4,'目的','mu di','muc dich','muc dich','我学习汉语的目的是为了交流。','Wo xue xi Han yu de mu di shi wei le jiao liu.','Muc dich hoc tieng Trung la de giao tiep.','noun','Muc tieu.',++$v5);
$v5_2=v($conn,$L5,4,'为了','wei le','de, vi (muc dich)','de','为了学好汉语，我每天练习。','Wei le xue hao Han yu, wo mei tian lian xi.','De hoc tot tieng Trung, toi luyen moi ngay.','prep','Chi muc dich.',++$v5);
$v5_3=v($conn,$L5,4,'提高','ti gao','nang cao','nang cao','提高汉语水平。','Ti gao Han yu shui ping.','Nang cao trinh do.','verb','Cai thien.',++$v5);
$v5_4=v($conn,$L5,4,'交流','jiao liu','giao tiep','giao tiep','用汉语交流。','Yong Han yu jiao liu.','Giao tiep bang tieng Trung.','verb','Trao doi.',++$v5);
$v5_5=v($conn,$L5,4,'水平','shui ping','trinh do','trinh do','汉语水平提高了。','Han yu shui ping ti gao le.','Trinh do da nang cao.','noun','Trinh do.',++$v5);
$v5_6=v($conn,$L5,4,'成绩','cheng ji','thanh tich','ket qua','考试成绩很好。','Kao shi cheng ji hen hao.','Diem thi tot.','noun','Ket qua.',++$v5);
$v5_7=v($conn,$L5,4,'进步','jin bu','tien bo','tien bo','你的汉语进步很大。','Ni de Han yu jin bu hen da.','Ban tien bo nhieu.','verb/noun','Tien bo.',++$v5);
$v5_8=v($conn,$L5,4,'方法','fang fa','phuong phap','cach','学习方法很重要。','Xue xi fang fa hen zhong yao.','Phuong phap hoc quan trong.','noun','Cach thuc.',++$v5);
$v5_9=v($conn,$L5,4,'文化','wen hua','van hoa','van hoa','了解中国文化。','Liao jie Zhong guo wen hua.','Hieu van hoa TQ.','noun','Van hoa.',++$v5);
$v5_10=v($conn,$L5,4,'通过','tong guo','thong qua','qua','通过练习提高。','Tong guo lian xi ti gao.','Qua luyen tap nang cao.','prep','Dung cong cu.',++$v5);
$v5_11=v($conn,$L5,4,'把','ba','(cau truc xu ly)','xu ly','请把门关上。','Qing ba men guan shang.','Hay dong cua.','prep','Cau truc disposal.',++$v5);
$g5_1=g($conn,$L5,'Cau truc 为了','为了 + Muc dich','De lam gi','Chi muc dich, dat o dau cau hoac sau chu ngu. Phan biet: 因为 (nguyen nhan) vs 为了 (muc dich).','为了健康，我每天运动 = De suc khoe toi tap moi ngay.','Muc dich.',1);
ge($conn,$g5_1,'为了提高汉语水平，我每天和中国朋友聊天。','Wei le ti gao Han yu shui ping, wo mei tian he Zhong guo peng you liao tian.','De nang cao trinh do, toi moi ngay noi voi ban TQ.',1);
ge($conn,$g5_1,'我学汉语是为了了解中国文化。','Wo xue Han yu shi wei le liao jie Zhong guo wen hua.','Toi hoc tieng Trung de hieu van hoa TQ.',2);
$g5_2=g($conn,$L5,'Cau bi dong 被','Subject + bei + (Agent) + V','Bi lam gi',' 被 dung cho cau bi dong, Agent co the bo. Thuong cho viec ko mong muon.','他被老师批评了 = Anh ay bi co giao phe binh.','Bi dong.',2);
ge($conn,$g5_2,'他的努力被大家看到了。','Ta de nu li bei da jia kan dao le.','Su co gang cua anh duoc moi nguoi thay.',1);
ge($conn,$g5_2,'这个问题被我们解决了。','Zhe ge wen ti bei wo men jie jue le.','Van de nay duoc chung toi giai quyet.',2);
$g5_3=g($conn,$L5,'Cau truc 把','把 + Object + V + Bo ngu','Tac dong len doi tuong','Nhan manh su tac dong, doi tuong thay doi trang thai.','请把书放在桌子上 = Hay dat sach len ban.','Disposal.',3);
ge($conn,$g5_3,'请把汉语书打开。','Qing ba Han yu shu da kai.','Hay mo sach tieng Trung.',1);
ge($conn,$g5_3,'我把作业做完了。','Wo ba zuo ye zuo wan le.','Toi lam xong bai tap.',2);
$g5_4=g($conn,$L5,'Cau truc 通过...来...','通过 + PP + 来 + Muc dich','Thong qua...de...',' 通过 neu phuong thuc, 来 chi huong toi.','通过练习来提高 = Qua luyen tap de nang cao.',4);
ge($conn,$g5_4,'通过和中国朋友交流来提高口语。','Tong guo he Zhong guo peng you jiao liu lai ti gao kou yu.','Qua giao tiep voi ban TQ de nang cao khau ngu.',1);
ge($conn,$g5_4,'通过多听多说来学习汉语。','Tong guo duo ting duo shuo lai xue xi Han yu.','Qua nghe nhieu noi nhieu de hoc tieng Trung.',2);
$d5_1=d($conn,$L5,'Tai sao hoc tieng Trung','Muc dich hoc tap.',1);
ds($conn,$d5_1,'Lan','你学汉语的目的是什么？','Ni xue Han yu de mu di shi shen me?','Muc dich hoc tieng Trung cua ban?',1);
ds($conn,$d5_1,'Minh','我学汉语是为了去中国旅游时能和当地人交流。','Wo xue Han yu shi wei le qu Zhong guo lv you shi neng he dang di ren jiao liu.','Toi hoc de di du lich TQ co the giao tiep.',2);
ds($conn,$d5_1,'Lan','我也是。而且通过学汉语，我了解了很多中国文化。','Wo ye shi. Er qie tong guo xue Han yu, wo liao jie le hen duo Zhong guo wen hua.','Toi cung vay. Qua hoc tieng Trung toi biet van hoa TQ.',3);
ds($conn,$d5_1,'Minh','对，我觉得学习语言最好的方法就是多交流。','Dui, wo jue de xue xi yu yan zui hao de fang fa jiu shi duo jiao liu.','Dung, hoc ngon ngu tot nhat la giao tiep nhieu.',4);
$d5_2=d($conn,$L5,'Phuong phap hoc tap','Chia se phuong phap.',2);
ds($conn,$d5_2,'Lan','你的汉语进步这么快，有什么好方法吗？','Ni de Han yu jin bu zhe me kuai, you shen me hao fang fa ma?','Ban tien bo nhanh, co phuong phap hay?',1);
ds($conn,$d5_2,'Minh','我每天都会把新学的单词复习一遍。','Wo mei tian dou hui ba xin xue de dan ci fu xi yi bian.','Toi moi ngay deu on lai tu moi hoc.',2);
ds($conn,$d5_2,'Lan','还有呢？','Hai you ne?','Con nua?',3);
ds($conn,$d5_2,'Minh','为了练习听力，我每天听中文播客。','Wei le lian xi ting li, wo mei tian ting Zhong wen bo ke.','De luyen nghe, toi nghe podcast TQ.',4);
ds($conn,$d5_2,'Lan','我也试试这些方法。','Wo ye shi shi zhe xie fang fa.','Toi cung thu.',5);
$d5_3=d($conn,$L5,'Thanh tich','Noi ve thanh tich.',3);
ds($conn,$d5_3,'Lan','这次HSK考试成绩出来了，我过了四级！','Zhe ci HSK kao shi cheng ji chu lai le, wo guo le si ji!','Thi HSK ra diem, toi do HSK4!',1);
ds($conn,$d5_3,'Minh','恭喜你！你的努力终于被大家看到了。','Gong xi ni! Ni de nu li zhong yu bei da jia kan dao le.','Chuc mung! Co gang cua ban duoc moi nguoi thay.',2);
ds($conn,$d5_3,'Lan','谢谢！我会继续进步的。','Xie xie! Wo hui ji xu jin bu de.','Cam on! Toi se tiep tuc co gang.',3);
ds($conn,$d5_3,'Minh','为了更高的目标，我们一起努力吧。','Wei le geng gao de mu biao, wo men yi qi nu li ba.','De muc tieu cao hon, ta cung co gang.',4);
ds($conn,$d5_3,'Lan','好！把汉语学得越来越好。','Hao! Ba Han yu xue de yue lai yue hao.','Tot! Hoc tieng Trung ngay cang tot.',5);
r($conn,$L5,'Tai sao hoc tieng Trung','我学习汉语已经三年了。很多人问我为什么学汉语。其实我的目的很简单：为了能和中国人交流，为了了解丰富多彩的中国文化。刚开始的时候我觉得汉语很难，特别是声调。但是通过每天坚持练习，我的汉语水平慢慢提高了。我用的方法是多听多说，把学到的单词立刻用在对话中。为了练习口语，我经常和中国朋友聊天。他们的鼓励让我很感动，也让我的进步更快。现在我已经通过了HSK四级，但我不会停止学习。我的下一个目标是通过HSK五级。我相信只要能坚持，就一定能成功。','Wo xue xi Han yu yi jing san nian le. Hen duo ren wen wo wei shen me xue Han yu. Qi shi wo de mu di hen jian dan: wei le neng he Zhong guo ren jiao liu, wei le liao jie feng fu duo cai de Zhong guo wen hua. Gang kai shi de shi hou wo jue de Han yu hen nan, te bie shi sheng diao. Dan shi tong guo mei tian jian chi lian xi, wo de Han yu shui ping man man ti gao le. Wo yong de fang fa shi duo ting duo shuo, ba xue dao de dan ci li ke yong zai dui hua zhong. Wei le lian xi kou yu, wo jing chang he Zhong guo peng you liao tian. Ta men de gu li rang wo hen gan dong, ye rang wo de jin bu geng kuai. Xian zai wo yi jing tong guo le HSK si ji, dan wo bu hui ting zhi xue xi. Wo de xia yi ge mu biao shi tong guo HSK wu ji. Wo xiang xin zhi yao neng jian chi, jiu yi ding neng cheng gong.','Toi hoc tieng Trung 3 nam. Nhieu nguoi hoi tai sao. Muc dich de giao tiep va hieu van hoa TQ. Ban dau kho, nhat la thanh dieu. Nhung kien tri luyen tap, trinh do nang cao. Phuong phap: nghe nhieu noi nhieu, ap dung tu da hoc. Toi noi voi ban TQ de luyen khau ngu. Ho khuyen khich khien toi cam dong va tien bo nhanh. Toi da do HSK4, se tiep tuc len HSK5. Toi tin kien tri se thanh cong.','medium',220,1);
$L5l=l($conn,$L5,'Hoc tieng Trung','A: Ban hoc tieng Trung bao lau? B: 3 nam. A: Tai sao bat dau? B: Ban dau vi thich phim TQ. Sau do phat hien hoc tieng Trung con giup hieu van hoa. A: Co phuong phap hay? B: Xem phim TQ va noi voi ban TQ. Thu vi lam.','A: Ni xue Han yu duo chang shi jian le? B: Yi jing san nian le. A: Wei shen me ni kai shi xue? B: Kai shi shi yin wei wo xi huan Zhong guo dian ying. Dan shi hou lai wo fa xian xue Han yu hai neng bang wo liao jie wen hua. A: Ni you shen me hao de xue xi fang fa ma? B: Wo de fang fa shi kan Zhong guo dian ying he he Zhong guo peng you jiao liu. Zhe ge guo cheng hen you yi si.','A: Ban hoc tieng Trung bao lau? B: 3 nam. A: Tai sao bat dau? B: Ban dau vi thich phim TQ. Sau do phat hien hoc tieng Trung con giup hieu van hoa. A: Co phuong phap hay? B: Xem phim TQ va noi voi ban TQ. Thu vi lam.','1');
lq($conn,$L5l,'B hoc tieng Trung bao lau?','{"A":"1 nam","B":"2 nam","C":"3 nam"}','3 nam','3 nam.','multiple_choice',1);
lq($conn,$L5l,'Sao B bat dau hoc?','{"A":"Thich phim TQ","B":"Vi cong viec","C":"Vi ban be"}','Thich phim TQ','Ban dau vi thich phim TQ.','multiple_choice',2);
lq($conn,$L5l,'Phuong phap hoc cua B?','{"A":"Doc sach","B":"Xem phim va giao tiep","C":"Hoc thuoc"}','Xem phim va giao tiep','Xem phim TQ va noi voi ban TQ.','multiple_choice',3);
$E5_1=e($conn,$L5,'Chon dap an','"为了" chi?','multiple_choice','medium',1,'B',1);
eo($conn,$E5_1,'Nguyen nhan','A',0,1); eo($conn,$E5_1,'Muc dich','B',1,2); eo($conn,$E5_1,'Ket qua','C',0,3);
$E5_2=e($conn,$L5,'Dich','"Toi hoc tieng Trung de hieu van hoa TQ."','translation','medium',1,'我学汉语是为了了解中国文化。',2);
$E5_3=e($conn,$L5,'Dien tu','请把书___在桌子上。','fill_blank','medium',1,'放',3);
$E5_4=e($conn,$L5,'Sap xep','为了 / 汉语 / 提高 / 水平 / 我 / 每天 / 练习','sentence_order','medium',1,'为了提高汉语水平，我每天练习。',4);
$E5_5=e($conn,$L5,'Dung sai','"被" trong cau bi dong.','true_false','medium',1,'true',5);
eo($conn,$E5_5,'Dung','A',1,1); eo($conn,$E5_5,'Sai','B',0,2);
$E5_6=e($conn,$L5,'Dien tu','我把作业做___了。','fill_blank','medium',1,'完',6);
$E5_7=e($conn,$L5,'Chon dap an','"把" nhan manh?','multiple_choice','medium',1,'C',7);
eo($conn,$E5_7,'Chu the','A',0,1); eo($conn,$E5_7,'Thoi gian','B',0,2); eo($conn,$E5_7,'Tac dong len doi tuong','C',1,3);
$E5_8=e($conn,$L5,'Dien tu','通___多练习来提高。','fill_blank','medium',1,'过',8);
$E5_9=e($conn,$L5,'Chon tu','努力___ moi nguoi thay.','multiple_choice','medium',1,'B',9);
eo($conn,$E5_9,'把','A',0,1); eo($conn,$E5_9,'被','B',1,2); eo($conn,$E5_9,'对','C',0,3);
$E5_10=e($conn,$L5,'Dien tu','qua giao tiep de nang cao -> tong guo...___...','fill_blank','medium',1,'来',10);
foreach ([$v5_1,$v5_2,$v5_3,$v5_4,$v5_5,$v5_6,$v5_7,$v5_8,$v5_9,$v5_10,$v5_11] as $i=>$vid) if ($vid) rv($conn,$L5,$vid,'core',$i+1);
echo " HSK4 L5 done: $v5 vocab, 4 grammar, 3 dialogues, 1 reading, 1 listening, 10 exercises\n";

$conn->exec("SET FOREIGN_KEY_CHECKS=1");
echo "\n HSK4 Lessons 1-5 seeding complete!\n";
