<?php
require_once __DIR__ . '/seed_helpers.php';
$conn->exec("SET FOREIGN_KEY_CHECKS=0");
$L1=createLesson($conn,4,6,'Bai 6: Chi zai Zhong guo','Am thuc Trung Hoa. "bu jin...hai..." (ko nhung...con...). "ge" (moi, cac). "su ran...dan shi..." (mac du...nhung...).','["Am thuc","Trung Hoa","Van hoa am thuc"]','Am thuc','medium','HSK4 Bai 6: Am thuc TQ. 不仅...还... (ko nhung...con...). 各 (moi/cac). 虽然...但是... (mac du...nhung...). Cach dung 又...又...');
$v1=0;
$v1_1=v($conn,$L1,4,'吃','chi','an','an','你吃了吗？','Ni chi le ma?','Ban an chua?','verb','An uong.',++$v1);
$v1_2=v($conn,$L1,4,'中国菜','Zhong guo cai','mon an TQ','mon an TQ','中国菜很好吃。','Zhong guo cai hen hao chi.','Mon TQ ngon.','noun','Mon an.',++$v1);
$v1_3=v($conn,$L1,4,'味道','wei dao','mùi vi','vi','这道菜味道很好。','Zhe dao cai wei dao hen hao.','Mon nay vi ngon.','noun','Mui vi.',++$v1);
$v1_4=v($conn,$L1,4,'辣','la','cay','cay','重庆菜很辣。','Chong qing cai hen la.','Mon Trung Kinh cay.','adj','Vi cay.',++$v1);
$v1_5=v($conn,$L1,4,'甜','tian','ngot','ngot','这个甜点很甜。','Zhe ge tian dian hen tian.','Mon trang mieng ngot.','adj','Vi ngot.',++$v1);
$v1_6=v($conn,$L1,4,'各','ge','moi, cac','moi','各地有不同口味。','Ge di you bu tong kou wei.','Moi noi co khau vi khac.','det','Moi loai.',++$v1);
$v1_7=v($conn,$L1,4,'南方','nan fang','mien Nam','mien Nam','南方人喜欢吃米饭。','Nan fang ren xi huan chi mi fan.','Nguoi mien Nam thich com.','noun','Phuong Nam.',++$v1);
$v1_8=v($conn,$L1,4,'北方','bei fang','mien Bac','mien Bac','北方人喜欢吃面条。','Bei fang ren xi huan chi mian tiao.','Nguoi Bac thich mi.','noun','Phuong Bac.',++$v1);
$v1_9=v($conn,$L1,4,'美食','mei shi','mon ngon','am thuc','中国有很多美食。','Zhong guo you hen duo mei shi.','TQ co nhieu mon ngon.','noun','Am thuc ngon.',++$v1);
$v1_10=v($conn,$L1,4,'尝','chang','nem thu','nem','你尝尝这个。','Ni chang chang zhe ge.','Hay nem cai nay.','verb','Thu vi.',++$v1);
$v1_11=v($conn,$L1,4,'特色','te se','dac sac','dac sac','这是四川的特色菜。','Zhe shi Si chuan de te se cai.','Day la dac san Tu Xuyen.','noun','Dac biet.',++$v1);
$v1_12=v($conn,$L1,4,'厨房','chu fang','bep','bep','他在厨房做饭。','Ta zai chu fang zuo fan.','Anh ay nau an trong bep.','noun','Bep.',++$v1);
$g1_1=g($conn,$L1,'Cau truc 不仅...还...','不仅 + A + 还 + B','Ko nhung...con...','Bo sung tang tien, 还 nhan manh them.','他不仅会做中国菜，还会做日本菜.',1);
ge($conn,$g1_1,'他不仅会吃，还会做中国菜。','Ta bu jin hui chi, hai hui zuo Zhong guo cai.','Anh ay ko nhung biet an ma con biet nau.',1);
ge($conn,$g1_2,'中国菜不仅味道好，而且营养丰富。','Zhong guo cai bu jin wei dao hao, er qie ying yang feng fu.','Mon TQ ko nhung ngon ma con dinh duong.',2);
$g1_2=g($conn,$L1,'Cau truc 各 + Danh tu','各 + N','Moi / Cac','各 chi moi ca the hoac moi loai.','各地有不同风俗 = Moi noi co phong tuc khac.',2);
ge($conn,$g1_2,'中国各地有不同口味。','Zhong guo ge di you bu tong kou wei.','Moi vung mien TQ co khau vi khac.',1);
ge($conn,$g1_2,'这家餐馆各道菜都很好吃。','Zhe jia can guan ge dao cai dou hen hao chi.','Nha hang nay moi mon deu ngon.',2);
$g1_3=g($conn,$L1,'Cau truc 虽然...但是...','虽然 + A + 但是 + B','Mac du...nhung...',' 虽然 chi nhuong bo thuc te, 但是 chi ket qua.','虽然辣但是很好吃 = Mac du cay nhung ngon.','Tuong phan.',3);
ge($conn,$g1_3,'虽然这道菜很辣，但是很好吃。','Sui ran zhe dao cai hen la, dan shi hen hao chi.','Mac du mon nay cay nhung ngon.',1);
ge($conn,$g1_3,'虽然我不太会做饭，但是我愿意学。','Sui ran wo bu tai hui zuo fan, dan shi wo yuan yi xue.','Mac du toi ko biet nau, nhung toi muon hoc.',2);
$g1_4=g($conn,$L1,'Cau truc 又...又...','又 + Adj1 + 又 + Adj2','Vua...vua...','Chi mot doi tuong co hai thuoc tinh.','这个菜又便宜又好吃 = Mon nay vua re vua ngon.',4);
ge($conn,$g1_4,'这个菜又便宜又好吃。','Zhe ge cai you pian yi you hao chi.','Mon nay vua re vua ngon.',1);
ge($conn,$g1_4,'这家餐厅又干净又舒服。','Zhe jia can ting you gan jing you shu fu.','Nha hang nay vua sach vua thoai mai.',2);
$d1_1=d($conn,$L1,'Am thuc TQ','Thu mon TQ.',1);
ds($conn,$d1_1,'Lan','你来中国吃过什么美食？','Ni lai Zhong guo chi guo shen me mei shi?','Ban den TQ an gi ngon?',1);
ds($conn,$d1_1,'Minh','我吃过北京烤鸭，味道非常好。','Wo chi guo Bei jing kao ya, wei dao fei chang hao.','Toi an vit quay Bac Kinh, vi ngon.',2);
ds($conn,$d1_1,'Lan','你尝过四川菜吗？很辣。','Ni chang guo Si chuan cai ma? Hen la.','Ban an mon Tu Xuyen chua? Cay lam.',3);
ds($conn,$d1_1,'Minh','虽然很辣，但是越吃越想吃。','Sui ran hen la, dan shi yue chi yue xiang chi.','Mac du cay, nhung cang an cang muon an.',4);
ds($conn,$d1_1,'Lan','中国菜不仅好吃，而且很有特色。','Zhong guo cai bu jin hao chi, er qie hen you te se.','Mon TQ ko nhung ngon ma con dac sac.',5);
$d1_2=d($conn,$L1,'Khau vi khac nhau','Khau vi Nam Bac.',2);
ds($conn,$d1_2,'Lan','你们北方人吃什么？','Ni men bei fang ren chi shen me?','Nguoi Bac an gi?',1);
ds($conn,$d1_2,'Minh','北方人喜欢吃面条和饺子。','Bei fang ren xi huan chi mian tiao he jiao zi.','Nguoi Bac thich an mi va banh chao.',2);
ds($conn,$d1_2,'Lan','我们南方人喜欢吃米饭。','Wo men nan fang ren xi huan chi mi fan.','Nguoi Nam chung toi thich com.',3);
ds($conn,$d1_2,'Minh','各地有各地的特色，都很美味。','Ge di you ge di de te se, dou hen mei wei.','Moi noi co dac sac rieng, deu ngon.',4);
$d1_3=d($conn,$L1,'Hoc nau an','Hoc nau mon TQ.',3);
ds($conn,$d1_3,'Lan','你会做中国菜吗？','Ni hui zuo Zhong guo cai ma?','Ban biet nau mon TQ ko?',1);
ds($conn,$d1_3,'Minh','会一点。我最近在学做麻婆豆腐。','Hui yi dian. Wo zui jin zai xue zuo Ma po dou fu.','Biet mot chut. Toi hoc nau Mapo Doufu.',2);
ds($conn,$d1_3,'Lan','这道菜又辣又香，我很喜欢。','Zhe dao cai you la you xiang, wo hen xi huan.','Mon nay vua cay vua thom, toi thich.',3);
ds($conn,$d1_3,'Minh','下次我做给你尝尝。','Xia ci wo zuo gei ni chang chang.','Lan sau toi lam cho ban nem.',4);
r($conn,$L1,'Am thuc Trung Hoa','中国是一个美食大国，各地有各的特色。北方人喜欢吃面条、饺子和馒头，口味偏咸。南方人喜欢吃米饭，口味偏清淡。四川人喜欢吃辣的，重庆火锅非常有名。广东人喜欢喝汤，他们的汤又营养又好喝。在中国，吃饭不仅是为了填饱肚子，更是一种文化交流。朋友聚会、家庭团圆都离不开一桌好菜。如果你来中国旅游，一定要尝尝各地的美食。','Zhong guo shi yi ge mei shi da guo, ge di you ge de te se. Bei fang ren xi huan chi mian tiao、jiao zi he man tou, kou wei pian xian. Nan fang ren xi huan chi mi fan, kou wei pian qing dan. Si chuan ren xi huan chi la de, Chong qing huo guo fei chang you ming. Guang dong ren xi huan he tang, ta men de tang you ying yang you hao he. Zai Zhong guo, chi fan bu jin shi wei le tian bao du zi, geng shi yi zhong wen hua jiao liu. Peng you ju hui、jia ting tuan yuan dou li bu kai yi zhuo hao cai. Ru guo ni lai Zhong guo lv you, yi ding yao chang chang ge di de mei shi.','TQ la dat nuoc am thuc, moi noi co net rieng. Mien Bac thich mi, banh chao. Nam thich com, thanh dam. Tu Xuyen thich cay, lau Trung Kinh noi tieng. Quang Dong thich sup, vua bo vua ngon. An o TQ ko chi de no ma la giao luu van hoa. Gap go ban be, sum hop gia dinh deu can com ngon. Du lich TQ nho nem dac san moi noi.','medium',180,1);
$L1l=l($conn,$L1,'Am thuc','A: Ban da an mon TQ gi chua? B: An vit quay Bac Kinh va lau Trung Kinh. A: Thich mon nao nhat? B: Vit quay, mac du lau cung ngon. A: Co dinh hoc nau ko? B: Co, toi muon hoc nau mon TQ.','A: Ni chi guo Zhong guo cai ma? B: Chi guo Bei jing kao ya he Chong qing huo guo. A: Ni zui xi huan na ge? B: Kao ya, sui ran huo guo ye hen hao chi. A: Ni da suan xue zuo Zhong guo cai ma? B: Shi de, wo xiang xue.','A: Ban da an mon TQ gi? B: An vit quay BK va lau TK. A: Thich mon nao nhat? B: Vit quay, du lau cung ngon. A: Dinh hoc nau ko? B: Co, toi muon hoc.','1');
lq($conn,$L1l,'B da an mon gi?','{"A":"Com chien","B":"Vit quay BK va lau TK","C":"Mi"}','Vit quay BK va lau TK','Da an vit quay va lau.','multiple_choice',1);
lq($conn,$L1l,'B thich mon nao?','{"A":"Lau","B":"Vit quay","C":"Ca hai"}','Vit quay','Thich vit quay nhat.','multiple_choice',2);
lq($conn,$L1l,'B co dinh hoc nau?','{"A":"Co","B":"Khong","C":"Chua nghi"}','Co','Muon hoc nau.','multiple_choice',3);
$E1_1=e($conn,$L1,'Chon dap an','"各" co nghia la?','multiple_choice','medium',1,'C',1);
eo($conn,$E1_1,'Ca','A',0,1); eo($conn,$E1_1,'Mot','B',0,2); eo($conn,$E1_1,'Moi, cac','C',1,3);
$E1_2=e($conn,$L1,'Dich','"Mac du cay nhung ngon."','translation','medium',1,'虽然辣但是很好吃。',2);
$E1_3=e($conn,$L1,'Dien tu','北方___吃面条。(Nguoi...)','fill_blank','medium',1,'人',3);
$E1_4=e($conn,$L1,'Sap xep','虽然 / 辣 / 好吃 / 但是 / 很','sentence_order','medium',1,'虽然辣但是很好吃。',4);
$E1_5=e($conn,$L1,'Dung sai','"美食" la "mon ngon".','true_false','easy',1,'true',5);
eo($conn,$E1_5,'Dung','A',1,1); eo($conn,$E1_5,'Sai','B',0,2);
$E1_6=e($conn,$L1,'Dien tu','中国各地有不___口味。','fill_blank','medium',1,'同',6);
$E1_7=e($conn,$L1,'Chon dap an','"又...又..." bieu thi?','multiple_choice','medium',1,'A',7);
eo($conn,$E1_7,'Vua...vua...','A',1,1); eo($conn,$E1_7,'Hoac...hoac...','B',0,2); eo($conn,$E1_7,'Tuy...nhung...','C',0,3);
$E1_8=e($conn,$L1,'Dien tu','这个菜又便宜___好吃。','fill_blank','medium',1,'又',8);
$E1_9=e($conn,$L1,'Chon tu','___ bu jin hao chi, er qie hen you te se.','multiple_choice','medium',1,'B',9);
eo($conn,$E1_9,'Mon TQ','A',0,1); eo($conn,$E1_9,'中国菜','B',1,2); eo($conn,$E1_9,'Am thuc','C',0,3);
foreach ([$v1_1,$v1_2,$v1_3,$v1_4,$v1_5,$v1_6,$v1_7,$v1_8,$v1_9,$v1_10,$v1_11,$v1_12] as $i=>$vid) if ($vid) rv($conn,$L1,$vid,'core',$i+1);
echo " HSK4 L6 done: $v1 vocab, 4 grammar, 3 dialogues, 1 reading, 1 listening, 9 exercises\n";

$L2=createLesson($conn,4,7,'Bai 7: Zui hao de jiao yu','Giao duc tot nhat. "pei yang" (boi duong). "huan jing" (moi truong). "ying xiang" (anh huong).','["Giao duc","Nuoi day","Moi truong"]','Giao duc','medium','HSK4 Bai 7: Giao duc tot nhat. 培养 (boi duong). 环境 (moi truong). 影响 (anh huong). 为了...而... (de...ma...).');
$v2=0;
$v2_1=v($conn,$L2,4,'教育','jiao yu','giao duc','giao duc','教育很重要。','Jiao yu hen zhong yao.','Giao duc rat quan trong.','noun','Su giao duc.',++$v2);
$v2_2=v($conn,$L2,4,'培养','pei yang','boi duong','boi duong','培养孩子的兴趣。','Pei yang hai zi de xing qu.','Boi duong so thich cua tre.','verb','Dao tao.',++$v2);
$v2_3=v($conn,$L2,4,'环境','huan jing','moi truong','moi truong','家庭环境很重要。','Jia ting huan jing hen zhong yao.','Moi truong gia dinh quan trong.','noun','Moi truong xung quanh.',++$v2);
$v2_4=v($conn,$L2,4,'影响','ying xiang','anh huong','anh huong','父母影响孩子。','Fu mu ying xiang hai zi.','Cha me anh huong con.','verb/noun','Tac dong.',++$v2);
$v2_5=v($conn,$L2,4,'父母','fu mu','cha me','cha me','父母是孩子的第一任老师。','Fu mu shi hai zi de di yi ren lao shi.','Cha me la thay co dau tien.','noun','Bo me.',++$v2);
$v2_6=v($conn,$L2,4,'孩子','hai zi','con cai','con','孩子需要关爱。','Hai zi xu yao guan ai.','Tre can yeu thuong.','noun','Tre em.',++$v2);
$v2_7=v($conn,$L2,4,'鼓励','gu li','khuyen khich','khuyen khich','鼓励孩子尝试新事物。','Gu li hai zi chang shi xin shi wu.','Khuyen tre thu cai moi.','verb','Dong vien.',++$v2);
$v2_8=v($conn,$L2,4,'独立','du li','doc lap','doc lap','孩子要学会独立。','Hai zi yao xue hui du li.','Tre phai hoc doc lap.','adj','Tu chu.',++$v2);
$v2_9=v($conn,$L2,4,'耐心','nai xin','nhan nai','kien nhan','教育孩子需要耐心。','Jiao yu hai zi xu yao nai xin.','Day tre can kien nhan.','noun/adj','Kien tri.',++$v2);
$v2_10=v($conn,$L2,4,'方式','fang shi','cach thuc','cach','教育方式很重要。','Jiao yu fang shi hen zhong yao.','Cach giao duc quan trong.','noun','Phuong thuc.',++$v2);
$v2_11=v($conn,$L2,4,'成长','cheng zhang','truong thanh','lon len','孩子在快乐中成长。','Hai zi zai kuai le zhong cheng zhang.','Tre lon len trong niem vui.','verb','Phat trien.',++$v2);
$g2_1=g($conn,$L2,'Cau truc 环境影响','环境 + Y + N + V','Moi truong anh huong gi','环境 chu the tac dong.','家庭环境会影响孩子的性格.',1);
ge($conn,$g2_1,'好的环境能让孩子健康成长。','Hao de huan jing neng rang hai zi jian kang cheng zhang.','Moi truong tot giup tre phat trien khoe.',1);
ge($conn,$g2_2,'家庭环境对孩子的成长有很大影响。','Jia ting huan jing dui hai zi de cheng zhang you hen da ying xiang.','Moi truong gia dinh anh huong lon den tre.',2);
$g2_2=g($conn,$L2,'Cau truc 鼓励 + ai + V','鼓励 + N + V','Khuyen ai lam gi',' 鼓励 khuyen khich ai do lam viec gi.','鼓励孩子多读书 = Khuyen tre doc sach.',2);
ge($conn,$g2_2,'父母应该鼓励孩子多读书。','Fu mu ying gai gu li hai zi duo du shu.','Cha me nen khuyen tre doc sach nhieu.',1);
ge($conn,$g2_2,'老师鼓励我们参加活动。','Lao shi gu li wo men can jia huo dong.','Co giao khuyen chung toi tham gia hoat dong.',2);
$g2_3=g($conn,$L2,'Cau truc 为了...而...','为了 + Muc dic + 而 + V','De...ma...','Nhan manh muc dich cua hanh dong.','为了教育孩子而努力 = Vi day con ma co gang.',3);
ge($conn,$g2_3,'为了孩子的未来，父母付出了很多。','Wei le hai zi de wei lai, fu mu fu chu le hen duo.','Vi tuong lai con, cha me da hy sinh nhieu.',1);
ge($conn,$g2_3,'为了培养孩子的兴趣，他每天陪孩子练习。','Wei le pei yang hai zi de xing qu, ta mei tian pei hai zi lian xi.','De boi duong so thich con, anh ay ngay ngay tap cung con.',2);
$d2_1=d($conn,$L2,'Giao duc gia dinh','Giao duc tu nho.',1);
ds($conn,$d2_1,'Lan','你觉得最好的教育是什么？','Ni jue de zui hao de jiao yu shi shen me?','Ban nghi giao duc tot nhat la gi?',1);
ds($conn,$d2_1,'Minh','我觉得父母的陪伴是最好的教育。','Wo jue de fu mu de pei ban shi zui hao de jiao yu.','Toi nghi su dong hanh cua cha me la tot nhat.',2);
ds($conn,$d2_1,'Lan','对，环境对孩子的成长影响很大。','Dui, huan jing dui hai zi de cheng zhang ying xiang hen da.','Dung, moi truong anh huong lon den tre.',3);
ds($conn,$d2_1,'Minh','所以父母要以身作则。','Suo yi fu mu yao yi shen zuo ze.','Nen cha me phai lam guong.',4);
$d2_2=d($conn,$L2,'Khuyen khich con','Cach khuyen con.',2);
ds($conn,$d2_2,'Lan','你的孩子学钢琴吗？','Ni de hai zi xue gang qin ma?','Con ban hoc piano ko?',1);
ds($conn,$d2_2,'Minh','学。虽然很难，但我一直鼓励他。','Xue. Sui ran hen nan, dan wo yi zhi gu li ta.','Co. Mac du kho, toi luon khuyen khich.',2);
ds($conn,$d2_2,'Lan','培养兴趣需要耐心。','Pei yang xing qu xu yao nai xin.','Boi duong so thich can kien nhan.',3);
ds($conn,$d2_2,'Minh','对，而且要用正确的方式。','Dui, er qie yao yong zheng que de fang shi.','Dung, va phai dung cach dung.',4);
$d2_3=d($conn,$L2,'Tre lon len','Con cai truong thanh.',3);
ds($conn,$d2_3,'Lan','你希望孩子成为什么样的人？','Ni xi wang hai zi cheng wei shen me yang de ren?','Ban mong con thanh nguoi the nao?',1);
ds($conn,$d2_3,'Minh','我希望他成为一个独立、善良的人。','Wo xi wang ta cheng wei yi ge du li、shan liang de ren.','Toi mong con thanh nguoi doc lap, tot bung.',2);
ds($conn,$d2_3,'Lan','这需要从小培养。','Zhe xu yao cong xiao pei yang.','Can boi duong tu nho.',3);
ds($conn,$d2_3,'Minh','对，教育是一辈子的事。','Dui, jiao yu shi yi bei zi de shi.','Dung, giao duc la chuyen ca doi.',4);
r($conn,$L2,'Giao duc tot nhat','很多人都认为最好的教育是送孩子去最好的学校。但是我认为，父母的爱和陪伴才是最好的教育。家庭环境对孩子的成长有很大的影响。如果父母经常鼓励孩子，孩子就会变得更加自信和独立。相反，如果父母总是批评孩子，孩子就会变得胆小。教育不仅仅是学习知识，更重要的是教会孩子如何做人。父母应该以身作则，用自己的行为影响孩子。为了孩子的未来，父母要耐心地培养他们，让他们在快乐中成长。','Hen duo ren dou ren wei zui hao de jiao yu shi song hai zi qu zui hao de xue xiao. Dan shi wo ren wei, fu mu de ai he pei ban cai shi zui hao de jiao yu. Jia ting huan jing dui hai zi de cheng zhang you hen da de ying xiang. Ru guo fu mu jing chang gu li hai zi, hai zi jiu hui bian de geng jia zi xin he du li. Xiang fan, ru guo fu mu zong shi pi ping hai zi, hai zi jiu hui bian de dan xiao. Jiao yu bu jin jin shi xue xi zhi shi, geng zhong yao de shi jiao hui hai zi ru he zuo ren. Fu mu ying gai yi shen zuo ze, yong zi ji de xing wei ying xiang hai zi. Wei le hai zi de wei lai, fu mu yao nai xin di pei yang ta men, rang ta men zai kuai le zhong cheng zhang.','Nhieu nguoi cho rang giao duc tot nhat la truong tot. Nhung toi nghi yeu thuong va dong hanh cua cha me moi la tot nhat. Moi truong gia dinh anh huong lon den tre. Neu cha me khuyen khich, tre tu tin va doc lap. Nguoc lai, cha me chi trich khien tre nhut nhat. Giao duc ko chi la kien thuc ma con day lam nguoi. Cha me lam guong, kien nhan boi duong de tre lon vui ve.','medium',195,1);
$L2l=l($conn,$L2,'Giao duc','A: Cha me ban day ban the nao? B: Ho rat kien nhan, luon khuyen khich toi. A: Ho co gay ap luc ko? B: Ko, ho de toi tu chon. A: Ban thay cach giao duc do the nao? B: Toi rat biet on ho.','A: Ni de fu mu shi zen me jiao yu ni de? B: Ta men hen you nai xin, zong shi gu li wo. A: Ta men hui gei ni ya li ma? B: Bu hui, ta men rang wo zi ji xuan ze. A: Ni jue de zhe zhong jiao yu fang shi zen me yang? B: Wo hen gan ji ta men.','A: Cha me ban day ban the nao? B: Ho rat kien nhan, luon khuyen khich toi. A: Ho co gay ap luc ko? B: Ko, ho de toi tu chon. A: Ban thay cach giao duc do the nao? B: Toi rat biet on ho.','1');
lq($conn,$L2l,'Cha me B day con the nao?','{"A":"Nghiem khac","B":"Kien nhan va khuyen khich","C":"Bo mac"}','Kien nhan va khuyen khich','Ho kien nhan va khuyen khich.','multiple_choice',1);
lq($conn,$L2l,'Cha me B co gay ap luc?','{"A":"Co","B":"Khong","C":"Thinh thoang"}','Khong','De con tu chon.','multiple_choice',2);
lq($conn,$L2l,'B cam thay the nao?','{"A":"Ghet","B":"Biet on","C":"Binh thuong"}','Biet on','Rat biet on.','multiple_choice',3);
$E2_1=e($conn,$L2,'Chon dap an','"培养" la?','multiple_choice','medium',1,'C',1);
eo($conn,$E2_1,'Hoc tap','A',0,1); eo($conn,$E2_1,'Day do','B',0,2); eo($conn,$E2_1,'Boi duong','C',1,3);
$E2_2=e($conn,$L2,'Dich','"Moi truong gia dinh anh huong lon den tre."','translation','medium',1,'家庭环境对孩子有大的影响。',2);
$E2_3=e($conn,$L2,'Dien tu','父母应该鼓___孩子多读书。','fill_blank','medium',1,'励',3);
$E2_4=e($conn,$L2,'Sap xep','鼓励 / 父母 / 孩子 / 应该','sentence_order','medium',1,'父母应该鼓励孩子。',4);
$E2_5=e($conn,$L2,'Dung sai','"环境" la "hoan canh".','true_false','easy',1,'false',5);
eo($conn,$E2_5,'Dung','A',0,1); eo($conn,$E2_5,'Sai','B',1,2);
$E2_6=e($conn,$L2,'Dien tu','为了孩子___未来，父母付出很多。','fill_blank','medium',1,'的',6);
$E2_7=e($conn,$L2,'Chon dap an','Cau nao dung?','multiple_choice','medium',1,'A',7);
eo($conn,$E2_7,'父母鼓励孩子学习。','A',1,1); eo($conn,$E2_7,'父母鼓励学习孩子。','B',0,2); eo($conn,$E2_7,'鼓励父母孩子学习。','C',0,3);
$E2_8=e($conn,$L2,'Dien tu','教育孩子需要耐___。','fill_blank','medium',1,'心',8);
foreach ([$v2_1,$v2_2,$v2_3,$v2_4,$v2_5,$v2_6,$v2_7,$v2_8,$v2_9,$v2_10,$v2_11] as $i=>$vid) if ($vid) rv($conn,$L2,$vid,'core',$i+1);
echo " HSK4 L7 done: $v2 vocab, 3 grammar, 3 dialogues, 1 reading, 1 listening, 8 exercises\n";

$L3=createLesson($conn,4,8,'Bai 8: Hai shi bu yong jian fei','Ko can giam can. "jian fei" (giam can). "jian kang" (suc khoe). "zhi yao...jiu..." (chi can...la...).','["Giam can","Suc khoe","Van dong"]','Suc khoe','medium','HSK4 Bai 8: Giam can. 只要...就... (chi can...la...). 其实 (thuc ra). Cau truc phu dinh: 不用 (ko can).');
$v3=0;
$v3_1=v($conn,$L3,4,'减肥','jian fei','giam can','giam can','我正在减肥。','Wo zheng zai jian fei.','Toi dang giam can.','verb','Giam can.',++$v3);
$v3_2=v($conn,$L3,4,'健康','jian kang','suc khoe','khoe','健康最重要。','Jian kang zui zhong yao.','Suc khoe quan trong nhat.','adj/noun','Suc khoe.',++$v3);
$v3_3=v($conn,$L3,4,'运动','yun dong','van dong','tap','每天运动对身体好。','Mei tian yun dong dui shen ti hao.','Van dong moi ngay tot cho co the.','verb/noun','The thao.',++$v3);
$v3_4=v($conn,$L3,4,'胖','pang','beo','beo','我胖了三公斤。','Wo pang le san gong jin.','Toi beo 3kg.','adj','Beo, map.',++$v3);
$v3_5=v($conn,$L3,4,'瘦','shou','gay','gay','她比以前瘦了。','Ta bi yi qian shou le.','Co ay gay hon truoc.','adj','Om.',++$v3);
$v3_6=v($conn,$L3,4,'体重','ti zhong','can nang','can','我的体重增加了。','Wo de ti zhong zeng jia le.','Can nang toi tang.',++$v3);
$v3_7=v($conn,$L3,4,'其实','qi shi','thuc ra','thuc ra','其实你不用减肥。','Qi shi ni bu yong jian fei.','Thuc ra ban ko can giam can.','adv','Su that la.',++$v3);
$v3_8=v($conn,$L3,4,'担心','dan xin','lo lang','lo','别担心，会好的。','Bie dan xin, hui hao de.','Dung lo, se on.','verb','Lo so.',++$v3);
$v3_9=v($conn,$L3,4,'锻炼','duan lian','ren luyen','tap luyen','每天锻炼身体。','Mei tian duan lian shen ti.','Tap luyen moi ngay.','verb','Tap luyen co the.',++$v3);
$v3_10=v($conn,$L3,4,'效果','xiao guo','hieu qua','hieu qua','效果很好。','Xiao guo hen hao.','Hieu qua rat tot.','noun','Ket qua.',++$v3);
$g3_1=g($conn,$L3,'Cau truc 只要...就...','只要 + DK + 就 + KQ','Chi can...la...',' dieu kien toi thieu.','只要运动就能减肥 = Chi can tap la giam can.',1);
ge($conn,$g3_1,'只要每天运动，就能保持健康。','Zhi yao mei tian yun dong, jiu neng bao chi jian kang.','Chi can tap moi ngay la giu suc khoe.',1);
ge($conn,$g3_1,'只要你坚持，就一定能成功。','Zhi yao ni jian chi, jiu yi ding neng cheng gong.','Chi can ban kien tri la nhat dinh thanh cong.',2);
$g3_2=g($conn,$L3,'Cau truc 不用 + V','不用 + V','Ko can V','Phu dinh su can thiet.','你不用减肥 = Ban ko can giam can.',2);
ge($conn,$g3_2,'其实你不用担心，你很健康。','Qi shi ni bu yong dan xin, ni hen jian kang.','Thuc ra ban ko can lo, ban rat khoe.',1);
ge($conn,$g3_2,'你不用每天都跑步，走路也可以。','Ni bu yong mei tian dou pao bu, zou lu ye ke yi.','Ban ko can chay moi ngay, di bo cung duoc.',2);
$g3_3=g($conn,$L3,'Phân biêt 胖 và 瘦','Chu the + 胖/瘦 + le','Beo / gay',' 胖 la map, 瘦 la om.','我胖了 = Toi beo len.','Beo gay.',3);
ge($conn,$g3_3,'她不是胖，是健康。','Ta bu shi pang, shi jian kang.','Co ay ko beo, la khoe.',1);
ge($conn,$g3_3,'你比以前瘦了很多。','Ni bi yi qian shou le hen duo.','Ban gay hon truoc nhieu.',2);
$d3_1=d($conn,$L3,'Co can giam can?','Noi ve giam can.',1);
ds($conn,$d3_1,'Lan','我最近越来越胖了，真担心。','Wo zui jin yue lai yue pang le, zhen dan xin.','Toi ngay cang beo, lo qua.',1);
ds($conn,$d3_1,'Minh','你看起来不胖啊。其实你不用担心。','Ni kan qi lai bu pang a. Qi shi ni bu yong dan xin.','Ban trong ko beo. Thuc ra ban ko can lo.',2);
ds($conn,$d3_1,'Lan','可是我想瘦一点。','Ke shi wo xiang shou yi dian.','Nhung toi muon gay hon.',3);
ds($conn,$d3_1,'Minh','只要多运动，少吃零食，就会有效果。','Zhi yao duo yun dong, shao chi ling shi, jiu hui you xiao guo.','Chi can tap nhieu, an it banh keo la co hieu qua.',4);
$d3_2=d($conn,$L3,'Hieu qua tap luyen','Ket qua re n luyen.',2);
ds($conn,$d3_2,'Minh','我最近开始锻炼了。','Wo zui jin kai shi duan lian le.','Toi moi bat dau tap.',1);
ds($conn,$d3_2,'Lan','效果怎么样？','Xiao guo zen me yang?','Hieu qua sao?',2);
ds($conn,$d3_2,'Minh','挺好的，体重没变但感觉更健康了。','Ting hao de, ti zhong mei bian dan gan jue geng jian kang le.','Tot, can ko doi nhung khoe hon.',3);
ds($conn,$d3_2,'Lan','运动最重要的不是减肥，而是健康。','Yun dong zui zhong yao de bu shi jian fei, er shi jian kang.','Tap quan trong ko phai giam can ma la suc khoe.',4);
$d3_3=d($conn,$L3,'Loi khuyen suc khoe','Khuyen ban.',3);
ds($conn,$d3_3,'Lan','我想减肥，有什么好方法？','Wo xiang jian fei, you shen me hao fang fa?','Toi muon giam can, co cach hay?',1);
ds($conn,$d3_3,'Minh','不用节食，只要每天运动半小时就行。','Bu yong jie shi, zhi yao mei tian yun dong ban xiao shi jiu xing.','Ko can nhip an, chi can tap nua tieng moi ngay.',2);
ds($conn,$d3_3,'Lan','跑步可以吗？','Pao bu ke yi ma?','Chay bo duoc ko?',3);
ds($conn,$d3_3,'Minh','当然可以。坚持一个月，一定有效果。','Dang ran ke yi. Jian chi yi ge yue, yi ding you xiao guo.','Duoc. Kien tri mot thang, co hieu qua.',4);
r($conn,$L3,'Ko can giam can','最近很多年轻人都想减肥。他们觉得自己太胖了，其实他们并不胖。健康比瘦更重要。如果为了减肥而不吃饭，对身体反而不好。其实只要每天坚持运动，少吃油炸食品，就能保持健康的身体。运动不一定要去健身房，走路、跑步、游泳都是很好的运动方式。我有一个朋友，她从来不减肥，但是她每天坚持走路一个小时，身体一直很健康。所以，不要过分担心体重，健康快乐才是最重要的。','Zui jin hen duo nian qing ren dou xiang jian fei. Ta men jue de zi ji tai pang le, qi shi ta men bing bu pang. Jian kang bi shou geng zhong yao. Ru guo wei le jian fei er bu chi fan, dui shen ti fan er bu hao. Qi shi zhi yao mei tian jian chi yun dong, shao chi you zha shi pin, jiu neng bao chi jian kang de shen ti. Yun dong bu yi ding yao qu jian shen fang, zou lu、pao bu、you yong dou shi hen hao de yun dong fang shi. Wo you yi ge peng you, ta cong lai bu jian fei, dan shi ta mei tian jian chi zou lu yi ge xiao shi, shen ti yi zhi hen jian kang. Suo yi, bu yao guo fen dan xin ti zhong, jian kang kuai le cai shi zui zhong yao de.','Nhieu nguoi tre muon giam can. Ho thay minh beo, nhung thuc ra ko beo. Suc khoe quan trong hon gay. Neu nhip an de giam can se hai co the. Chi can tap moi ngay, an it do chien ran la giu suc khoe. Tap ko can den phong gym, di bo, chay, boi deu tot. Toi co ban ko bao gio giam can nhung di bo moi ngay, suc khoe tot. Dung lo can nang qua, suc khoe va vui ve moi quan trong.','medium',195,1);
$L3l=l($conn,$L3,'Giam can','A: Ban hinh nhu gay hon. B: That a? Toi dang giam can. A: Lam sao? B: An it va tap nhieu. Toi chay bo moi toi, chay ngay cang nhanh. A: Hieu qua? B: Giam duoc 3kg, tu tin hon.','A: Ni zui jin hao xiang shou le. B: Shi ma? Wo zheng zai jian fei. A: Ni zen me jian? B: Shao chi duo yun dong. Wo mei tian wan shang pao bu, pao de yue lai yue kuai. A: Xiao guo zen me yang? B: Jian le san gong jin, yue lai yue you zi xin.','A: Ban hinh nhu gay hon. B: That a? Toi dang giam can. A: Lam sao? B: An it va tap nhieu. Toi chay bo moi toi, chay ngay cang nhanh. A: Hieu qua? B: Giam duoc 3kg, tu tin hon.','1');
lq($conn,$L3l,'B giam duoc bao nhieu?','{"A":"1kg","B":"3kg","C":"5kg"}','3kg','Giam 3kg.','multiple_choice',1);
lq($conn,$L3l,'B giam can bang cach nao?','{"A":"Thuoc","B":"Nhip an","C":"An it va tap nhieu"}','An it va tap nhieu','An it tap nhieu.','multiple_choice',2);
lq($conn,$L3l,'B cam thay the nao?','{"A":"Met","B":"Tu tin hon","C":"Buon"}','Tu tin hon','Ngay cang tu tin.','multiple_choice',3);
$E3_1=e($conn,$L3,'Chon dap an','"只要...就..." la?','multiple_choice','medium',1,'B',1);
eo($conn,$E3_1,'Neu...thi...','A',0,1); eo($conn,$E3_1,'Chi can...la...','B',1,2); eo($conn,$E3_1,'Du...cung...','C',0,3);
$E3_2=e($conn,$L3,'Dich','"Ban ko can giam can."','translation','medium',1,'你不用减肥。',2);
$E3_3=e($conn,$L3,'Dien tu','只___运动就能健康。','fill_blank','medium',1,'要',3);
$E3_4=e($conn,$L3,'Sap xep','只要 / 运动 / 健康 / 就能 / 保持','sentence_order','medium',1,'只要运动就能保持健康。',4);
$E3_5=e($conn,$L3,'Dung sai','"其实" la "thuc ra".','true_false','easy',1,'true',5);
eo($conn,$E3_5,'Dung','A',1,1); eo($conn,$E3_5,'Sai','B',0,2);
$E3_6=e($conn,$L3,'Dien tu','你___用担心。','fill_blank','medium',1,'不',6);
$E3_7=e($conn,$L3,'Chon dap an','"胖" trai nghia voi?','multiple_choice','medium',1,'A',7);
eo($conn,$E3_7,'瘦','A',1,1); eo($conn,$E3_7,'高','B',0,2); eo($conn,$E3_7,'矮','C',0,3);
$E3_8=e($conn,$L3,'Dien tu','健康比瘦更___要。','fill_blank','medium',1,'重',8);
$E3_9=e($conn,$L3,'Chon tu','坚持运动，____好的效果。','multiple_choice','medium',1,'C',9);
eo($conn,$E3_9,'lai','A',0,1); eo($conn,$E3_9,'co','B',0,2); eo($conn,$E3_9,'就有','C',1,3);
foreach ([$v3_1,$v3_2,$v3_3,$v3_4,$v3_5,$v3_6,$v3_7,$v3_8,$v3_9,$v3_10] as $i=>$vid) if ($vid) rv($conn,$L3,$vid,'core',$i+1);
echo " HSK4 L8 done: $v3 vocab, 3 grammar, 3 dialogues, 1 reading, 1 listening, 9 exercises\n";

$L4=createLesson($conn,4,9,'Bai 9: Ru guo ni lei le','Neu ban met. "ru guo" (neu). "xiu xi" (nghi ngoi). "fang song" (thu gian). "ya li" (ap luc).','["Met moi","Nghi ngoi","Ap luc","Thu gian"]','Thu gian','medium','HSK4 Bai 9: 如果... (neu). 休息 (nghi). 放松 (thu gian). 压力 (ap luc). 一边...一边... (vua...vua...).');
$v4=0;
$v4_1=v($conn,$L4,4,'如果','ru guo','neu','neu','如果你累了，就休息吧。','Ru guo ni lei le, jiu xiu xi ba.','Neu ban met, hay nghi ngoi.','conj','Gia dinh.',++$v4);
$v4_2=v($conn,$L4,4,'累','lei','met','met','今天很累。','Jin tian hen lei.','Hom nay met.','adj','Met moi.',++$v4);
$v4_3=v($conn,$L4,4,'休息','xiu xi','nghi ngoi','nghi','休息一下吧。','Xiu xi yi xia ba.','Nghi mot chut.','verb','Nghi.',++$v4);
$v4_4=v($conn,$L4,4,'放松','fang song','thu gian','thu gian','听音乐可以放松心情。','Ting yin yue ke yi fang song xin qing.','Nghe nhac co the thu gian tam trang.','verb','Giai tri.',++$v4);
$v4_5=v($conn,$L4,4,'压力','ya li','ap luc','ap luc','工作压力很大。','Gong zuo ya li hen da.','Ap luc cong viec lon.','noun','Ap luc.',++$v4);
$v4_6=v($conn,$L4,4,'旅游','lv you','du lich','du lich','去旅游能放松心情。','Qu lv you neng fang song xin qing.','Di du lich co the thu gian.','verb','Du lich.',++$v4);
$v4_7=v($conn,$L4,4,'音乐','yin yue','am nhac','nhac','我喜欢听音乐。','Wo xi huan ting yin yue.','Toi thich nghe nhac.','noun','Am nhac.',++$v4);
$v4_8=v($conn,$L4,4,'心情','xin qing','tam trang','tam trang','心情很好。','Xin qing hen hao.','Tam trang tot.','noun','Cam xuc.',++$v4);
$v4_9=v($conn,$L4,4,'睡眠','shui mian','giac ngu','ngu','充足的睡眠很重要。','Chong zu de shui mian hen zhong yao.','Giac ngu du rat quan trong.','noun','Ngu.',++$v4);
$v4_10=v($conn,$L4,4,'旅行','lv xing','du hanh','du lich','我喜欢旅行。','Wo xi huan lv xing.','Toi thich du lich.','verb','Di du lich.',++$v4);
$v4_11=v($conn,$L4,4,'快乐','kuai le','vui ve','vui','祝你快乐。','Zhu ni kuai le.','Chuc ban vui ve.','adj','Hanh phuc.',++$v4);
$g4_1=g($conn,$L4,'Cau truc 如果 + DK + 就 + KQ','如果 + DK + 就 + KQ','Neu...thi...','Cau dieu kien, 如果 neu len DK, 就 dan KQ.','如果累了就休息 = Neu met thi nghi.',1);
ge($conn,$g4_1,'如果你感到压力大，就去旅行吧。','Ru guo ni gan dao ya li da, jiu qu lv xing ba.','Neu ban thay ap luc lon, hay di du lich.',1);
ge($conn,$g4_1,'如果心情不好，就听听音乐。','Ru guo xin qing bu hao, jiu ting ting yin yue.','Neu buon, hay nghe nhac.',2);
$g4_2=g($conn,$L4,'Cau truc 放松 + 一下','放松 + yi xia','Thu gian mot chut',' 一下 lam hanh dong nhe nhang.','放松一下 = Thu gian mot ti.',2);
ge($conn,$g4_2,'工作累了，要适当放松一下。','Gong zuo lei le, yao shi dang fang song yi xia.','Lam met, can thu gian mot chut.',1);
ge($conn,$g4_2,'周末应该好好放松一下。','Zhou mo ying gai hao hao fang song yi xia.','Cuoi tuan nen thu gian.',2);
$g4_3=g($conn,$L4,'Cau truc 一边...一边...','一边 + V1 + 一边 + V2','Vua...vua...','Hai hanh dong song song.','一边听音乐一边跑步 = Vua nghe nhac vua chay.',3);
ge($conn,$g4_3,'我一边听音乐一边跑步。','Wo yi bian ting yin yue yi bian pao bu.','Toi vua nghe nhac vua chay bo.',1);
ge($conn,$g4_3,'一边旅行一边学习，是最好的放松方式。','Yi bian lv xing yi bian xue xi, shi zui hao de fang song fang shi.','Vua di vua hoc, la cach thu gian tot nhat.',2);
$d4_1=d($conn,$L4,'Met va ap luc','Tam su ve ap luc.',1);
ds($conn,$d4_1,'Lan','最近工作压力好大，感觉真累。','Zui jin gong zuo ya li hao da, gan jue zhen lei.','Gan day ap luc viec lon, met qua.',1);
ds($conn,$d4_1,'Minh','如果太累了，就请假休息几天。','Ru guo tai lei le, jiu qing jia xiu xi ji tian.','Neu met qua, hay nghi vai ngay.',2);
ds($conn,$d4_1,'Lan','但是还有很多工作没做完。','Dan shi hai you hen duo gong zuo mei zuo wan.','Nhung con nhieu viec chua xong.',3);
ds($conn,$d4_1,'Minh','健康最重要，适当放松一下对身体好。','Jian kang zui zhong yao, shi dang fang song yi xia dui shen ti hao.','Suc khoe quan trong nhat, thu gian tot cho co the.',4);
$d4_2=d($conn,$L4,'Cach thu gian','Cach thu gian.',2);
ds($conn,$d4_2,'Lan','你平时怎么放松？','Ni ping shi zen me fang song?','Ban thuong thu gian cach nao?',1);
ds($conn,$d4_2,'Minh','我喜欢听音乐和旅行。','Wo xi huan ting yin yue he lv xing.','Toi thich nghe nhac va du lich.',2);
ds($conn,$d4_2,'Lan','旅行确实能让人心情变好。','Lv xing que shi neng rang ren xin qing bian hao.','Du lich that lam tam trang tot hon.',3);
ds($conn,$d4_2,'Minh','对，如果心情不好，就去外面走走。','Dui, ru guo xin qing bu hao, jiu qu wai mian zou zou.','Dung, neu buon, hay ra ngoai di bo.',4);
$d4_3=d($conn,$L4,'Giac ngu','Tam su ve ngu.',3);
ds($conn,$d4_3,'Lan','我最近睡眠不好，总是睡不着。','Wo zui jin shui mian bu hao, zong shi shui bu zhao.','Gan day toi ngu ko ngon.',1);
ds($conn,$d4_3,'Minh','如果睡不着，可以喝杯热牛奶。','Ru guo shui bu zhao, ke yi he bei re niu nai.','Neu mat ngu, co the uong sua nong.',2);
ds($conn,$d4_3,'Lan','我试试。睡眠充足了，心情也会好。','Wo shi shi. Shui mian chong zu le, xin qing ye hui hao.','Toi thu. Ngu du tam trang cung tot.',3);
ds($conn,$d4_3,'Minh','对，快乐最重要。','Dui, kuai le zui zhong yao.','Dung, vui ve quan trong nhat.',4);
r($conn,$L4,'Neu ban met','现在的人生活节奏很快，工作压力也很大。如果感到累了，一定要给自己时间休息。休息不是偷懒，而是为了更好地工作。你可以听听音乐、出去旅行或者和朋友聊聊天。适当的放松能让心情变好，也能提高工作效率。充足的睡眠也很重要，如果睡眠不好，第二天就会没精神。周末的时候，不要一直待在家里，出去运动一下，呼吸新鲜空气。生活不仅要努力工作，也要学会享受快乐。','Xian zai de ren sheng huo jie zou hen kuai, gong zuo ya li ye hen da. Ru guo gan dao lei le, yi ding yao gei zi ji shi jian xiu xi. Xiu xi bu shi tou lan, er shi wei le geng hao de gong zuo. Ni ke yi ting ting yin yue、chu qu lv xing huo zhe he peng you liao liao tian. Shi dang de fang song neng rang xin qing bian hao, ye neng ti gao gong zuo xiao lv. Chong zu de shui mian ye hen zhong yao, ru guo shui mian bu hao, di er tian jiu hui mei jing shen. Zhou mo de shi hou, bu yao yi zhi dai zai jia li, chu qu yun dong yi xia, hu xi xin xian kong qi. Sheng huo bu jin yao nu li gong zuo, ye yao xue hui xiang shou kuai le.','Nguoi nay song nhanh, ap luc lon. Neu met, nho cho minh thoi gian nghi. Nghi ko phai luoi ma de lam tot hon. Co the nghe nhac, du lich, noi voi ban. Thu gian dung cach giup tam trang tot va tang hieu qua cong viec. Giac ngu du cung quan trong. Cuoi tuan dung o nha, ra ngoai tap the duc, hit thoa khi trong lanh. Song ko chi lam viec ma con huong thu niem vui.','medium',200,1);
$L4l=l($conn,$L4,'Thu gian','A: Ban trong met moi qua. B: U, ap lu c cong viec lon. A: Nen thu gian. Ban co cach nao? B: Toi thich du lich. A: Ban hay di choi cuoi tuan nay di. B: Toi cung nghi vay.','A: Ni kan qi lai hen lei. B: Shi a, gong zuo ya li hen da. A: Ni ying gai fang song yi xia. Ni you shen me hao fang fa ma? B: Wo xi huan lv xing. A: Ni zhe ge zhou mo chu qu wan ba. B: Wo ye zhe me xiang.','A: Ban trong met. B: U, ap luc viec lon. A: Nen thu gian. Ban co cach? B: Toi thich du lich. A: Cuoi tuan di choi di. B: Toi cung nghi vay.','1');
lq($conn,$L4l,'B cam thay the nao?','{"A":"Khoe","B":"Met","C":"Vui"}','Met','Met vi ap luc viec.','multiple_choice',1);
lq($conn,$L4l,'B thich thu gian cach nao?','{"A":"Doc sach","B":"Du lich","C":"Xem phim"}','Du lich','Thich du lich.','multiple_choice',2);
lq($conn,$L4l,'A khuyen B lam gi?','{"A":"O nha","B":"Cuoi tuan di choi","C":"Lam them viec"}','Cuoi tuan di choi','Hay di choi cuoi tuan.','multiple_choice',3);
$E4_1=e($conn,$L4,'Chon dap an','"如果...就..." la?','multiple_choice','medium',1,'A',1);
eo($conn,$E4_1,'Neu...thi...','A',1,1); eo($conn,$E4_1,'Vi...nen...','B',0,2); eo($conn,$E4_1,'Mac du...nhung...','C',0,3);
$E4_2=e($conn,$L4,'Dich','"Neu met, hay nghi."','translation','medium',1,'如果累了，就休息。',2);
$E4_3=e($conn,$L4,'Dien tu','如果___了，就休息。','fill_blank','medium',1,'累',3);
$E4_4=e($conn,$L4,'Sap xep','如果 / 压力 / 大 / 旅行 / 就 / 去','sentence_order','medium',1,'如果压力大，就去旅行。',4);
$E4_5=e($conn,$L4,'Dung sai','"放松" la "can thang".','true_false','easy',1,'false',5);
eo($conn,$E4_5,'Dung','A',0,1); eo($conn,$E4_5,'Sai','B',1,2);
$E4_6=e($conn,$L4,'Dien tu','放松一___对身。体好。','fill_blank','medium',1,'下',6);
$E4_7=e($conn,$L4,'Chon dap an','"一边...一边..." bieu thi?','multiple_choice','medium',1,'B',7);
eo($conn,$E4_7,'Lan luot','A',0,1); eo($conn,$E4_7,'Song song','B',1,2); eo($conn,$E4_7,'Lua chon','C',0,3);
$E4_8=e($conn,$L4,'Dien tu','他一边听音乐一___跑步。','fill_blank','medium',1,'边',8);
foreach ([$v4_1,$v4_2,$v4_3,$v4_4,$v4_5,$v4_6,$v4_7,$v4_8,$v4_9,$v4_10,$v4_11] as $i=>$vid) if ($vid) rv($conn,$L4,$vid,'core',$i+1);
echo " HSK4 L9 done: $v4 vocab, 3 grammar, 3 dialogues, 1 reading, 1 listening, 8 exercises\n";

$L5=createLesson($conn,4,10,'Bai 10: Xing fu shi shen me','Hanh phuc la gi. "xing fu", "kuai le", "man zu", "gan dong". Cau hoi + 是 + N.','["Hanh phuc","Cuoc song","Cam xuc"]','Hanh phuc','medium','HSK4 Bai 10: Hanh phuc la gi. 幸福 (hanh phuc). 快乐 (vui). 满足 (thoa man). 感动 (cam dong). Cau truc: ...是...(la...)');
$v5=0;
$v5_1=v($conn,$L5,4,'幸福','xing fu','hanh phuc','hanh phuc','幸福很简单。','Xing fu hen jian dan.','Hanh phuc rat don gian.','adj/noun','Cam giac dep.',++$v5);
$v5_2=v($conn,$L5,4,'快乐','kuai le','vui ve','vui','祝你快乐。','Zhu ni kuai le.','Chuc ban vui.','adj','Vui tuoi.',++$v5);
$v5_3=v($conn,$L5,4,'满足','man zu','thoa man','thoa man','我很满足现在的生活。','Wo hen man zu xian zai de sheng huo.','Toi thoa man voi cuoc song hien tai.','verb/adj','Hai long.',++$v5);
$v5_4=v($conn,$L5,4,'感动','gan dong','cam dong','cam dong','这个故事很感动。','Zhe ge gu shi hen gan dong.','Cau chuyen nay cam dong.','verb/adj','Xuc dong.',++$v5);
$v5_5=v($conn,$L5,4,'珍惜','zhen xi','tran trong','tran trong','珍惜身边的人。','Zhen xi shen bian de ren.','Tran trong nguoi ben canh.','verb','Quy trong.',++$v5);
$v5_6=v($conn,$L5,4,'家人','jia ren','gia dinh','nguoi nha','家人是最重要的。','Jia ren shi zui zhong yao de.','Gia dinh la quan trong nhat.','noun','Nguoi than.',++$v5);
$v5_7=v($conn,$L5,4,'拥有','yong you','co, so huu','co','拥有健康就是幸福。','Yong you jian kang jiu shi xing fu.','Co suc khoe la hanh phuc.','verb','So huu.',++$v5);
$v5_8=v($conn,$L5,4,'失去','shi qu','mat di','mat','失去后才懂得珍惜。','Shi qu hou cai dong de zhen xi.','Mat roi moi biet tran trong.','verb','Danh mat.',++$v5);
$v5_9=v($conn,$L5,4,'简单','jian dan','don gian','don gian','幸福其实很简单。','Xing fu qi shi hen jian dan.','Hanh phuc that ra don gian.','adj','Ko phuc tap.',++$v5);
$v5_10=v($conn,$L5,4,'生活','sheng huo','cuoc song','song','生活很美好。','Sheng huo hen mei hao.','Cuoc song rat dep.','noun','Doi song.',++$v5);
$v5_11=v($conn,$L5,4,'美好','mei hao','tot dep','tot dep','祝你有美好的未来。','Zhu ni you mei hao de wei lai.','Chuc ban tuong lai dep.','adj','Dep de.',++$v5);
$g5_1=g($conn,$L5,'Cau truc ...是...','A + 是 + B','A la B','Cau khang dinh voi 是.','幸福是简单 = HP la don gian.',1);
ge($conn,$g5_1,'幸福不是拥有很多，而是珍惜现在。','Xing fu bu shi yong you hen duo, er shi zhen xi xian zai.','HP ko phai co nhieu ma la tran trong hien tai.',1);
ge($conn,$g5_1,'快乐是一种心态。','Kuai le shi yi zhong xin tai.','Vui la mot tam thai.',2);
$g5_2=g($conn,$L5,'Cau truc 对...感到...','对 + N + 感到 + Adj','Cam thay ve...','Bieu thi cam xuc doi voi doi tuong.','对生活感到满足 = Thoa man voi cuoc song.',2);
ge($conn,$g5_2,'我对现在的生活感到很满足。','Wo dui xian zai de sheng huo gan dao hen man zu.','Toi cam thay thoa man voi song hien tai.',1);
ge($conn,$g5_2,'他对家人的关心感到很感动。','Ta dui jia ren de guan xin gan dao hen gan dong.','Anh ay cam dong truoc su quan tam cua gia dinh.',2);
$g5_3=g($conn,$L5,'Cau truc 只有...才... (on hon)','只有 + DK + 才 + KQ','Chi co...moi...',' dieu kien bat buoc.','只有珍惜才能拥有 = Chi tran trong moi co duoc.',3);
ge($conn,$g5_3,'只有珍惜现在，才能拥有美好的未来。','Zhi you zhen xi xian zai, cai neng yong you mei hao de wei lai.','Chi tran trong hien tai moi co tuong lai dep.',1);
ge($conn,$g5_3,'只有失去过，才知道什么是幸福。','Zhi you shi qu guo, cai zhi dao shen me shi xing fu.','Chi mat roi moi biet hanh phuc la gi.',2);
$d5_1=d($conn,$L5,'HP la gi','Ban ve HP.',1);
ds($conn,$d5_1,'Lan','你觉得幸福是什么？','Ni jue de xing fu shi shen me?','Ban nghi HP la gi?',1);
ds($conn,$d5_1,'Minh','对我来说，幸福就是和家人在一起。','Dui wo lai shuo, xing fu jiu shi he jia ren zai yi qi.','Voi toi, HP la o ben gia dinh.',2);
ds($conn,$d5_1,'Lan','我也是。有健康的身体、爱我的家人，就是幸福。','Wo ye shi. You jian kang de shen ti、ai wo de jia ren, jiu shi xing fu.','Toi cung vay. Co suc khoe, gia dinh yeu thuong la HP.',3);
ds($conn,$d5_1,'Minh','幸福其实很简单，就在我们身边。','Xing fu qi shi hen jian dan, jiu zai wo men shen bian.','HP that don gian, ngay ben canh ta.',4);
$d5_2=d($conn,$L5,'Cam on cuoc song','Loi cam on.',2);
ds($conn,$d5_2,'Lan','我最近收到了一份很感动的礼物。','Wo zui jin shou dao le yi fen hen gan dong de li wu.','Toi moi nhan mot mon qua cam dong.',1);
ds($conn,$d5_2,'Minh','是什么礼物？','Shi shen me li wu?','Qua gi vay?',2);
ds($conn,$d5_2,'Lan','是女儿亲手做的贺卡。','Shi nv er qin shou zuo de he ka.','La thiep con gai tu tay lam.',3);
ds($conn,$d5_2,'Minh','真让人感动。这就是幸福啊！','Zhen rang ren gan dong. Zhe jiu shi xing fu a!','That cam dong. Do la HP!',4);
$d5_3=d($conn,$L5,'Tran trong hien tai','Loi khuyen.',3);
ds($conn,$d5_3,'Lan','有时候我们只看到自己没有的，却忘了已经拥有的。','You shi hou wo men zhi kan dao zi ji mei you de, que wang le yi jing yong you de.','Doi khi ta chi thay minh ko co ma quen da co.',1);
ds($conn,$d5_3,'Minh','对，要学会满足和感恩。','Dui, yao xue hui man zu he gan en.','Dung, phai hoc thoa man va biet on.',2);
ds($conn,$d5_3,'Lan','珍惜身边的人，就是最大的幸福。','Zhen xi shen bian de ren, jiu shi zui da de xing fu.','Tran trong nguoi ben canh la HP lon nhat.',3);
ds($conn,$d5_3,'Minh','说得对。让我们一起珍惜现在的生活。','Shuo de dui. Rang wo men yi qi zhen xi xian zai de sheng huo.','Dung. Hay cung tran trong cuoc song hien tai.',4);
r($conn,$L5,'HP la gi','很多人都问：幸福是什么？其实幸福没有标准答案。对不同的人来说，幸福有不同的样子。对饥饿的人来说，幸福是一碗热饭；对生病的人来说，幸福是健康的身体；对孤独的人来说，幸福是家人的陪伴。其实幸福就在我们身边，只是我们有时候没有发现。每天早上醒来，看到阳光，听到鸟叫，这就是幸福。和朋友一起吃饭聊天，这也是幸福。幸福不需要很多钱，也不需要多伟大的成就。只要学会满足和感恩，每天都可以是幸福的。珍惜现在拥有的一切，你会发现幸福其实很简单。','Hen duo ren dou wen: xing fu shi shen me? Qi shi xing fu mei you biao zhun da an. Dui bu tong de ren lai shuo, xing fu you bu tong de yang zi. Dui ji e de ren lai shuo, xing fu shi yi wan re fan; dui sheng bing de ren lai shuo, xing fu shi jian kang de shen ti; dui gu du de ren lai shuo, xing fu shi jia ren de pei ban. Qi shi xing fu jiu zai wo men shen bian, zhi shi wo men you shi hou mei you fa xian. Mei tian zao shang xing lai, kan dao yang guang, ting dao niao jiao, zhe jiu shi xing fu. He peng you yi qi chi fan liao tian, zhe ye shi xing fu. Xing fu bu xu yao hen duo qian, ye bu xu yao duo wei da de cheng jiu. Zhi yao xue hui man zu he gan en, mei tian dou ke yi shi xing fu de. Zhen xi xian zai yong you de yi qie, ni hui fa xian xing fu qi shi hen jian dan.','Nhieu nguoi hoi HP la gi? Ko co dap an chuan. Voi nguoi doi, HP la bat com nong. Voi nguoi om, HP la suc khoe. Voi nguoi co don, HP la gia dinh. HP ben ta, nhung ta ko nhan ra. Sang thuc day thay nang nghe chim hot la HP. An cung ban be la HP. HP ko can nhieu tien hay thanh tuu lon. Chi can thoa man va biet on, moi ngay deu co the HP. Tran trong nhung gi co, ban se thay HP that don gian.','medium',220,1);
$L5l=l($conn,$L5,'HP','A: HP la gi? B: Voi toi, HP la duoc song vui ve. A: Ban co cam thay HP ko? B: Co. Toi co gia dinh yeu thuong va ban be tot. A: The con tien bac? B: Quan trong nhung ko phai tat ca.','A: Xing fu shi shen me? B: Dui wo lai shuo, xing fu jiu shi kuai le de sheng huo. A: Ni gan dao xing fu ma? B: Shi de. Wo you ai wo de jia ren he hao peng you. A: Na qian ne? B: Hen zhong yao, dan bu shi quan bu.','A: HP la gi? B: Voi toi, HP la song vui. A: Ban thay HP ko? B: Co. Toi co gia dinh yeu va ban tot. A: Con tien? B: Quan trong nhung ko phai tat ca.','1');
lq($conn,$L5l,'B noi HP la gi?','{"A":"Co tien","B":"Song vui","C":"Noi tieng"}','Song vui','HP la song vui ve.','multiple_choice',1);
lq($conn,$L5l,'B co HP ko?','{"A":"Khong","B":"Co","C":"Ko biet"}','Co','Co gia dinh va ban tot.','multiple_choice',2);
lq($conn,$L5l,'B nghi tien quan trong the nao?','{"A":"Tat ca","B":"Ko quan trong","C":"Quan trong nhung ko phai tat ca"}','Quan trong nhung ko phai tat ca','Quan trong nhung ko phai het.','multiple_choice',3);
$E5_1=e($conn,$L5,'Chon dap an','"幸福" la?','multiple_choice','medium',1,'A',1);
eo($conn,$E5_1,'Hanh phuc','A',1,1); eo($conn,$E5_1,'Buon','B',0,2); eo($conn,$E5_1,'Gian','C',0,3);
$E5_2=e($conn,$L5,'Dich','"HP la o ben gia dinh."','translation','medium',1,'幸福是和家人在一起。',2);
$E5_3=e($conn,$L5,'Dien tu','我___现在的生活很满足。','fill_blank','medium',1,'对',3);
$E5_4=e($conn,$L5,'Sap xep','幸福 / 简单 / 其实 / 很','sentence_order','medium',1,'幸福其实很简单。',4);
$E5_5=e($conn,$L5,'Dung sai','"珍惜" la "tran trong".','true_false','easy',1,'true',5);
eo($conn,$E5_5,'Dung','A',1,1); eo($conn,$E5_5,'Sai','B',0,2);
$E5_6=e($conn,$L5,'Dien tu','拥有健康___是幸福。','fill_blank','medium',1,'就',6);
$E5_7=e($conn,$L5,'Chon dap an','"只有...才..." la?','multiple_choice','medium',1,'B',7);
eo($conn,$E5_7,'Chi can...la...','A',0,1); eo($conn,$E5_7,'Chi...moi...','B',1,2); eo($conn,$E5_7,'Du...cung...','C',0,3);
$E5_8=e($conn,$L5,'Dien tu','Chi mat ___ moi biet tran trong.','fill_blank','medium',1,'失去',8);
$E5_9=e($conn,$L5,'Chon tu','Toi dui cuoc song hien tai cam thay ___.','multiple_choice','medium',1,'C',9);
eo($conn,$E5_9,'vui','A',0,1); eo($conn,$E5_9,'buon','B',0,2); eo($conn,$E5_9,'满 足','C',1,3);
$E5_10=e($conn,$L5,'Dien tu','___去后才懂得珍惜。','fill_blank','medium',1,'失',10);
foreach ([$v5_1,$v5_2,$v5_3,$v5_4,$v5_5,$v5_6,$v5_7,$v5_8,$v5_9,$v5_10,$v5_11] as $i=>$vid) if ($vid) rv($conn,$L5,$vid,'core',$i+1);
echo " HSK4 L10 done: $v5 vocab, 3 grammar, 3 dialogues, 1 reading, 1 listening, 10 exercises\n";

$conn->exec("SET FOREIGN_KEY_CHECKS=1");
echo "\n HSK4 Lessons 6-10 seeding complete!\n";
