<?php
require_once __DIR__ . '/seed_helpers.php';
$conn->exec("SET FOREIGN_KEY_CHECKS=0");
$L1=createLesson($conn,4,11,'Bai 11: Sheng huo ke yi geng mei hao','Cuoc song co the tot dep hon. "gai bian" (thay doi). "ti gao" (nang cao). Cau truc so sanh: "bi" (hon).','["Cuoc song","Thay doi","Cai thien"]','Cuoc song','medium','HSK4 Bai 11: Cuoc song tot hon. 改变 (thay doi). 提高 (nang cao). So sanh voi 比. Cau truc 越来越. 可以...也可以... (co the...cung co the...).');
$v1=0;
$v1_1=v($conn,$L1,4,'生活','sheng huo','cuoc song','song','生活越来越好了。','Sheng huo yue lai yue hao le.','Song ngay cang tot.','noun','Doi song.',++$v1);
$v1_2=v($conn,$L1,4,'美好','mei hao','tot dep','dep','生活很美好。','Sheng huo hen mei hao.','Cuoc song rat dep.','adj','Dep de.',++$v1);
$v1_3=v($conn,$L1,4,'改变','gai bian','thay doi','thay doi','改变生活方式。','Gai bian sheng huo fang shi.','Thay doi cach song.','verb','Bien doi.',++$v1);
$v1_4=v($conn,$L1,4,'提高','ti gao','nang cao','nang cao','提高生活质量。','Ti gao sheng huo zhi liang.','Nang cao chat luong song.','verb','Cai thien.',++$v1);
$v1_5=v($conn,$L1,4,'生活方5式','sheng huo fang shi','cach song','loi song','健康的生活方式很重要。','Jian kang de sheng huo fang shi hen zhong yao.','Cach song lanh manh quan trong.','noun','Phuong thuc song.',++$v1);
$v1_6=v($conn,$L1,4,'目标','mu biao','muc tieu','muc tieu','设定目标。','She ding mu biao.','Dat muc tieu.','noun','Muc dich.',++$v1);
$v1_7=v($conn,$L1,4,'计划','ji hua','ke hoach','ke hoach','我有一个计划。','Wo you yi ge ji hua.','Toi co mot ke hoach.','noun/verb','Ke hoach.',++$v1);
$v1_8=v($conn,$L1,4,'实现','shi xian','thuc hien','dat duoc','实现梦想。','Shi xian meng xiang.','Thuc hien uoc mo.','verb','Dat duoc.',++$v1);
$v1_9=v($conn,$L1,4,'幸福','xing fu','hanh phuc','hanh phuc','幸福的生活。','Xing fu de sheng huo.','Song hanh phuc.','adj/noun','Hanh phuc.',++$v1);
$v1_10=v($conn,$L1,4,'改变','gai bian','thay doi','thay doi','改变自己。','Gai bian zi ji.','Thay doi chinh minh.','verb','Bien doi.',++$v1);
$v1_11=v($conn,$L1,4,'未来','wei lai','tuong lai','tuong lai','未来会更美好。','Wei lai hui geng mei hao.','Tuong lai se dep hon.','noun','Tuong lai.',++$v1);
$g1_1=g($conn,$L1,'So sanh voi 比','A + 比 + B + Tinh tu','A hon B',' 比 la tu so sanh. Tinh tu khong kem 很.','生活比以前好了 = Song tot hon truoc.',1);
ge($conn,$g1_1,'现在的生活比以前好了很多。','Xian zai de sheng huo bi yi qian hao le hen duo.','Song hien tai tot hon truoc nhieu.',1);
ge($conn,$g1_2,'他的生活比我的更丰富。','Ta de sheng huo bi wo de geng feng fu.','Song cua anh ay phong phu hon toi.',2);
$g1_2=g($conn,$L1,'Cau truc 可以...也可以...','可以 + V1 + 也可以 + V2','Co the...cung co the...','Dua ra hai lua chon.','可以读书也可以旅行 = Co the doc va cung co the di.',2);
ge($conn,$g1_2,'周末可以休息，也可以出去玩儿。','Zhou mo ke yi xiu xi, ye ke yi chu qu wanr.','Cuoi tuan co the nghi, cung co the di choi.',1);
ge($conn,$g1_2,'生活可以很简单，也可以很精彩。','Sheng huo ke yi hen jian dan, ye ke yi hen jing cai.','Song co the don gian, cung co the tuc.','精彩','2');
$g1_3=g($conn,$L1,'Cau truc 为了实现...','为了实现 + Muc tieu + V','De thuc hien...',' 为了 chi muc dich, 实现 chi su dat duoc.','为了实现梦想而努力学习 = De dat uoc mo ma hoc.','Muc tieu.',3);
ge($conn,$g1_3,'为了实现目标，他每天都很努力。','Wei le shi xian mu biao, ta mei tian dou hen nu li.','De dat muc tieu, anh ay moi ngay co gang.',1);
ge($conn,$g1_3,'为了实现美好的生活，我们要改变自己。','Wei le shi xian mei hao de sheng huo, wo men yao gai bian zi ji.','De co cuoc song dep, ta phai thay doi.',2);
$d1_1=d($conn,$L1,'Cai thien cuoc song','Lam song tot hon.',1);
ds($conn,$d1_1,'Lan','你觉得怎样才能让生活更美好？','Ni jue de zen yang cai neng rang sheng huo geng mei hao?','Ban nghi lam sao de song tot hon?',1);
ds($conn,$d1_1,'Minh','我觉得要有目标和计划。','Wo jue de yao you mu biao he ji hua.','Toi nghi can co muc tieu va ke hoach.',2);
ds($conn,$d1_1,'Lan','对，实现目标会让人感到幸福。','Dui, shi xian mu biao hui rang ren gan dao xing fu.','Dung, dat muc tieu lam ta thay HP.',3);
ds($conn,$d1_1,'Minh','而且要保持积极的态度。','Er qie yao bao chi ji ji de tai du.','Va phai giu thai do tich cuc.',4);
$d1_2=d($conn,$L1,'Thay doi ban than','Thay doi de tot hon.',2);
ds($conn,$d1_2,'Lan','我想改变自己，但是不知道从哪里开始。','Wo xiang gai bian zi ji, dan shi bu zhi dao cong na li kai shi.','Toi muon thay doi, nhung ko biet bat dau tu dau.',1);
ds($conn,$d1_2,'Minh','可以从小的习惯开始改变。','Ke yi cong xiao de xi guan kai shi gai bian.','Co the bat dau tu thoi quen nho.',2);
ds($conn,$d1_2,'Lan','比如每天读书半小时？','Bi ru mei tian du shu ban xiao shi?','Nhu moi ngay doc sach nua tieng?',3);
ds($conn,$d1_2,'Minh','对，坚持下来，生活就会不一样。','Dui, jian chi xia lai, sheng huo jiu hui bu yi yang.','Dung, kien tri roi song se khac.',4);
$d1_3=d($conn,$L1,'Tuong lai tot dep','Ve tuong lai.',3);
ds($conn,$d1_3,'Lan','你对未来有什么计划？','Ni dui wei lai you shen me ji hua?','Ban co ke hoach gi cho tuong lai?',1);
ds($conn,$d1_3,'Minh','我计划去中国留学，提高汉语水平。','Wo ji hua qu Zhong guo liu xue, ti gao Han yu shui ping.','Toi du dinh du hoc TQ, nang cao trinh do.',2);
ds($conn,$d1_3,'Lan','很棒的理想！相信你一定能实现。','Hen bang de li xiang! Xiang xin ni yi ding neng shi xian.','Ly tuong tuyet! Tin ban se dat duoc.',3);
ds($conn,$d1_3,'Minh','谢谢。只要努力，未来会更美好。','Xie xie. Zhi yao nu li, wei lai hui geng mei hao.','Cam on. Chi can co gang, tuong lai se dep hon.',4);
r($conn,$L1,'Song tot dep hon','每个人都希望自己的生活越来越美好。但是美好的生活不是等来的，而是靠自己的努力去创造的。首先，我们要有一个明确的目标。有了目标，就有了方向。其次，要制定计划，一步一步地实现它。在实现目标的过程中，我们会遇到困难，但只要不放弃，就一定能成功。同时，我们也要学会改变自己，改掉坏习惯，养成好习惯。比如每天早睡早起、多读书、多运动。生活可以很简单，也可以很精彩。只要我们用心去生活，未来一定会更加美好。','Mei ge ren dou xi wang zi ji de sheng huo yue lai yue mei hao. Dan shi mei hao de sheng huo bu shi deng lai de, er shi kao zi ji de nu li qu chuang zao de. Shou xian, wo men yao you yi ge ming que de mu biao. You le mu biao, jiu you le fang xiang. Qi ci, yao zhi ding ji hua, yi bu yi bu di shi xian ta. Zai shi xian mu biao de guo cheng zhong, wo men hui yu dao kun nan, dan zhi yao bu fang qi, jiu yi ding neng cheng gong. Tong shi, wo men ye yao xue hui gai bian zi ji, gai diao huai xi guan, yang cheng hao xi guan. Bi ru mei tian zao shui zao qi、duo du shu、duo yun dong. Sheng huo ke yi hen jian dan, ye ke yi hen jing cai. Zhi yao wo men yong xin qu sheng huo, wei lai yi ding hui geng jia mei hao.','Ai cung muon song ngay cang tot. Song dep ko phai doi ma tu tao ra. Dau tien can muc tieu ro rang. Tiep theo, ke hoach tuong buoc thuc hien. Se co kho khan, nhung ko bo cuoc se thanh cong. Cung can thay doi, bo thoi quen xau, tao thoi quen tot. Nhu ngu som day som, doc sach, tap the duc. Song co the don gian hay tuc. Chi can song bang ca trai tim, tuong lai se dep.','medium',210,1);
$L1l=l($conn,$L1,'Thay doi','A: Ban muon cai thien cuoc song the nao? B: Toi muon thay doi thoi quen. A: Thoi quen gi? B: Thuc day som va doc nhieu sach hon. A: Tot day! Kien tri nhe.','A: Ni xiang zen me gai bian sheng huo? B: Wo xiang gai bian xi guan. A: Shen me xi guan? B: Zao qi he du geng duo de shu. A: Hen hao! Jian chi a.','A: Ban muon cai thien song the nao? B: Toi muon thay doi thoi quen. A: Thoi quen gi? B: Day som va doc nhieu sach. A: Tot! Kien tri nhe.','1');
lq($conn,$L1l,'B muon thay doi gi?','{"A":"Cong viec","B":"Thoi quen","C":"Ban be"}','Thoi quen','Muon thay doi thoi quen.','multiple_choice',1);
lq($conn,$L1l,'B muon thay doi thoi quen nao?','{"A":"An nhieu","B":"Day som va doc sach","C":"Xem TV"}','Day som va doc sach','Day som va doc sach.','multiple_choice',2);
lq($conn,$L1l,'A khuyen B gi?','{"A":"Bo cuoc","B":"Kien tri","C":"Lam khac"}','Kien tri','Kien tri nhe.','multiple_choice',3);
$E1_1=e($conn,$L1,'Chon dap an','"比" la tu so sanh?','multiple_choice','medium',1,'A',1);
eo($conn,$E1_1,'Dung','A',1,1); eo($conn,$E1_1,'Sai','B',0,2);
$E1_2=e($conn,$L1,'Dich','"Song hien tai tot hon truoc."','translation','medium',1,'现在的生活比以前好了。',2);
$E1_3=e($conn,$L1,'Dien tu','生活越来___好。','fill_blank','medium',1,'越',3);
$E1_4=e($conn,$L1,'Sap xep','可以 / 休息 / 周末 / 也 / 可以 / 出去 / 玩儿','sentence_order','medium',1,'周末可以休息，也可以出去玩儿。',4);
$E1_5=e($conn,$L1,'Dung sai','"目标" la "muc tieu".','true_false','easy',1,'true',5);
eo($conn,$E1_5,'Dung','A',1,1); eo($conn,$E1_5,'Sai','B',0,2);
$E1_6=e($conn,$L1,'Dien tu','为___实现梦想而努力。','fill_blank','medium',1,'了',6);
$E1_7=e($conn,$L1,'Chon dap an','Cau nao dung?','multiple_choice','medium',1,'C',7);
eo($conn,$E1_7,'我比他高很。','A',0,1); eo($conn,$E1_7,'我很比他高。','B',0,2); eo($conn,$E1_7,'我比他高很多。','C',1,3);
$E1_8=e($conn,$L1,'Dien tu','周末可以休息，也可以出去___。','fill_blank','medium',1,'玩儿',8);
$E1_9=e($conn,$L1,'Chon tu','___ muc tieu, anh ay moi ngay co gang.','multiple_choice','medium',1,'B',9);
eo($conn,$E1_9,'Wei le dat','A',0,1); eo($conn,$E1_9,'为了实现','B',1,2); eo($conn,$E1_9,'Da dat','C',0,3);
foreach ([$v1_1,$v1_2,$v1_3,$v1_4,$v1_5,$v1_6,$v1_7,$v1_8,$v1_9,$v1_10,$v1_11] as $i=>$vid) if ($vid) rv($conn,$L1,$vid,'core',$i+1);
echo " HSK4 L11 done: $v1 vocab, 3 grammar, 3 dialogues, 1 reading, 1 listening, 9 exercises\n";

$L2=createLesson($conn,4,12,'Bai 12: Yong ji ji de xin tai qu sheng huo','Song voi thai do tich cuc. "ji ji" (tich cuc). "xin tai" (tam thai). "tai du" (thai do). "bu guan...dou..." (bat ke...deu...).','["Tich cuc","Tam thai","Thai do song"]','Tam ly','medium','HSK4 Bai 12: Song tich cuc. 积极 (tich cuc). 心态 (tam thai). 态度 (thai do). 不管...都... (bat ke...deu...). 从...来看 (tu...ma xet).');
$v2=0;
$v2_1=v($conn,$L2,4,'积极','ji ji','tich cuc','tich cuc','积极面对生活。','Ji ji mian dui sheng huo.','Tich cuc doi dien voi song.','adj','Chu dong.',++$v2);
$v2_2=v($conn,$L2,4,'心态','xin tai','tam thai','tam ly','心态很重要。','Xin tai hen zhong yao.','Tam thai quan trong.','noun','Thai do tam ly.',++$v2);
$v2_3=v($conn,$L2,4,'态度','tai du','thai do','thai do','学习态度要认真。','Xue xi tai du yao ren zhen.','Thai do hoc phai nghiem tuc.','noun','Cach nhin nhan.',++$v2);
$v2_4=v($conn,$L2,4,'不管','bu guan','bat ke','mac ke','不管多难，我都不会放弃。','Bu guan duo nan, wo dou bu hui fang qi.','Bat ke kho, toi ko bo.','conj','Thuong dung voi 都.',++$v2);
$v2_5=v($conn,$L2,4,'乐观','le guan','lac quan','lac quan','他性格很乐观。','Ta xing ge hen le guan.','Anh ay tinh cach lac quan.','adj','Vui ve.',++$v2);
$v2_6=v($conn,$L2,4,'困难','kun nan','kho khan','kho','遇到困难不要怕。','Yu dao kun nan bu yao pa.','Gap kho dung so.','noun/adj','Kho khan.',++$v2);
$v2_7=v($conn,$L2,4,'面对','mian dui','doi dien','doi mat','勇敢面对挑战。','Yong gan mian dui tiao zhan.','Dung cam doi dien thai thach.','verb','Doi mat.',++$v2);
$v2_8=v($conn,$L2,4,'信心','xin xin','niem tin','tu tin','要有信心。','Yao you xin xin.','Can co niem tin.','noun','Su tin tuong.',++$v2);
$v2_9=v($conn,$L2,4,'勇敢','yong gan','dung cam','dan cam','勇敢面对一切。','Yong gan mian dui yi qie.','Dung cam doi dien moi thu.','adj','Gan da.',++$v2);
$v2_10=v($conn,$L2,4,'成功','cheng gong','thanh cong','thanh cong','努力就会成功。','Nu li jiu hui cheng gong.','Co gang se thanh cong.','verb/noun','Dat duoc.',++$v2);
$v2_11=v($conn,$L2,4,'失败','shi bai','that bai','that bai','失败是成功之母。','Shi bai shi cheng gong zhi mu.','That bai la me thanh cong.','verb/noun','Ko thanh cong.',++$v2);
$g2_1=g($conn,$L2,'Cau truc 不管...都...','不管 + (ai/gi/tn) + 都 + V','Bat ke...deu...',' 不管 + tu nghi van + 都. 不管多难、不管谁、不管什么.','不管多难都坚持 = Bat ke kho deu kien tri.',1);
ge($conn,$g2_1,'不管遇到什么困难，都要积极面对。','Bu guan yu dao shen me kun nan, dou yao ji ji mian dui.','Bat ke gap kho gi, deu phai tich cuc doi dien.',1);
ge($conn,$g2_2,'不管别人怎么说，我相信自己。','Bu guan bie ren zen me shuo, wo xiang xin zi ji.','Bat ke nguoi ta noi gi, toi tin minh.',2);
$g2_2=g($conn,$L2,'Cau truc 从...来看','从 + Goc nhin + 来看','Tu...ma xet','Dua ra danh gia tu goc nhin nao do.','从心态来看，他很乐观 = Tu tam thai, anh ay lac quan.',2);
ge($conn,$g2_2,'从态度来看，他是一个很认真的人。','Cong tai du lai kan, ta shi yi ge hen ren zhen de ren.','Tu thai do, anh ay la nguoi nghiem tuc.',1);
ge($conn,$g2_2,'从这次失败来看，我们需要改变方法。','Cong zhe ci shi bai lai kan, wo men xu yao gai bian fang fa.','Tu that bai nay, ta can doi phuong phap.',2);
$g2_3=g($conn,$L2,'Cau truc 只要...就... (nhac lai)','只要 + DK + 就 + KQ','Chi can...la...',' dieu kien toi thieu dan den ket qua.','只要有信心，就能成功 = Chi co tin la thanh cong.',3);
ge($conn,$g2_3,'只要有积极的心态，生活就会更美好。','Zhi yao you ji ji de xin tai, sheng huo jiu hui geng mei hao.','Chi co tam thai tich cuc, song se dep hon.',1);
ge($conn,$g2_3,'只要不放弃，就还有机会。','Zhi yao bu fang qi, jiu hai you ji hui.','Chi can ko bo cuoc, con co hoi.',2);
$d2_1=d($conn,$L2,'Tam thai tich cuc','Noi ve tam thai.',1);
ds($conn,$d2_1,'Lan','你心态真好，不管遇到什么事都能开心。','Ni xin tai zhen hao, bu guan yu dao shen me shi dou neng kai xin.','Ban tam thai tot, gap gi cung vui.',1);
ds($conn,$d2_1,'Minh','我觉得生活已经很美好了，要学会感恩。','Wo jue de sheng huo yi jing hen mei hao le, yao xue hui gan en.','Toi thay song dep roi, phai biet on.',2);
ds($conn,$d2_1,'Lan','但是有时候我总想不好的事情。','Dan shi you shi hou wo zong xiang bu hao de shi qing.','Nhung toi hay nghi chuyen ko hay.',3);
ds($conn,$d2_1,'Minh','试试从积极的角度看问题。','Shi shi cong ji ji de jiao du kan wen ti.','Hay thu nhin tu goc tich cuc.',4);
$d2_2=d($conn,$L2,'Vuot qua kho khan','Vuot kho.',2);
ds($conn,$d2_2,'Lan','最近工作遇到了很多困难。','Zui jin gong zuo yu dao le hen duo kun nan.','Gan day viec gap nhieu kho khan.',1);
ds($conn,$d2_2,'Minh','不管多困难，勇敢面对就好。','Bu guan duo kun nan, yong gan mian dui jiu hao.','Bat ke kho may, dung cam doi dien.',2);
ds($conn,$d2_2,'Lan','你说得对。只要有信心，就能解决。','Ni shuo de dui. Zhi yao you xin xin, jiu neng jie jue.','Ban dung. Chi can tu tin, se giai quyet.',3);
ds($conn,$d2_2,'Minh','对，失败不可怕，怕的是不敢面对。','Dui, shi bai bu ke pa, pa de shi bu gan mian dui.','That bai ko dang so, so la ko dam doi dien.',4);
$d2_3=d($conn,$L2,'Thanh cong','Noi ve thanh cong.',3);
ds($conn,$d2_3,'Lan','你觉得成功最重要的是什么？','Ni jue de cheng gong zui zhong yao de shi shen me?','Ban nghi thanh cong can nhat gi?',1);
ds($conn,$d2_3,'Minh','态度。不管能力怎么样，态度决定一切。','Tai du. Bu guan neng li zen me yang, tai du jue ding yi qie.','Thai do. Bat ke nang luc, thai do quyet dinh.',2);
ds($conn,$d2_3,'Lan','说得好。从今天开始，我要改变态度。','Shuo de hao. Cong jin tian kai shi, wo yao gai bian tai du.','Noi hay. Tu nay toi se doi thai do.',3);
ds($conn,$d2_3,'Minh','加油！积极的心态会带来成功。','Jia you! Ji ji de xin tai hui dai lai cheng gong.','Co len! Tam thai tich cuc se mang lai thanh cong.',4);
r($conn,$L2,'Song tich cuc','生活中有很多不确定的事情。有时候我们会遇到困难，有时候会失败。但是不管发生什么，我们都要保持积极的心态。心态决定了我们看问题的方式。同样一件事情，乐观的人看到的是机会，悲观的人看到的是困难。从心态来看，积极的人更容易成功。因为他们不管遇到什么困难，都会想办法解决，而不是放弃。如果你现在觉得生活不如意，不妨试着改变一下自己的心态。从积极的角度看问题，你会发现世界其实很美好。只要有信心，有勇气，就没有过不去的坎。','Sheng huo zhong you hen duo bu que ding de shi qing. You shi hou wo men hui yu dao kun nan, you shi hou hui shi bai. Dan shi bu guan fa sheng shen me, wo men dou yao bao chi ji ji de xin tai. Xin tai jue ding le wo men kan wen ti de fang shi. Tong yang yi jian shi qing, le guan de ren kan dao de shi ji hui, bei guan de ren kan dao de shi kun nan. Cong xin tai lai kan, ji ji de ren geng rong yi cheng gong. Yin wei ta men bu guan yu dao shen me kun nan, dou hui xiang ban fa jie jue, er bu shi fang qi. Ru guo ni xian zai jue de sheng huo bu ru yi, bu fang shi zhe gai bian yi xia zi ji de xin tai. Cong ji ji de jiao du kan wen ti, ni hui fa xian shi jie qi shi hen mei hao. Zhi yao you xin xin, you yong qi, jiu mei you guo bu qu de kan.','Song co nhieu bat dinh. Doi luc gap kho, that bai. Nhung bat ke gi, giu tam thai tich cuc. Tam thai quyet dinh cach ta nhin van de. Cung mot viec, lac quan thay co hoi, bi quan thay kho khan. Nguoi tich cuc de thanh cong hon vi ho tim giai phap thay vi bo cuoc. Neu ban thay song ko nhu y, hay thu doi tam thai. Nhin tu goc tich cuc, ban se thay the gioi dep. Chi can tin va dung cam, ko gi ko qua duoc.','medium',220,1);
$L2l=l($conn,$L2,'Tam thai','A: Ban hinh nhu luon vui. B: Vi toi co tam thai tich cuc. A: Co bi that bai bao gio ko? B: Co, nhung ko bo cuoc. Toi nhin that bai la bai hoc. A: Ban song lac quan that. B: Song vui se tot hon.','A: Ni hao xiang zong shi hen kai xin. B: Yin wei wo you ji ji de xin tai. A: Ni you shi bai guo ma? B: You, dan wo bu fang qi. Wo ba shi bai kan cheng xue xi. A: Ni zhen le guan. B: Kuai le de sheng huo geng hao.','A: Ban luon vui. B: Vi toi co tam thai tich cuc. A: Co that bai ko? B: Co, nhung ko bo. Toi xem that bai la bai hoc. A: Ban lac quan that. B: Song vui se tot hon.','1');
lq($conn,$L2l,'Tai sao B luon vui?','{"A":"Co tien","B":"Tam thai tich cuc","C":"Ko co viec"}','Tam thai tich cuc','Vi co tam thai tich cuc.','multiple_choice',1);
lq($conn,$L2l,'B nhin that bai the nao?','{"A":"Rat so","B":"La bai hoc","C":"Ko quan tam"}','La bai hoc','Xem that bai la bai hoc.','multiple_choice',2);
lq($conn,$L2l,'A nhan xet B the nao?','{"A":"Bi quan","B":"Lac quan","C":"Binh thuong"}','Lac quan','Lac quan that.','multiple_choice',3);
$E2_1=e($conn,$L2,'Chon dap an','"不管...都..." la?','multiple_choice','medium',1,'B',1);
eo($conn,$E2_1,'Vi...nen...','A',0,1); eo($conn,$E2_1,'Bat ke...deu...','B',1,2); eo($conn,$E2_1,'Neu...thi...','C',0,3);
$E2_2=e($conn,$L2,'Dich','"Bat ke gi, deu tich cuc doi dien."','translation','medium',1,'不管什么，都要积极面对。',2);
$E2_3=e($conn,$L2,'Dien tu','不管___困难，都要坚持。','fill_blank','medium',1,'什么',3);
$E2_4=e($conn,$L2,'Sap xep','不管 / 多难 / 放弃 / 不 / 我 / 都','sentence_order','medium',1,'不管多难，我都不放弃。',4);
$E2_5=e($conn,$L2,'Dung sai','"心态" la "tam thai".','true_false','easy',1,'true',5);
eo($conn,$E2_5,'Dung','A',1,1); eo($conn,$E2_5,'Sai','B',0,2);
$E2_6=e($conn,$L2,'Dien tu','从心态来___, anh ay lac quan.','fill_blank','medium',1,'看',6);
$E2_7=e($conn,$L2,'Chon dap an','"积极" trai nghia voi?','multiple_choice','medium',1,'C',7);
eo($conn,$E2_7,'Chu dong','A',0,1); eo($conn,$E2_7,'No luc','B',0,2); eo($conn,$E2_7,'Tieu cuc','C',1,3);
$E2_8=e($conn,$L2,'Dien tu','Chung ta can co ___. (niem tin)','fill_blank','medium',1,'信心',8);
foreach ([$v2_1,$v2_2,$v2_3,$v2_4,$v2_5,$v2_6,$v2_7,$v2_8,$v2_9,$v2_10,$v2_11] as $i=>$vid) if ($vid) rv($conn,$L2,$vid,'core',$i+1);
echo " HSK4 L12 done: $v2 vocab, 3 grammar, 3 dialogues, 1 reading, 1 listening, 8 exercises\n";

$L3=createLesson($conn,4,13,'Bai 13: Cong xian zai kai shi','Tu bay gio bat dau. "kai shi" (bat dau). "jian chi" (kien tri). "xi guan" (thoi quen). "mu biao" (muc tieu).','["Bat dau","Kien tri","Thoi quen","Muc tieu"]','Phat trien','medium','HSK4 Bai 13: Bat dau tu nay. 开始 (bat dau). 坚持 (kien tri). 习惯 (thoi quen). 目标 (muc tieu). 从...开始 (tu...bat dau).');
$v3=0;
$v3_1=v($conn,$L3,4,'开始','kai shi','bat dau','bat dau','从今天开始。','Cong jin tian kai shi.','Tu hom nay bat dau.','verb','Bat dau.',++$v3);
$v3_2=v($conn,$L3,4,'坚持','jian chi','kien tri','kien tri','坚持下去。','Jian chi xia qu.','Kien tri tiep.','verb','Ko bo cuoc.',++$v3);
$v3_3=v($conn,$L3,4,'习惯','xi guan','thoi quen','thoi quen','养成好习惯。','Yang cheng hao xi guan.','Tao thoi quen tot.','noun','Thoi quen.',++$v3);
$v3_4=v($conn,$L3,4,'目标','mu biao','muc tieu','muc tieu','设定目标。','She ding mu biao.','Dat muc tieu.','noun','Muc dich.',++$v3);
$v3_5=v($conn,$L3,4,'计划','ji hua','ke hoach','ke hoach','制定计划。','Zhi ding ji hua.','Lap ke hoach.','noun/verb','Ke hoach.',++$v3);
$v3_6=v($conn,$L3,4,'努力','nu li','co gang','co gang','努力学习。','Nu li xue xi.','Co gang hoc tap.','verb/adv','No luc.',++$v3);
$v3_7=v($conn,$L3,4,'成功','cheng gong','thanh cong','thanh cong','祝你成功。','Zhu ni cheng gong.','Chuc thanh cong.','verb/noun','Dat duoc.',++$v3);
$v3_8=v($conn,$L3,4,'时间','shi jian','thoi gian','thoi gian','珍惜时间。','Zhen xi shi jian.','Tran trong thoi gian.','noun','Thoi gian.',++$v3);
$v3_9=v($conn,$L3,4,'改变','gai bian','thay doi','thay doi','改变从现在开始。','Gai bian cong xian zai kai shi.','Thay doi tu bay gio.','verb','Bien doi.',++$v3);
$v3_10=v($conn,$L3,4,'未来','wei lai','tuong lai','tuong lai','创造美好未来。','Chuang zao mei hao wei lai.','Tao tuong lai dep.','noun','Tuong lai.',++$v3);
$g3_1=g($conn,$L3,'Cau truc 从...开始','从 + Thoi gian/Dia diem + 开始','Tu...bat dau','Chi diem xuat phat.','从今天开始 = Tu hom nay bat dau.',1);
ge($conn,$g3_1,'从今天开始，我要每天读书。','Cong jin tian kai shi, wo yao mei tian du shu.','Tu hom nay, toi se doc sach moi ngay.',1);
ge($conn,$g3_2,'改变从生活中的小事开始。','Gai bian cong sheng huo zhong de xiao shi kai shi.','Thay doi tu viec nho trong song.',2);
$g3_2=g($conn,$L3,'Cau truc 坚持 + V + 下去','坚持 + V + 下去','Kien tri lam tiep',' 下去 chi tiep tuc hanh dong.','坚持下去 = Kien tri tiep.',2);
ge($conn,$g3_2,'只要坚持下去，就一定能成功。','Zhi yao jian chi xia qu, jiu yi ding neng cheng gong.','Chi can kien tri, se thanh cong.',1);
ge($conn,$g3_2,'不管多难，我都要坚持下去。','Bu guan duo nan, wo dou yao jian chi xia qu.','Bat ke kho, toi phai kien tri.',2);
$g3_3=g($conn,$L3,'Cau truc 从...到... (thoi gian)','从 + T1 + 到 + T2','Tu...den...','Chi pham vi thoi gian.','从早到晚 = Tu sang den toi.',3);
ge($conn,$g3_3,'从今天到周末，我要完成这个计划。','Cong jin tian dao zhou mo, wo yao wan cheng zhe ge ji hua.','Tu nay den cuoi tuan, toi se hoan thanh ke hoach.',1);
ge($conn,$g3_3,'他从开始到结束都很认真。','Ta cong kai shi dao jie shu dou hen ren zhen.','Anh ay tu dau den cuoi deu nghiem tuc.',2);
$d3_1=d($conn,$L3,'Bat dau tu nay','Noi ve viec bat dau.',1);
ds($conn,$d3_1,'Lan','我决定从今天开始减肥。','Wo jue ding cong jin tian kai shi jian fei.','Toi quyet dinh tu nay giam can.',1);
ds($conn,$d3_1,'Minh','好！坚持就是胜利。','Hao! Jian chi jiu shi sheng li.','Tot! Kien tri la thang loi.',2);
ds($conn,$d3_1,'Lan','但是我不知道能不能坚持。','Dan shi wo bu zhi dao neng bu neng jian chi.','Nhung toi ko biet co kien tri noi ko.',3);
ds($conn,$d3_1,'Minh','从每天运动半小时开始，慢慢来。','Cong mei tian yun dong ban xiao shi kai shi, man man lai.','Bat dau tu tap nua tieng moi ngay.',4);
$d3_2=d($conn,$L3,'Ke hoach tuong lai','Ke hoach tuong lai.',2);
ds($conn,$d3_2,'Lan','你对未来有什么计划？','Ni dui wei lai you shen me ji hua?','Ban co ke hoach gi cho tuong lai?',1);
ds($conn,$d3_2,'Minh','我计划三年内学好汉语。','Wo ji hua san nian nei xue hao Han yu.','Toi du dinh 3 nam hoc tot tieng Trung.',2);
ds($conn,$d3_2,'Lan','目标很大，需要坚持努力。','Mu biao hen da, xu yao jian chi nu li.','Muc tieu lon, can kien tri.',3);
ds($conn,$d3_2,'Minh','是的，我从现在开始每天学习。','Shi de, wo cong xian zai kai shi mei tian xue xi.','Vang, toi tu nay moi ngay hoc.',4);
$d3_3=d($conn,$L3,'Thoi quen tot','Hinh thanh thoi quen.',3);
ds($conn,$d3_3,'Lan','怎样才能养成好习惯？','Zen yang cai neng yang cheng hao xi guan?','Lam sao de tao thoi quen tot?',1);
ds($conn,$d3_3,'Minh','从每天坚持做一件小事开始。','Cong mei tian jian chi zuo yi jian xiao shi kai shi.','Tu kien tri lam mot viec nho moi ngay.',2);
ds($conn,$d3_3,'Lan','比如？','Bi ru?','Vi du?',3);
ds($conn,$d3_3,'Minh','比如每天早起十分钟。','Bi ru mei tian zao qi shi fen zhong.','Nhu moi ngay day som 10 phut.',4);
ds($conn,$d3_3,'Lan','这个我可以试试。','Zhe ge wo ke yi shi shi.','Cai nay toi co the thu.',5);
r($conn,$L3,'Bat dau tu nay','很多人总是说"明天开始"，但"明天"永远不会来。如果你想做一件事，最好的时间就是现在。不要等到明天，不要等到以后。从现在开始，一个小小的改变，坚持一段时间，就会变成习惯。习惯养成了，生活就会不一样。比如你想学汉语，从每天记五个单词开始。你想减肥，从每天走一万步开始。你想读书，从每天读十页开始。只要开始做了，就已经成功了一半。记住：不管什么时候开始，都不算晚。重要的是开始之后，能不能坚持下去。从今天开始，行动起来吧！','Hen duo ren zong shi shuo "ming tian kai shi", dan "ming tian" yong yuan bu hui lai. Ru guo ni xiang zuo yi jian shi, zui hao de shi jian jiu shi xian zai. Bu yao deng dao ming tian, bu yao deng dao yi hou. Cong xian zai kai shi, yi ge xiao xiao de gai bian, jian chi yi duan shi jian, jiu hui bian cheng xi guan. Xi guan yang cheng le, sheng huo jiu hui bu yi yang. Bi ru ni xiang xue Han yu, cong mei tian ji wu ge dan ci kai shi. Ni xiang jian fei, cong mei tian zou yi wan bu kai shi. Ni xiang du shu, cong mei tian du shi ye kai shi. Zhi yao kai shi zuo le, jiu yi jing cheng gong le yi ban. Ji zhu: bu guan shen me shi hou kai shi, dou bu suan wan. Zhong yao de shi kai shi zhi hou, neng bu neng jian chi xia qu. Cong jin tian kai shi, xing dong qi lai ba!','Nhieu nguoi noi "mai mai bat dau". Nhung "mai" se ko bao gio den. Muon lam gi, thoi gian tot nhat la bay gio. Tu bay gio, mot thay doi nho, kien tri se thanh thoi quen. Thoi quen tao ra, song se khac. Muon hoc tieng Trung, tu hoc 5 tu moi ngay. Muon giam can, tu di 1 van buoc. Muon doc sach, tu doc 10 trang. Chi can bat dau la da thanh cong mot nua. Nho: bat dau luc nao cung ko muon. Quan trong la sau do co kien tri ko. Tu hom nay, hay hanh dong!','medium',215,1);
$L3l=l($conn,$L3,'Bat dau','A: Ban dinh bat dau hoc tieng Trung? B: Toi muon nhung chua bat dau. A: Tai sao? B: Toi so minh hoc ko duoc. A: Dung so. Co gang tu tu, kien tri la duoc. B: Vay toi se bat dau tu hom nay.','A: Ni da suan kai shi xue Han yu ma? B: Wo xiang dan hai mei kai shi. A: Wei shen me? B: Wo pa xue bu hao. A: Bie pa. Man man lai, jian chi jiu xing. B: Hao, wo cong jin tian kai shi.','A: Ban dinh bat dau hoc tieng Trung? B: Toi muon nhung chua bat dau. A: Tai sao? B: Toi so hoc ko duoc. A: Dung so. Tu tu kien tri. B: Vay toi bat dau tu nay.','1');
lq($conn,$L3l,'B da bat dau hoc tieng Trung chua?','{"A":"Roi","B":"Chua","C":"Dang hoc"}','Chua','Chua bat dau.','multiple_choice',1);
lq($conn,$L3l,'Tai sao B chua bat dau?','{"A":"Ban","B":"So hoc ko duoc","C":"Ko thich"}','So hoc ko duoc','So minh hoc ko duoc.','multiple_choice',2);
lq($conn,$L3l,'Cuoi cung B quyet the nao?','{"A":"Ko hoc","B":"Bat dau tu nay","C":"Cho mai"}','Bat dau tu nay','Se bat dau tu hom nay.','multiple_choice',3);
$E3_1=e($conn,$L3,'Chon dap an','"从...开始" la?','multiple_choice','medium',1,'C',1);
eo($conn,$E3_1,'Tu...den...','A',0,1); eo($conn,$E3_1,'Tu...ra...','B',0,2); eo($conn,$E3_1,'Tu...bat dau','C',1,3);
$E3_2=e($conn,$L3,'Dich','"Tu hom nay bat dau."','translation','medium',1,'从今天开始。',2);
$E3_3=e($conn,$L3,'Dien tu','从今天___始。','fill_blank','medium',1,'开',3);
$E3_4=e($conn,$L3,'Sap xep','坚持 / 下去 / 只要 / 就能 / 成功','sentence_order','medium',1,'只要坚持下去就能成功。',4);
$E3_5=e($conn,$L3,'Dung sai','"坚持" la "kien tri".','true_false','easy',1,'true',5);
eo($conn,$E3_5,'Dung','A',1,1); eo($conn,$E3_5,'Sai','B',0,2);
$E3_6=e($conn,$L3,'Dien tu','Cong xian zai ___ shi.','fill_blank','medium',1,'开始',6);
$E3_7=e($conn,$L3,'Chon dap an','"从...到..." chi?','multiple_choice','medium',1,'B',7);
eo($conn,$E3_7,'Dia diem','A',0,1); eo($conn,$E3_7,'Thoi gian','B',1,2); eo($conn,$E3_7,'Nguyen nhan','C',0,3);
$E3_8=e($conn,$L3,'Dien tu','___ cheng hao xi guan.','fill_blank','medium',1,'养成',8);
$E3_9=e($conn,$L3,'Chon tu','___ muon lam gi, thoi gian tot nhat la bay gio.','multiple_choice','medium',1,'A',9);
eo($conn,$E3_9,'Neu','A',1,1); eo($conn,$E3_9,'Vi','B',0,2); eo($conn,$E3_9,'Cho du','C',0,3);
foreach ([$v3_1,$v3_2,$v3_3,$v3_4,$v3_5,$v3_6,$v3_7,$v3_8,$v3_9,$v3_10] as $i=>$vid) if ($vid) rv($conn,$L3,$vid,'core',$i+1);
echo " HSK4 L13 done: $v3 vocab, 3 grammar, 3 dialogues, 1 reading, 1 listening, 9 exercises\n";

$L4=createLesson($conn,4,14,'Bai 14: Bao hu huan jing','Bao ve moi truong. "huan jing" (moi truong). "bao hu" (bao ve). "wu ran" (o nhiem). "jie yue" (tiet kiem).','["Moi truong","Bao ve","O nhiem","Tiet kiem"]','Moi truong','medium','HSK4 Bai 14: Bao ve moi truong. 环境 (moi truong). 保护 (bao ve). 污染 (o nhiem). 节约 (tiet kiem). Cau truc: 如果...就... (neu...thi...).');
$v4=0;
$v4_1=v($conn,$L4,4,'环境','huan jing','moi truong','moi truong','保护环境。','Bao hu huan jing.','Bao ve moi truong.','noun','Moi truong xq.',++$v4);
$v4_2=v($conn,$L4,4,'保护','bao hu','bao ve','bao ve','保护大自然。','Bao hu da zi ran.','Bao ve tu nhien.','verb','Bao ve.',++$v4);
$v4_3=v($conn,$L4,4,'污染','wu ran','o nhiem','ban','空气污染很严重。','Kong qi wu ran hen yan zhong.','O nhiem ko khi nghiem trong.','noun/verb','Lam ban.',++$v4);
$v4_4=v($conn,$L4,4,'节约','jie yue','tiet kiem','tiet kiem','节约用水。','Jie yue yong shui.','Tiet kiem nuoc.','verb','Tien kiem.',++$v4);
$v4_5=v($conn,$L4,4,'垃圾','la ji','rac','rac','垃圾分类。','La ji fen lei.','Phan loai rac.','noun','Rac thai.',++$v4);
$v4_6=v($conn,$L4,4,'浪费','lang fei','lang phi','phi','不要浪费粮食。','Bu yao lang fei liang shi.','Dung phi thuc pham.','verb','Lang phi.',++$v4);
$v4_7=v($conn,$L4,4,'绿色','lv se','mau xanh','xanh','绿色出行。','Lv se chu xing.','Di lai xanh.','adj','Mau xanh la.',++$v4);
$v4_8=v($conn,$L4,4,'空气','kong qi','khong khi','khong khi','新鲜空气。','Xin xian kong qi.','Khong khi trong lanh.','noun','Không khi.',++$v4);
$v4_9=v($conn,$L4,4,'环保','huan bao','bao ve moi truong','bao ve MT','环保人人有责。','Huan bao ren ren you ze.','Bao ve MT ai cung co trach nhiem.','noun/adj','Bao ve moi truong.',++$v4);
$v4_10=v($conn,$L4,4,'地球','di qiu','trai dat','trai dat','保护地球。','Bao hu di qiu.','Bao ve trai dat.','noun','Trai dat.',++$v4);
$v4_11=v($conn,$L4,4,'能源','neng yuan','nang luong','nang luong','节约能源。','Jie yue neng yuan.','Tiet kiem nang luong.','noun','Nguon nang luong.',++$v4);
$g4_1=g($conn,$L4,'Cau truc 如果...就... (bao ve)','如果 + DK + 就 + KQ','Neu...thi...','Ap dung cho bao ve moi truong.','如果人人环保，环境就会更好 = Neu ai cung BVMT, MT se tot hon.',1);
ge($conn,$g4_1,'如果我们不保护环境，地球就会被污染。','Ru guo wo men bu bao hu huan jing, di qiu jiu hui bei wu ran.','Neu ta ko BVMT, trai dat se bi o nhiem.',1);
ge($conn,$g4_2,'如果每个人都节约用水，就能保护水资源。','Ru guo mei ge ren dou jie yue yong shui, jiu neng bao hu shui zi yuan.','Neu ai cung tiet kiem nuoc, se BV duoc tai nguyen nuoc.',2);
$g4_2=g($conn,$L4,'Cau truc 被 trong bao ve MT','Subject + 被 + V','Bi lam gi',' 被 cho cau bi dong.','环境被污染了 = MT bi o nhiem.',2);
ge($conn,$g4_2,'空气被污染了。','Kong qi bei wu ran le.','Khong khi bi o nhiem.',1);
ge($conn,$g4_2,'垃圾应该被分类。','La ji ying gai bei fen lei.','Rac nen duoc phan loai.',2);
$g4_3=g($conn,$L4,'Cau truc phu dinh 不要','不要 + V','Dung/ko nen','Khuyen cao ko nen lam gi.','不要浪费水 = Dung phi nuoc.',3);
ge($conn,$g4_3,'不要乱扔垃圾。','Bu yao luan reng la ji.','Dung xac rac bay ba.',1);
ge($conn,$g4_3,'不要浪费粮食，要节约。','Bu yao lang fei liang shi, yao jie yue.','Dung phi thuc an, hay tiet kiem.',2);
$d4_1=d($conn,$L4,'Bao ve moi truong','Noi ve MT.',1);
ds($conn,$d4_1,'Lan','你觉得环境问题严重吗？','Ni jue de huan jing wen ti yan zhong ma?','Ban thay van de MT nghiem trong ko?',1);
ds($conn,$d4_1,'Minh','很严重。空气污染越来越厉害了。','Hen yan zhong. Kong qi wu ran yue lai yue li hai le.','Rat nghiem. O nhiem ko khi ngay cang nang.',2);
ds($conn,$d4_1,'Lan','我们每个人都应该为环保出一份力。','Wo men mei ge ren dou ying gai wei huan bao chu yi fen li.','Moi nguoi nen gop suc cho BVMT.',3);
ds($conn,$d4_1,'Minh','对，从身边的小事做起。','Dui, cong shen bian de xiao shi zuo qi.','Dung, tu viec nho xung quanh.',4);
$d4_2=d($conn,$L4,'Tiet kiem','Noi ve tiet kiem.',2);
ds($conn,$d4_2,'Lan','你有什么节约能源的好方法？','Ni you shen me jie yue neng yuan de hao fang fa?','Ban co cach tiet kiem nang luong hay?',1);
ds($conn,$d4_2,'Minh','出门时关灯，用环保袋。','Chu men shi guan deng, yong huan bao dai.','Ra ngoai tat den, dung tui BVMT.',2);
ds($conn,$d4_2,'Lan','还有吗？','Hai you ma?','Con nua?',3);
ds($conn,$d4_2,'Minh','少用一次性筷子，多坐公交车。','Shao yong yi ci xing kuai zi, duo zuo gong jiao che.','It dung dua mot lan, di xe buyt nhieu.',4);
$d4_3=d($conn,$L4,'Phan loai rac','Phan loai rac.',3);
ds($conn,$d4_3,'Lan','你们那里垃圾分类了吗？','Ni men na li la ji fen lei le ma?','Ben ban da phan loai rac chua?',1);
ds($conn,$d4_3,'Minh','已经开始分类了。每个小区都有分类垃圾桶。','Yi jing kai shi fen lei le. Mei ge xiao qu dou you fen lei la ji tong.','Da bat dau phan loai. Khu nao cung co thung rac phan loai.',2);
ds($conn,$d4_3,'Lan','这样很好，垃圾被分类后更容易处理。','Zhe yang hen hao, la ji bei fen lei hou geng rong yi chu li.','Tot, rac phan loai de xu ly hon.',3);
ds($conn,$d4_3,'Minh','对，环保需要大家一起努力。','Dui, huan bao xu yao da jia yi qi nu li.','Dung, BVMT can ca cong dong co gang.',4);
r($conn,$L4,'Bao ve trai dat','地球是我们的家，保护环境是每个人的责任。但是现在环境污染越来越严重。空气被污染了，水被污染了，垃圾也越来越多了。如果我们不采取行动，地球将会变得越来越不适合居住。那么，我们能为环保做什么呢？其实很简单：节约用水、用电；少用一次性物品；垃圾分类；多坐公共交通。这些小事看起来不起眼，但是如果每个人都做到，环境就会慢慢变好。不要等到环境被彻底破坏了才后悔。从现在开始，让我们一起保护我们唯一的地球吧！','Di qiu shi wo men de jia, bao hu huan jing shi mei ge ren de ze ren. Dan shi xian zai huan jing wu ran yue lai yue yan zhong. Kong qi bei wu ran le, shui bei wu ran le, la ji ye yue lai yue duo le. Ru guo wo men bu cai qu xing dong, di qiu jiang hui bian de yue lai yue bu shi he ju zhu. Na me, wo men neng wei huan bao zuo shen me ne? Qi shi hen jian dan: jie yue yong shui、yong dian; shao yong yi ci xing wu pin; la ji fen lei; duo zuo gong jiao jiao tong. Zhe xie xiao shi kan qi lai bu qi yan, dan shi ru guo mei ge ren dou zuo dao, huan jing jiu hui man man bian hao. Bu yao deng dao huan jing bei che di po huai le cai hou hui. Cong xian zai kai shi, rang wo men yi qi bao hu wo men wei yi de di qiu ba!','Trai Dat la nha chung ta, BVMT la trach nhiem moi nguoi. Nhung o nhiem ngay cang nghiem trong. Ko khi bi ban, nuoc bi ban, rac ngay cang nhieu. Neu ko hanh dong, Trai Dat se ko con o duoc. Ta co the lam gi? Don gian: tiet kiem nuoc, dien; it dung do mot lan; phan loai rac; di xe buyt. Viec nho ko dang ke, nhung neu ai cung lam, MT se tot dan. Dung cho den luc MT bi pha huy roi moi hoi. Tu nay, hay cung BV Trai Dat duy nhat cua chung ta!','medium',220,1);
$L4l=l($conn,$L4,'Bao ve MT','A: Ban co thoi quen BVMT ko? B: Co. Toi phan loai rac va tiet kiem dien. A: Tot qua! Con nua ko? B: Toi di lam bang xe buyt thay vi xe hoi. A: Tai sao? B: Vi xe buyt it gay o nhiem hon.','A: Ni you bao hu huan jing de xi guan ma? B: You. Wo la ji fen lei he jie yue yong dian. A: Zhen hao! Hai you ma? B: Wo zuo gong jiao che shang ban, er bu shi kai che. A: Wei shen me? B: Yin wei gong jiao che wu ran shao.','A: Ban co thoi quen BVMT ko? B: Co. Toi phan loai rac va tiet kiem dien. A: Tot! Con nua? B: Toi di lam bang xe buyt thay vi xe hoi. A: Tai sao? B: Vi xe buyt it gay o nhiem hon.','1');
lq($conn,$L4l,'B co thoi quen BVMT?','{"A":"Khong","B":"Co","C":"Mot chut"}','Co','Phan loai rac va tiet kiem dien.','multiple_choice',1);
lq($conn,$L4l,'B di lam bang gi?','{"A":"Xe hoi","B":"Xe buyt","C":"Xe dap"}','Xe buyt','Di xe buyt.','multiple_choice',2);
lq($conn,$L4l,'Sao B chon xe buyt?','{"A":"Re","B":"Nhanh","C":"It gay o nhiem"}','It gay o nhiem','Xe buyt it gay o nhiem.','multiple_choice',3);
$E4_1=e($conn,$L4,'Chon dap an','"污染" la?','multiple_choice','medium',1,'A',1);
eo($conn,$E4_1,'O nhiem','A',1,1); eo($conn,$E4_1,'Sach','B',0,2); eo($conn,$E4_1,'Dep','C',0,3);
$E4_2=e($conn,$L4,'Dich','"Dung xac rac bay ba."','translation','medium',1,'不要乱扔垃圾。',2);
$E4_3=e($conn,$L4,'Dien tu','Bao___huan jing.','fill_blank','medium',1,'护',3);
$E4_4=e($conn,$L4,'Sap xep','不要 / 垃圾 / 乱扔','sentence_order','medium',1,'不要乱扔垃圾。',4);
$E4_5=e($conn,$L4,'Dung sai','"节约" la "tiet kiem".','true_false','easy',1,'true',5);
eo($conn,$E4_5,'Dung','A',1,1); eo($conn,$E4_5,'Sai','B',0,2);
$E4_6=e($conn,$L4,'Dien tu','Khong khi bi wu ___ le.','fill_blank','medium',1,'污染',6);
$E4_7=e($conn,$L4,'Chon dap an','"被" dung de?','multiple_choice','medium',1,'B',7);
eo($conn,$E4_7,'Cau chu dong','A',0,1); eo($conn,$E4_7,'Cau bi dong','B',1,2); eo($conn,$E4_7,'Cau nghiv an','C',0,3);
$E4_8=e($conn,$L4,'Dien tu','___保护地球。','fill_blank','medium',1,'一起',8);
foreach ([$v4_1,$v4_2,$v4_3,$v4_4,$v4_5,$v4_6,$v4_7,$v4_8,$v4_9,$v4_10,$v4_11] as $i=>$vid) if ($vid) rv($conn,$L4,$vid,'core',$i+1);
echo " HSK4 L14 done: $v4 vocab, 3 grammar, 3 dialogues, 1 reading, 1 listening, 8 exercises\n";

$L5=createLesson($conn,4,15,'Bai 15: Jiao yu hai zi','Giao duc con cai. "jiao yu" (giao duc). "hai zi" (tre). "fang shi" (cach thuc). "li jie" (thau hieu). Cau truc: "ying gai" (nen). "bu yao" (dung).','["Giao duc","Con cai","Phuong phap","Thau hieu"]','Gia dinh','medium','HSK4 Bai 15: Day con. 教育 (giao duc). 方式 (cach). 理解 (hieu). 应该+ V (nen). Cau truc khuyen bao: 要/不要. Cach noi ve viec nuoi day con.');
$v5=0;
$v5_1=v($conn,$L5,4,'教育','jiao yu','giao duc','giao duc','教育孩子要有耐心。','Jiao yu hai zi yao you nai xin.','Day con can kien nhan.','noun','Su day do.',++$v5);
$v5_2=v($conn,$L5,4,'孩子','hai zi','con, tre em','con','孩子需要关爱。','Hai zi xu yao guan ai.','Tre can yeu thuong.','noun','Tre nho.',++$v5);
$v5_3=v($conn,$L5,4,'方式','fang shi','cach thuc','cach','教育方式很重要。','Jiao yu fang shi hen zhong yao.','Cach giao duc quan trong.','noun','Phuong thuc.',++$v5);
$v5_4=v($conn,$L5,4,'理解','li jie','thau hieu','hieu','理解孩子的想法。','Li jie hai zi de xiang fa.','Thau hieu suy nghi cua tre.','verb','Hieu ro.',++$v5);
$v5_5=v($conn,$L5,4,'沟通','gou tong','giao tiep','truyen thong','多和孩子沟通。','Duo he hai zi gou tong.','Nhieu giao tiep voi con.','verb','Trao doi.',++$v5);
$v5_6=v($conn,$L5,4,'尊重','zun zhong','ton trong','ton trong','尊重孩子的选择。','Zun zhong hai zi de xuan ze.','Ton trong lua chon cua tre.','verb','Ton trong.',++$v5);
$v5_7=v($conn,$L5,4,'鼓励','gu li','khuyen khich','khuyen','鼓励孩子尝试。','Gu li hai zi chang shi.','Khuyen tre thu.','verb','Dong vien.',++$v5);
$v5_8=v($conn,$L5,4,'批评','pi ping','phe binh','che','不要总批评孩子。','Bu yao zong pi ping hai zi.','Dung cu phe binh tre.','verb','Che trach.',++$v5);
$v5_9=v($conn,$L5,4,'自觉','zi jue','tu giac','tu giac','孩子要自觉学习。','Hai zi yao zi jue xue xi.','Tre phai tu giac hoc.','adj','Chu dong.',++$v5);
$v5_10=v($conn,$L5,4,'成长','cheng zhang','truong thanh','lon','孩子在快乐中成长。','Hai zi zai kuai le zhong cheng zhang.','Tre lon trong vui ve.','verb','Phat trien.',++$v5);
$v5_11=v($conn,$L5,4,'未来','wei lai','tuong lai','tuong lai','教育影响孩子的未来。','Jiao yu ying xiang hai zi de wei lai.','Giao duc anh huong tuong lai tre.','noun','Tuong lai.',++$v5);
$g5_1=g($conn,$L5,'Cau truc 要/不要 + V','要/不要 + V','Nen/Dung lam gi',' 要 chi nen lam, 不要 chi dung lam.','要尊重孩子 = Nen ton trong tre.','Khuyen bao.',1);
ge($conn,$g5_1,'要尊重孩子的想法。','Yao zun zhong hai zi de xiang fa.','Nen ton trong suy nghi cua tre.',1);
ge($conn,$g5_2,'不要总是批评孩子，要多鼓励。','Bu yao zong shi pi ping hai zi, yao duo gu li.','Dung cu phe binh tre, hay da khuyen.',2);
$g5_2=g($conn,$L5,'Cau truc 多/少 + V','多/少 + V','Nhieu/It lam gi',' 多 va 少 chi tan suat.','多沟通 = Giao tiep nhieu.',2);
ge($conn,$g5_2,'多和孩子沟通，了解他们的想法。','Duo he hai zi gou tong, liao jie ta men de xiang fa.','Nhieu giao tiep voi tre, hieu suy nghi cua chung.',1);
ge($conn,$g5_2,'少批评，多鼓励，孩子会更自信。','Shao pi ping, duo gu li, hai zi hui geng zi xin.','It phe binh, nhieu khuyen khich, tre se tu tin hon.',2);
$g5_3=g($conn,$L5,'Cau truc 在...中 + V','在 + MOi truong + 中 + V','Trong...V...','Chi moi truong cua hanh dong.','在快乐中成长 = Lon trong vui ve.',3);
ge($conn,$g5_3,'孩子应该在快乐中成长。','Hai zi ying gai zai kuai le zhong cheng zhang.','Tre nen lon len trong niem vui.',1);
ge($conn,$g5_3,'在鼓励中长大的孩子更自信。','Zai gu li zhong zhang da de hai zi geng zi xin.','Tre lon trong khuyen khich se tu tin hon.',2);
$d5_1=d($conn,$L5,'Cach day con','Cach day con tot.',1);
ds($conn,$d5_1,'Lan','你觉得怎么教育孩子最好？','Ni jue de zen me jiao yu hai zi zui hao?','Ban nghi day con the nao tot nhat?',1);
ds($conn,$d5_1,'Minh','多理解，少批评。要尊重孩子的想法。','Duo li jie, shao pi ping. Yao zun zhong hai zi de xiang fa.','Nhieu thau hieu, it phe binh. Ton trong y tre.',2);
ds($conn,$d5_1,'Lan','但是如果孩子做错了也不说吗？','Dan shi ru guo hai zi zuo cuo le ye bu shuo ma?','Nhung neu tre sai cung ko noi a?',3);
ds($conn,$d5_1,'Minh','可以说，但要注意语气和方式。','Ke yi shuo, dan yao zhu yi yu qi he fang shi.','Co the noi, nhung chu y giong dieu va cach.',4);
$d5_2=d($conn,$L5,'Giao tiep voi con','Giao tiep voi tre.',2);
ds($conn,$d5_2,'Lan','你每天和你的孩子沟通吗？','Ni mei tian he ni de hai zi gou tong ma?','Ban moi ngay giao tiep voi con ko?',1);
ds($conn,$d5_2,'Minh','当然。每天晚饭时，我们都会聊聊学校的事。','Dang ran. Mei tian wan fan shi, wo men dou hui liao liao xue xiao de shi.','Duong nhien. Buoi toi, chung toi noi chuyen ve truong.',2);
ds($conn,$d5_2,'Lan','这个习惯很好。沟通能增进感情。','Zhe ge xi guan hen hao. Gou tong neng zeng jin gan qing.','Thoi quen tot. Giao tiep tang tinh cam.',3);
ds($conn,$d5_2,'Minh','对，而且能了解孩子的想法。','Dui, er qie neng liao jie hai zi de xiang fa.','Va biet duoc suy nghi cua tre.',4);
$d5_3=d($conn,$L5,'Tuong lai con','Ve tuong lai con.',3);
ds($conn,$d5_3,'Lan','你对孩子的未来有什么期望？','Ni dui hai zi de wei lai you shen me qi wang?','Ban ky vong gi ve tuong lai con?',1);
ds($conn,$d5_3,'Minh','我只希望他健康快乐地成长。','Wo zhi xi wang ta jian kang kuai le di cheng zhang.','Toi chi mong con lon khoe va vui.',2);
ds($conn,$d5_3,'Lan','说得好。最重要的不是成绩，而是品格。','Shuo de hao. Zui zhong yao de bu shi cheng ji, er shi pin ge.','Noi hay. Quan trong ko phai diem ma la pham chat.',3);
ds($conn,$d5_3,'Minh','对，教育的目标是让孩子成为善良的人。','Dui, jiao yu de mu biao shi rang hai zi cheng wei shan liang de ren.','Dung, muc tieu giao duc la de con thanh nguoi tot.',4);
r($conn,$L5,'Day con the nao','教育孩子是每个父母都要面对的重要问题。每个孩子都是独特的，所以教育方式也应该不同。首先，父母要多理解孩子，了解他们的想法和感受。其次，要多鼓励，少批评。批评太多会让孩子失去信心。好的教育不是打骂，而是沟通和引导。父母应该尊重孩子的选择，让他们学会独立思考。同时，也要让孩子明白什么是正确的，什么是错误的。在爱和规则中长大的孩子，会更自信、更善良。教育的目标不是让孩子变成父母想要的样子，而是帮助他们成为最好的自己。','Jiao yu hai zi shi mei ge fu mu dou yao mian dui de zhong yao wen ti. Mei ge hai zi dou shi du te de, suo yi jiao yu fang shi ye ying gai bu tong. Shou xian, fu mu yao duo li jie hai zi, liao jie ta men de xiang fa he gan shou. Qi ci, yao duo gu li, shao pi ping. Pi ping tai duo hui rang hai zi shi qu xin xin. Hao de jiao yu bu shi da ma, er shi gou tong he yin dao. Fu mu ying gai zun zhong hai zi de xuan ze, rang ta men xue hui du li si kao. Tong shi, ye yao rang hai zi ming bai shen me shi zheng que de, shen me shi cuo wu de. Zai ai he gui ze zhong zhang da de hai zi, hui geng zi xin, geng shan liang. Jiao yu de mu biao bu shi rang hai zi bian cheng fu mu xiang yao de yang zi, er shi bang zhu ta men cheng wei zui hao de zi ji.','Day con la van de moi cha me phai doi mat. Moi tre la doc nhat, can cach day khac nhau. Truoc het, cha me can thau hieu tre. Tiep theo, nhieu khuyen khich, it phe binh. Phe binh nhieu khien tre mat tu tin. Giao duc tot ko phai danh ma la giao tiep va huong dan. Cha me nen ton trong lua chon cua tre, de tu hoc tu duy. Cung can cho tre biet dung sai. Lon trong tinh yeu va ky luat, tre se tu tin va tot bung hon. Muc tieu giao duc ko phai de tre thanh nguoi cha me muon, ma de chung tro nen phien ban tot nhat cua chinh minh.','medium',230,1);
$L5l=l($conn,$L5,'Day con','A: Ban co con ko? B: Co, toi co mot be trai 5 tuoi. A: Ban day con the nao? B: Toi co gang nhieu khuyen khich, it phe binh. A: Tot day. Con ban tu giac hoc chua? B: Dang dan dan hinh thanh thoi quen.','A: Ni you hai zi ma? B: You, wo you yi ge wu sui de er zi. A: Ni zen me jiao yu ta? B: Wo duo gu li, shao pi ping. A: Hen hao. Ta zi jue ma? B: Zheng zai man man xing cheng xi guan.','A: Ban co con ko? B: Co, be trai 5 tuoi. A: Ban day the nao? B: Toi nhieu khuyen khich, it phe binh. A: Tot. Con tu giac chua? B: Dang dan hinh thanh thoi quen.','1');
lq($conn,$L5l,'B co con bao nhieu tuoi?','{"A":"3 tuoi","B":"5 tuoi","C":"7 tuoi"}','5 tuoi','Be trai 5 tuoi.','multiple_choice',1);
lq($conn,$L5l,'B day con bang cach nao?','{"A":"Nghiem khac","B":"Nhieu khuyen khich","C":"Mac ke"}','Nhieu khuyen khich','Nhieu khuyen khich, it phe binh.','multiple_choice',2);
lq($conn,$L5l,'Con B co tu giac chua?','{"A":"Roi","B":"Dang hinh thanh","C":"Chua"}','Dang hinh thanh','Dang dan hinh thanh thoi quen.','multiple_choice',3);
$E5_1=e($conn,$L5,'Chon dap an','"不要" dung de?','multiple_choice','medium',1,'B',1);
eo($conn,$E5_1,'Khuyen nen lam','A',0,1); eo($conn,$E5_1,'Khuyen dung lam','B',1,2); eo($conn,$E5_1,'Men h lenh','C',0,3);
$E5_2=e($conn,$L5,'Dich','"Nen ton trong y cua tre."','translation','medium',1,'要尊重孩子的想法。',2);
$E5_3=e($conn,$L5,'Dien tu','要尊重孩子的选___。','fill_blank','medium',1,'择',3);
$E5_4=e($conn,$L5,'Sap xep','不要 / 批评 / 总是 / 孩子','sentence_order','medium',1,'不要总是批评孩子。',4);
$E5_5=e($conn,$L5,'Dung sai','"沟通" la "giao tiep".','true_false','easy',1,'true',5);
eo($conn,$E5_5,'Dung','A',1,1); eo($conn,$E5_5,'Sai','B',0,2);
$E5_6=e($conn,$L5,'Dien tu','duo gou tong, shao pi ___.','fill_blank','medium',1,'评',6);
$E5_7=e($conn,$L5,'Chon dap an','"在...中" chi?','multiple_choice','medium',1,'C',7);
eo($conn,$E5_7,'Dia diem','A',0,1); eo($conn,$E5_7,'Thoi gian','B',0,2); eo($conn,$E5_7,'Moi truong','C',1,3);
$E5_8=e($conn,$L5,'Dien tu','在___中成长。','fill_blank','medium',1,'快乐',8);
$E5_9=e($conn,$L5,'Chon tu','Giao duc de tre thanh ___ tot nhat cua chinh minh.','multiple_choice','medium',1,'C',9);
eo($conn,$E5_9,'minh','A',0,1); eo($conn,$E5_9,'ban than','B',0,2); eo($conn,$E5_9,'自己','C',1,3);
$E5_10=e($conn,$L5,'Dien tu','Zun zhong hai zi de xuan ___.','fill_blank','medium',1,'择',10);
foreach ([$v5_1,$v5_2,$v5_3,$v5_4,$v5_5,$v5_6,$v5_7,$v5_8,$v5_9,$v5_10,$v5_11] as $i=>$vid) if ($vid) rv($conn,$L5,$vid,'core',$i+1);
echo " HSK4 L15 done: $v5 vocab, 3 grammar, 3 dialogues, 1 reading, 1 listening, 10 exercises\n";

$conn->exec("SET FOREIGN_KEY_CHECKS=1");
echo "\n HSK4 Lessons 11-15 seeding complete!\n";
