<?php
require_once __DIR__ . '/seed_helpers.php';
$conn->exec("SET FOREIGN_KEY_CHECKS=0");
$L21=createLesson($conn,4,21,'Bai 21: Bao hu wo men de jia yuan','Bao ve moi truong. Cau truc "zai...fang mian" (ve phuong dien). "fou ze" (neu khong). "dui yu" (doi voi). "sui zhe" (cung voi).','["Bao ve moi truong","Thien nhien","Phat trien ben vung"]','Moi truong','medium','HSK4 Bai 21: Tu vung ve moi truong. 在...方面 (ve phuong dien). 否则 (neu khong). 对于 (doi voi). 随着 (cung voi).');
$v21=0;
$v21_1=v($conn,$L21,4,'保护','bao hu','bao ve','bao ve','我们要保护环境。','Wo men yao bao hu huan jing.','Chung ta phai bao ve moi truong.','verb','Gin giu.',++$v21);
$v21_2=v($conn,$L21,4,'地球','di qiu','trai dat','trai dat','地球是我们的家园。','Di qiu shi wo men de jia yuan.','Trai dat la ngoi nha cua chung ta.','noun','Hanh tinh.',++$v21);
$v21_3=v($conn,$L21,4,'环境','huan jing','moi truong','moi truong','保护环境人人有责。','Bao hu huan jing ren ren you ze.','Bao ve moi truong ai cung co trach nhiem.','noun','Moi truong xung quanh.',++$v21);
$v21_4=v($conn,$L21,4,'绿色','lv se','mau xanh la','xanh','绿色出行很环保。','Lv se chu xing hen huan bao.','Di lai xanh la bao ve moi truong.','noun','Bao ve moi truong.',++$v21);
$v21_5=v($conn,$L21,4,'减少','jian shao','giam bot','giam','减少浪费。','Jian shao lang fei.','Giam bot lang phi.','verb','Lam it di.',++$v21);
$v21_6=v($conn,$L21,4,'污染','wu ran','o nhiem','o nhiem','空气污染很严重。','Kong qi wu ran hen yan zhong.','O nhiem khong khi rat nghiem trong.','noun/verb','Lam ban.',++$v21);
$v21_7=v($conn,$L21,4,'节约','jie yue','tiet kiem','tiet kiem','节约用水。','Jie yue yong shui.','Tiet kiem nuoc.','verb','Tiet kiem tai nguyen.',++$v21);
$v21_8=v($conn,$L21,4,'垃圾','la ji','rac thai','rac','垃圾分类很重要。','La ji fen lei hen zhong yao.','Phan loai rac rat quan trong.','noun','Chat thai.',++$v21);
$v21_9=v($conn,$L21,4,'回收','hui shou','thu hoi','thu hoi','回收利用。','Hui shou li yong.','Tai che su dung.','verb','Tai su dung.',++$v21);
$v21_10=v($conn,$L21,4,'能源','neng yuan','nang luong','nang luong','节约能源。','Jie yue neng yuan.','Tiet kiem nang luong.','noun','Tai nguyen nang luong.',++$v21);
$v21_11=v($conn,$L21,4,'空气','kong qi','khong khi','khong khi','新鲜空气。','Xin xian kong qi.','Khong khi trong lanh.','noun','Khi quyen.',++$v21);
$g21_1=g($conn,$L21,'Cau truc 在...方面','在 + Danh tu + 方面','Ve phuong dien / Trong linh vuc','在...方面 neu ro linh vuc dang noi toi. Thuong dung sau chu ngu hoac dau cau.','在环保方面，我们可以做得更好 = Trong BVMT, ta co the lam tot hon.','Phuong dien.',1);
ge($conn,$g21_1,'在保护环境方面，我们应该从身边的小事做起。','Zai bao hu huan jing fang mian, wo men ying gai cong shen bian de xiao shi zuo qi.','Trong bao ve moi truong, ta nen bat dau tu viec nho xung quanh.',1);
ge($conn,$g21_1,'在减少污染方面，每个人都可以出一份力。','Zai jian shao wu ran fang mian, mei ge ren dou ke yi chu yi fen li.','Trong viec giam o nhiem, moi nguoi deu co the gop suc.',2);
$g21_2=g($conn,$L21,'Cau truc 否则','DK + Ket qua + 否则 + DK phu','Neu khong / bang khong','否则 (fou ze) mang y dieu kien nguoc lai. Neu khong lam DK thi se co KQ khong mong muon.','早点出发，否则会迟到 = Di som, ko se tre.','Dieu kien nguoc.',2);
ge($conn,$g21_2,'我们应该减少使用塑料袋，否则环境污染会更严重。','Wo men ying gai jian shao shi yong su liao dai, fou ze huan jing wu ran hui geng yan zhong.','Ta nen giam dung tui nilon, neu khong o nhiem se nghiem trong hon.',1);
ge($conn,$g21_2,'请把垃圾扔进垃圾桶，否则会影响环境。','Qing ba la ji reng jin la ji tong, fou ze hui ying xiang huan jing.','Hay bo rac vao thung, neu ko se anh huong moi truong.',2);
$g21_3=g($conn,$L21,'Cau truc 对于','对于 + DT + (lai) shuo / ma noi','Doi voi','对于 dat doi tuong cua nhan xet. Thuong dung 对于...来说.','对于我来说，环保很重要 = Voi toi BVMT quan trong.','Doi tuong.',3);
ge($conn,$g21_3,'对于现代社会来说，环保已经成为每个人的责任。','Dui yu xian dai she hui lai shuo, huan bao yi jing cheng wei mei ge ren de ze ren.','Doi voi XH hien dai, BVMT da la trach nhiem cua moi nguoi.',1);
ge($conn,$g21_3,'对于垃圾分类，我们应该认真学习。','Dui yu la ji fen lei, wo men ying gai ren zhen xue xi.','Ve phan loai rac, ta nen hoc tap nghiem tuc.',2);
$g21_4=g($conn,$L21,'Cau truc 随着','随着 + N + V, Ket qua','Cung voi / Theo','随着 chi su thay doi di kem. Thuong dung dau cau.','随着科技发展，生活越来越方便 = Cung voi KHKT phat trien.','Dong hanh.',4);
ge($conn,$g21_4,'随着经济的发展，环境问题也越来越严重。','Sui zhe jing ji de fa zhan, huan jing wen ti ye yue lai yue yan zhong.','Cung voi KT phat trien, van de moi truong cang nghiem trong.',1);
ge($conn,$g21_4,'随着人们环保意识的提高，越来越多的人选择绿色出行。','Sui zhe ren men huan bao yi shi de ti gao, yue lai yue duo de ren xuan ze lv se chu xing.','Cung voi y thuc BVMT nang cao, nhieu nguoi chon di lai xanh.',2);
$d21_1=d($conn,$L21,'Bao ve moi truong','Noi ve bao ve moi truong.',1);
ds($conn,$d21_1,'Lan','你觉得我们现在最应该做什么来保护环境？','Ni jue de wo men xian zai zui ying gai zuo shen me lai bao hu huan jing?','Ban nghi ta nen lam gi de BVMT?',1);
ds($conn,$d21_1,'Minh','我觉得首先要减少使用塑料袋，否则白色污染会越来越严重。','Wo jue de shou xian yao jian shao shi yong su liao dai, fou ze bai se wu ran hui yue lai yue yan zhong.','Toi nghi truoc het giam tui nilon, ko o nhiem trang nang hon.',2);
ds($conn,$d21_1,'Lan','说得对。还有就是垃圾要分类。','Shuo de dui. Hai you jiu shi la ji yao fen lei.','Dung. Con phai phan loai rac.',3);
ds($conn,$d21_1,'Minh','对，在环保方面，小事也能起到大作用。','Dui, zai huan bao fang mian, xiao shi ye neng qi dao da zuo yong.','Trong BVMT, viec nho cung co tac dung lon.',4);
$d21_2=d($conn,$L21,'Tiet kiem nang luong','Tiet kiem dien nuoc.',2);
ds($conn,$d21_2,'Minh','你平时有节约用水用电的习惯吗？','Ni ping shi you jie yue yong shui yong dian de xi guan ma?','Ban co thoi quen tiet kiem nuoc dien ko?',1);
ds($conn,$d21_2,'Lan','有啊。我出门都会关灯，洗完手马上关水龙头。','You a. Wo chu men dou hui guan deng, xi wan shou ma shang guan shui long tou.','Co. Toi ra ngoai tat den, rua tay xong tat nuoc ngay.',2);
ds($conn,$d21_2,'Minh','真不错。对于节约能源，每个人的小习惯都很重要。','Zhen bu cuo. Dui yu jie yue neng yuan, mei ge ren de xiao xi guan dou hen zhong yao.','Tot. Ve tiet kiem nang luong, thoi quen nho cua moi nguoi deu quan trong.',3);
ds($conn,$d21_2,'Lan','是啊，保护地球需要我们大家一起努力。','Shi a, bao hu di qiu xu yao wo men da jia yi qi nu li.','Dung, bao ve trai dat can ca chung ta cung co gang.',4);
$d21_3=d($conn,$L21,'Di lai xanh','Di lai bao ve moi truong.',3);
ds($conn,$d21_3,'Lan','你现在上班怎么去？','Ni xian zai shang ban zen me qu?','Bay gio ban di lam bang gi?',1);
ds($conn,$d21_3,'Minh','我改骑自行车了，既环保又锻炼身体。','Wo gai qi zi xing che le, ji huan bao you duan lian shen ti.','Toi chuyen sang di xe dap, vua BVMT vua tap the duc.',2);
ds($conn,$d21_3,'Lan','好主意。随着环保意识提高，骑自行车的人越来越多了。','Hao zhu yi. Sui zhe huan bao yi shi ti gao, qi zi xing che de ren yue lai yue duo le.','Y hay. Cung voi y thuc BVMT tang, nhieu nguoi di xe dap hon.',3);
ds($conn,$d21_3,'Minh','是啊，保护地球要从自己做起。','Shi a, bao hu di qiu yao cong zi ji zuo qi.','Dung, bao ve trai dat phai tu minh bat dau.',4);
ds($conn,$d21_3,'Lan','你说得对，我也要考虑换一种出行方式。','Ni shuo de dui, wo ye yao kao lv huan yi zhong chu xing fang shi.','Ban noi dung, toi cung can doi cach di lai.',5);
r($conn,$L21,'Bao ve ngoi nha chung','我们的地球正面临着严重的环境问题。随着工业的发展，空气污染和水污染越来越严重。很多人还没有意识到，保护环境其实就是在保护我们自己。对于每个人来说，减少浪费、节约能源都是很容易做到的事情。出门时关灯、节约用水、少用塑料袋，这些小事看起来不起眼，但如果每个人都这样做，效果就会非常大。在环保方面，我们还可以选择绿色出行，比如骑自行车或坐公交车。否则，等到环境被破坏了再后悔就来不及了。让我们从今天开始，一起保护我们的家园吧。','Wo men de di qiu zheng mian lin zhe yan zhong de huan jing wen ti. Sui zhe gong ye de fa zhan, kong qi wu ran he shui wu ran yue lai yue yan zhong. Hen duo ren hai mei you yi shi dao, bao hu huan jing qi shi jiu shi zai bao hu wo men zi ji. Dui yu mei ge ren lai shuo, jian shao lang fei、jie yue neng yuan dou shi hen rong yi zuo dao de shi qing. Chu men shi guan deng、jie yue yong shui、shao yong su liao dai, zhe xie xiao shi kan qi lai bu qi yan, dan ru guo mei ge ren dou zhe yang zuo, xiao guo jiu hui fei chang da. Zai huan bao fang mian, wo men hai ke yi xuan ze lv se chu xing, bi ru qi zi xing che huo zuo gong jiao che. Fou ze, deng dao huan jing bei po huai le zai hou hui jiu lai bu ji le. Rang wo men cong jin tian kai shi, yi qi bao hu wo men de jia yuan ba.','Trai dat dang doi mat o nhiem nghiem trong. Cung voi cong nghiep phat trien, o nhiem khong khi va nuoc nang hon. Nhieu nguoi chua nhan ra BVMT la bao ve chinh minh. Giam lang phi, tiet kiem nang luong la viec de lam. Den tat den, tiet kiem nuoc, it dung tui nilon - viec nho co tac dung lon. Chon di lai xanh nhu xe dap. Neu ko, khi MT huy hoai roi thi qua muon. Cung BVMT tu hom nay.','medium',180,1);
$L21l=l($conn,$L21,'BV moi truong','A: Ban co thoi quen BVMT ko? B: Co, toi phan loai rac va tiet kiem nuoc. A: Tai sao ban lam vay? B: Vi toi nghi moi nguoi nen co trach nhiem voi moi truong. A: Ban co di xe dap ko? B: Cuoi tuan co, vua BVMT vua tap the duc.','A: Ni you bao hu huan jing de xi guan ma? B: You, wo la ji fen lei he jie yue yong shui. A: Wei shen me ni zhe yang zuo? B: Yin wei wo jue de mei ge ren dou ying gai dui huan jing fu ze. A: Ni hui qi zi xing che ma? B: Zhou mo hui, ji huan bao you yun dong.','A: Ban co thoi quen BVMT ko? B: Co, toi phan loai rac va tiet kiem nuoc. A: Tai sao ban lam vay? B: Vi toi nghi moi nguoi nen co trach nhiem voi moi truong. A: Ban co di xe dap ko? B: Cuoi tuan co, vua BVMT vua tap the duc.','1');
lq($conn,$L21l,'B co thoi quen BVMT nao?','{"A":"Di xe may","B":"Phan loai rac","C":"Dung nhieu tui nilon"}','Phan loai rac','Phan loai rac va tiet kiem nuoc.','multiple_choice',1);
lq($conn,$L21l,'Tai sao B lam vay?','{"A":"Vi luat","B":"Co trach nhiem voi MT","C":"Vi ban be"}','Co trach nhiem voi MT','Moi nguoi nen co trach nhiem voi MT.','multiple_choice',2);
lq($conn,$L21l,'B di xe dap khi nao?','{"A":"Moi ngay","B":"Cuoi tuan","C":"Khong bao gio"}','Cuoi tuan','Cuoi tuan di xe dap.','multiple_choice',3);
$E21_1=e($conn,$L21,'Chon dap an','"保护" co nghia la?','multiple_choice','medium',1,'B',1);
eo($conn,$E21_1,'Pha huy','A',0,1); eo($conn,$E21_1,'Bao ve','B',1,2); eo($conn,$E21_1,'Bao qua','C',0,3);
$E21_2=e($conn,$L21,'Dich','"Bao ve moi truong la trach nhiem cua moi nguoi."','translation','medium',1,'保护环境是每个人的责任。',2);
$E21_3=e($conn,$L21,'Dien tu','___着经济的发展，环境问题越来越严重。','fill_blank','medium',1,'随',3);
$E21_4=e($conn,$L21,'Sap xep','保护 / 环境 / 应该 / 我们 / 从 / 小事 / 做起','sentence_order','medium',1,'保护环境应该从小事做起。',4);
$E21_5=e($conn,$L21,'Dung sai','"节约" co nghia la lang phi.','true_false','easy',1,'false',5);
eo($conn,$E21_5,'Dung','A',0,1); eo($conn,$E21_5,'Sai','B',1,2);
$E21_6=e($conn,$L21,'Dien tu','减少使用塑料袋，___会导致白色污染。','fill_blank','medium',1,'否则',6);
$E21_7=e($conn,$L21,'Chon dap an','"在...方面" dung de?','multiple_choice','medium',1,'C',7);
eo($conn,$E21_7,'Hoi thoi gian','A',0,1); eo($conn,$E21_7,'Hoi dia diem','B',0,2); eo($conn,$E21_7,'Chi phuong dien','C',1,3);
$E21_8=e($conn,$L21,'Dien tu','___于垃圾分类，我们应该认真对待。','fill_blank','medium',1,'对',8);
$E21_9=e($conn,$L21,'Chon tu','xanh la: ___色出行。','multiple_choice','medium',1,'B',9);
eo($conn,$E21_9,'hong','A',0,1); eo($conn,$E21_9,'lv','B',1,2); eo($conn,$E21_9,'lan','C',0,3);
$E21_10=e($conn,$L21,'Dien tu','Tiet kiem nang luong va ___ giam o nhiem.','fill_blank','medium',1,'减少',10);
foreach ([$v21_1,$v21_2,$v21_3,$v21_4,$v21_5,$v21_6,$v21_7,$v21_8,$v21_9,$v21_10,$v21_11] as $i=>$vid) if ($vid) rv($conn,$L21,$vid,'core',$i+1);
echo " HSK4 L21 done: $v21 vocab, 4 grammar, 3 dialogues, 1 reading, 1 listening, 10 exercises\n";
$L22=createLesson($conn,4,22,'Bai 22: Peng you zhi jian de you yi','Tinh ban giua nhung nguoi ban. Cau truc "zhi" (cua, o). "ji ran...jiu..." (da...thi...). "nan dao" (le nao/co phai). "bing" (nhan manh).','["Tinh ban","Tin tuong","Quan he"]','Tinh ban','medium','HSK4 Bai 22: Chat luong cao. 之 (cua/giua). 既然...就... (da...thi...). 难道 (le nao). 并 + Phu dinh.');
$v22=0;
$v22_1=v($conn,$L22,4,'友谊','you yi','tinh ban','tinh ban','真正的友谊很珍贵。','Zhen zheng de you yi hen zhen gui.','Tinh ban that su rat quy.','noun','Tinh cam ban be.',++$v22);
$v22_2=v($conn,$L22,4,'信任','xin ren','tin tuong','tin tuong','朋友之间要互相信任。','Peng you zhi jian yao hu xiang xin ren.','Ban be can tin tuong lan nhau.','noun/verb','Tin cay.',++$v22);
$v22_3=v($conn,$L22,4,'真诚','zhen cheng','chan thanh','chan thanh','真诚的友谊最长久。','Zhen cheng de you yi zui chang jiu.','Tinh ban chan thanh lau ben nhat.','adj','That tam.',++$v22);
$v22_4=v($conn,$L22,4,'尊重','zun zhong','ton trong','ton trong','互相尊重很重要。','Hu xiang zun zhong hen zhong yao.','Ton trong lan nhau rat quan trong.','verb','Ton trong nguoi khac.',++$v22);
$v22_5=v($conn,$L22,4,'理解','li jie','thau hieu','hieu','朋友之间需要理解。','Peng you zhi jian xu yao li jie.','Ban be can thau hieu nhau.','verb','Thong cam.',++$v22);
$v22_6=v($conn,$L22,4,'争吵','zheng chao','tranh cai','cai','他们从不争吵。','Ta men cong lai bu zheng chao.','Ho chua bao gio cai nhau.','verb','Cai va.',++$v22);
$v22_7=v($conn,$L22,4,'原谅','yuan liang','tha thu','tha thu','请原谅我。','Qing yuan liang wo.','Hay tha thu cho toi.','verb','Bo qua loi lam.',++$v22);
$v22_8=v($conn,$L22,4,'宝贵','bao gui','quy bau','quy','友谊很宝贵。','You yi hen bao gui.','Tinh ban rat quy.','adj','Co gia tri cao.',++$v22);
$v22_9=v($conn,$L22,4,'陪伴','pei ban','dong hanh','ben canh','谢谢你一直陪伴我。','Xie xie ni yi zhi pei ban wo.','Cam on ban luon ben canh toi.','verb','O ben.',++$v22);
$v22_10=v($conn,$L22,4,'珍惜','zhen xi','tran trong','tran trong','珍惜身边的友谊。','Zhen xi shen bian de you yi.','Tran trong tinh ban ben canh.','verb','Quy trong.',++$v22);
$v22_11=v($conn,$L22,4,'彼此','bi ci','lan nhau','lan nhau','我们彼此信任。','Wo men bi ci xin ren.','Chung toi tin tuong lan nhau.','pron','Hai ben.',++$v22);
$g22_1=g($conn,$L22,'Cau truc 之 (van phong)','DT + 之 + DT','Cua / Giua','之 la tu van phong, chi quan he so huu hoac lien he. Trong giao tiep thuong dung 的.','朋友之间 = peng you zhi jian = giua ban be.','So huu van phong.',1);
ge($conn,$g22_1,'朋友之间的友谊需要用心维护。','Peng you zhi jian de you yi xu yao yong xin wei hu.','Tinh ban giua nhung nguoi ban can duoc gin giu.',1);
ge($conn,$g22_1,'真诚是友谊的基础。','Zhen cheng shi you yi de ji chu.','Chan thanh la nen tang cua tinh ban.',2);
$g22_2=g($conn,$L22,'Cau truc 既然...就...','既然 + DK + 就 + Ket qua','Da...thi...','既然 (ji ran) dua ra DK da biet, 就 (jiu) dan ket qua.','既然我们是朋友，就应该互相帮助 = Da la ban, nen giup do nhau.','Dieu kien da biet.',2);
ge($conn,$g22_2,'既然我们选择了做朋友，就应该互相信任。','Ji ran wo men xuan ze le zuo peng you, jiu ying gai hu xiang xin ren.','Da chon lam ban, nen tin tuong lan nhau.',1);
ge($conn,$g22_2,'既然互相理解，就不会争吵。','Ji ran hu xiang li jie, jiu bu hui zheng chao.','Da thau hieu nhau, thi ko cai nhau.',2);
$g22_3=g($conn,$L22,'Cau truc 难道 (nghi van tu tu)','难道 + Khang dinh/phu dinh + ma?','Le nao / Chang le','难道 dung trong cau hoi tu tu, dien ta su nhan manh hoac nghi van. Khong can tra loi truc tiep.','难道你不知道吗？ = Le nao ban ko biet sao?','Nghiem van tu tu.',3);
ge($conn,$g22_3,'难道真正的友谊不是建立在信任之上的吗？','Nan dao zhen zheng de you yi bu shi jian li zai xin ren zhi shang de ma?','Le nao tinh ban that su ko xay dung tren tin tuong sao?',1);
ge($conn,$g22_3,'难道你不珍惜我们之间的友谊吗？','Nan dao ni bu zhen xi wo men zhi jian de you yi ma?','Le nao ban ko tran trong tinh ban giua chung ta sao?',2);
$g22_4=g($conn,$L22,'Cau truc 并 + Phu dinh','并 + bu/mei + V','Nhan manh phu dinh','并 (bing) truoc phu dinh de nhan manh su phu nhan.','他并不是我的朋友 = Anh ay ko phai la ban toi.','Nhan manh phu dinh.',4);
ge($conn,$g22_4,'争吵并不意味着友谊结束了。','Zheng chao bing bu yi wei zhe you yi jie shu le.','Cai nhau ko co nghia la tinh ban ket thuc.',1);
ge($conn,$g22_4,'真正的朋友并不会因为距离而疏远。','Zhen zheng de peng you bing bu hui yin wei ju li er shu yuan.','Ban that su ko vi khoang cach ma xa cach.',2);
$d22_1=d($conn,$L22,'Dinh nghia tinh ban','The nao la ban that su.',1);
ds($conn,$d22_1,'Lan','你觉得什么样的友谊才是真正的友谊？','Ni jue de shen me yang de you yi cai shi zhen zheng de you yi?','Ban nghi tinh ban the nao moi la that su?',1);
ds($conn,$d22_1,'Minh','对我来说，真正的友谊建立在信任和真诚之上。','Dui wo lai shuo, zhen zheng de you yi jian li zai xin ren he zhen cheng zhi shang.','Voi toi, tinh ban that su xay dung tren tin tuong va chan thanh.',2);
ds($conn,$d22_1,'Lan','既然互相信任，就不会随便怀疑对方。','Ji ran hu xiang xin ren, jiu bu hui sui bian huai yi dui fang.','Da tin tuong nhau, ko nghi ngo ban.',3);
ds($conn,$d22_1,'Minh','没错。朋友之间最重要的是彼此理解。','Mei cuo. Peng you zhi jian zui zhong yao de shi bi ci li jie.','Dung. Ban be quan trong nhat la thau hieu nhau.',4);
ds($conn,$d22_1,'Lan','吵架了也不要紧，只要真诚原谅就行。','Chao jia le ye bu yao jin, zhi yao zhen cheng yuan liang jiu xing.','Cai nhau cung ko sao, chi can chan thanh tha thu.',5);
$d22_2=d($conn,$L22,'Giu gin tinh ban','Giu gin tinh ban.',2);
ds($conn,$d22_2,'Minh','我和最好的朋友最近很少联系了。','Wo he zui hao de peng you zui jin hen shao lian xi le.','Toi va ban than it lien lac roi.',1);
ds($conn,$d22_2,'Lan','难道你们吵架了吗？','Nan dao ni men chao jia le ma?','Le nao hai ban cai nhau sao?',2);
ds($conn,$d22_2,'Minh','没有，只是因为工作太忙了。','Mei you, zhi shi yin wei gong zuo tai mang le.','Ko co, chi vi ban qua ban.',3);
ds($conn,$d22_2,'Lan','真正的友谊并不会因为忙碌而改变。','Zhen zheng de you yi bing bu hui yin wei mang lu er gai bian.','Tinh ban that su ko vi ban ma doi.',4);
ds($conn,$d22_2,'Minh','你说得对。我应该主动联系他。','Ni shuo de dui. Wo ying gai zhu dong lian xi ta.','Ban dung. Toi nen chu dong lien lac.',5);
$d22_3=d($conn,$L22,'Quy trong tinh ban','Hoc cach tran trong.',3);
ds($conn,$d22_3,'Lan','朋友送了我一份很珍贵的礼物。','Peng you song le wo yi fen hen zhen gui de li wu.','Ban tang toi mot mon qua quy.',1);
ds($conn,$d22_3,'Minh','礼物不重要，重要的是他的心意。','Li wu bu zhong yao, zhong yao de shi ta de xin yi.','Qua ko quan trong, tam y moi quan trong.',2);
ds($conn,$d22_3,'Lan','是啊，朋友之间的陪伴和理解是最宝贵的。','Shi a, peng you zhi jian de pei ban he li jie shi zui bao gui de.','Dung, dong hanh va thau hieu la quy nhat.',3);
ds($conn,$d22_3,'Minh','珍惜身边每一个真诚的朋友吧。','Zhen xi shen bian mei yi ge zhen cheng de peng you ba.','Hay tran trong tung nguoi ban chan thanh.',4);
ds($conn,$d22_3,'Lan','嗯，我们一起珍惜这份友谊。','En, wo men yi qi zhen xi zhe fen you yi.','U, cung tran trong tinh ban nay.',5);
r($conn,$L22,'Tinh ban giua ban be','友谊是人生中最宝贵的财富之一。朋友之间的信任和理解，是友谊长久的基础。真正的朋友不会因为距离而变得陌生，也不会因为时间而忘记对方。我和小华认识已经十年了，我们之间从来没有过真正的争吵。即使有不同的意见，我们也会互相尊重和理解。有时候我们会很久不联系，但当我们再次见面的时候，仍然像以前一样亲密。难道这不是真正的友谊吗？我始终相信，真诚是友谊最重要的东西。如果不珍惜，再好的友谊也会失去。既然我们拥有这份友谊，就应该用心去维护它。','You yi shi ren sheng zhong zui bao gui de cai fu zhi yi. Peng you zhi jian de xin ren he li jie, shi you yi chang jiu de ji chu. Zhen zheng de peng you bu hui yin wei ju li er bian de mo sheng, ye bu hui yin wei shi jian er wang ji dui fang. Wo he Xiao Hua ren shi yi jing shi nian le, wo men zhi jian cong lai mei you guo zhen zheng de zheng chao. Ji shi you bu tong de yi jian, wo men ye hui hu xiang zun zhong he li jie. You shi hou wo men hui hen jiu bu lian xi, dan dang wo men zai ci jian mian de shi hou, reng ran xiang yi qian yi yang qin mi. Nan dao zhe bu shi zhen zheng de you yi ma? Wo shi zhong xiang xin, zhen cheng shi you yi zui zhong yao de dong xi. Ru guo bu zhen xi, zai hao de you yi ye hui shi qu. Ji ran wo men yong you zhe fen you yi, jiu ying gai yong xin qu wei hu ta.','Tinh ban la tai san quy nhat doi. Tin tuong va thau hieu la nen tang. Ban that su ko vi xa cach ma la, ko vi thoi gian ma quen. Toi va Tieu Hoa quen 10 nam, chua tung cai nhau. Co y kien khac cung ton trong. Lau ko gap nhung gap lai van than. Le nao do ko phai tinh ban that su? Toi tin chan thanh la quan trong nhat. Ko tran trong se mat. Da co tinh ban, hay gin giu.','medium',195,1);
$L22l=l($conn,$L22,'Tinh ban','A: Ban co nghe noi Minh va Tuan gianh nhau ko? B: Co. Ho cai nhau vi chuyen nho. A: Le nao 10 nam tinh ban vi chuyen nho ma ket thuc? B: Ko dau. Ho da tha thu cho nhau roi. A: Toi mung. Tinh ban that su ko vi ly do nho ma tan vo. B: Dung. Chan thanh va thau hieu la quan trong nhat.','A: Ni ting shuo Ming he Tuan chao jia le ma? B: Ting shuo le. Shi yin wei yi jian xiao shi. A: Nan dao shi nian de you yi jiu yin wei zhe ge jie shu le ma? B: Bu shi, ta men yi jing yuan liang bi ci le. A: Na jiu hao. Zhen zheng de you yi bing bu hui yin wei xiao shi jiu jie shu. B: Dui, zhen cheng he li jie cai shi zui bang de.','A: Ban co nghe noi Minh va Tuan gianh nhau ko? B: Co. Ho cai nhau vi chuyen nho. A: Le nao 10 nam tinh ban vi chuyen nho ma ket thuc? B: Ko dau. Ho da tha thu cho nhau roi. A: Toi mung. Tinh ban that su ko vi ly do nho ma tan vo. B: Dung. Chan thanh va thau hieu la quan trong nhat.','1');
lq($conn,$L22l,'Tai sao Minh va Tuan cai nhau?','{"A":"Chuyen tien","B":"Chuyen nho","C":"Chuyen tinh cam"}','Chuyen nho','Vi mot chuyen nho.','multiple_choice',1);
lq($conn,$L22l,'Ho da lam gi?','{"A":"Ket thuc tinh ban","B":"Tha thu cho nhau","C":"Khong noi chuyen"}','Tha thu cho nhau','Ho da tha thu cho nhau.','multiple_choice',2);
lq($conn,$L22l,'Dieu nao quan trong nhat trong tinh ban?','{"A":"Tuoi tac","B":"Chan thanh va thau hieu","C":"Khoang cach"}','Chan thanh va thau hieu','Chan thanh va thau hieu quan trong nhat.','multiple_choice',3);
$E22_1=e($conn,$L22,'Chon dap an','"友谊" co nghia la?','multiple_choice','medium',1,'C',1);
eo($conn,$E22_1,'Tinh yeu','A',0,1); eo($conn,$E22_1,'Tinh cam gia dinh','B',0,2); eo($conn,$E22_1,'Tinh ban','C',1,3);
$E22_2=e($conn,$L22,'Dich','"Chan thanh la nen tang cua tinh ban."','translation','medium',1,'真诚是友谊的基础。',2);
$E22_3=e($conn,$L22,'Dien tu','___然我们是朋友，就应该互相信任。','fill_blank','medium',1,'既',3);
$E22_4=e($conn,$L22,'Sap xep','朋友 / 之间 / 信任 / 需要 / 互相','sentence_order','medium',1,'朋友之间需要互相信任。',4);
$E22_5=e($conn,$L22,'Dung sai','"难道" dung trong cau hoi tu tu.','true_false','medium',1,'true',5);
eo($conn,$E22_5,'Dung','A',1,1); eo($conn,$E22_5,'Sai','B',0,2);
$E22_6=e($conn,$L22,'Dien tu','争吵并___意味着友谊结束。','fill_blank','medium',1,'不',6);
$E22_7=e($conn,$L22,'Chon dap an','"之" trong "朋友之间" co nghia?','multiple_choice','medium',1,'B',7);
eo($conn,$E22_7,'Va','A',0,1); eo($conn,$E22_7,'Cua / Giua','B',1,2); eo($conn,$E22_7,'De','C',0,3);
$E22_8=e($conn,$L22,'Dien tu','朋友之间彼此___任很重要。','fill_blank','medium',1,'信',8);
$E22_9=e($conn,$L22,'Chon tu','___ la tha thu cho nhau.','multiple_choice','medium',1,'B',9);
eo($conn,$E22_9,'Chan thanh','A',0,1); eo($conn,$E22_9,'Yuan liang','B',1,2); eo($conn,$E22_9,'Cung nhau','C',0,3);
$E22_10=e($conn,$L22,'Dien tu','Da la ban cua nhau, hay ___ trong tinh ban.','fill_blank','medium',1,'珍惜',10);
foreach ([$v22_1,$v22_2,$v22_3,$v22_4,$v22_5,$v22_6,$v22_7,$v22_8,$v22_9,$v22_10,$v22_11] as $i=>$vid) if ($vid) rv($conn,$L22,$vid,'core',$i+1);
echo " HSK4 L22 done: $v22 vocab, 4 grammar, 3 dialogues, 1 reading, 1 listening, 10 exercises\n";
$L23=createLesson($conn,4,23,'Bai 23: Lv xing rang sheng huo geng jing cai','Du lich. Cau truc "chu le...yi wai" (ngoai...ra). "yi" (de). "cong er" (do do/qua do). "bing bu/bing mei you" (thuc ra ko).','["Du lich","Trai nghiem","Kham pha"]','Du lich','medium','HSK4 Bai 23: Tu vung du lich. 除了...以外 (ngoai...ra). 以 (de). 从而 (do do). 并不/并没有 (thuc ra ko).');
$v23=0;
$v23_1=v($conn,$L23,4,'旅行','lv xing','du lich','du lich','我喜欢旅行。','Wo xi huan lv xing.','Toi thich di du lich.','verb/noun','Di choi xa.',++$v23);
$v23_2=v($conn,$L23,4,'风景','feng jing','phong canh','canh','这里的风景很美。','Zhe li de feng jing hen mei.','Phong canh o day rat dep.','noun','Canh dep.',++$v23);
$v23_3=v($conn,$L23,4,'体验','ti yan','trai nghiem','trai nghiem','这次旅行体验很棒。','Zhe ci lv xing ti yan hen bang.','Trai nghiem chuyen di nay rat tuyet.','verb/noun','Cam nhan thuc te.',++$v23);
$v23_4=v($conn,$L23,4,'精彩','jing cai','tuyet voi','tuyet','生活很精彩。','Sheng huo hen jing cai.','Cuoc song rat tuyet.','adj','Dep, hay.',++$v23);
$v23_5=v($conn,$L23,4,'放松','fang song','thu gian','thu gian','旅行让我放松。','Lv xing rang wo fang song.','Du lich giup toi thu gian.','verb','Giai tri.',++$v23);
$v23_6=v($conn,$L23,4,'目的地','mu di di','diem den','diem den','目的地是北京。','Mu di di shi Bei Jing.','Diem den la Bac Kinh.','noun','Noi den.',++$v23);
$v23_7=v($conn,$L23,4,'当地','dang di','ban dia','dia phuong','了解当地文化。','Liao jie dang di wen hua.','Tim hieu van hoa dia phuong.','noun','Noi do.',++$v23);
$v23_8=v($conn,$L23,4,'美食','mei shi','am thuc ngon','mon ngon','品尝当地美食。','Pin chang dang di mei shi.','Thuong thuc am thuc dia phuong.','noun','Do an ngon.',++$v23);
$v23_9=v($conn,$L23,4,'自然','zi ran','tu nhien','tu nhien','自然风光很迷人。','Zi ran feng guang hen mi ren.','Phong canh tu nhien quyen ru.','noun','Thien nhien.',++$v23);
$v23_10=v($conn,$L23,4,'纪念品','ji nian pin','qua luu niem','qua luu niem','买了一些纪念品。','Mai le yi xie ji nian pin.','Mua vai mon qua luu niem.','noun','Vat ky niem.',++$v23);
$v23_11=v($conn,$L23,4,'感受','gan shou','cam nhan','cam nhan','感受大自然。','Gan shou da zi ran.','Cam nhan thien nhien.','verb/ noun','Cam giac.',++$v23);
$v23_12=v($conn,$L23,4,'回忆','hui yi','ky uc','hoi uc','美好的回忆。','Mei hao de hui yi.','Ky uc dep.','noun/verb','Nho lai.',++$v23);
$g23_1=g($conn,$L23,'Cau truc 除了...以外/还/也','除了 + N + 以外 + 还/也 + V','Ngoai...ra con...','Ngoai tru mot doi tuong ra, con co hoac cung co.','除了北京以外，我还去过上海 = Ngoai Bac Kinh toi con di Thuong Hai.','Bao gom.',1);
ge($conn,$g23_1,'除了欣赏风景以外，旅行还能让我们了解当地文化。','Chu le xin shang feng jing yi wai, lv xing hai neng rang wo men liao jie dang di wen hua.','Ngoai ngam canh, du lich con cho ta hieu van hoa dia phuong.',1);
ge($conn,$g23_1,'除了放松心情以外，旅行也是一种学习。','Chu le fang song xin qing yi wai, lv xing ye shi yi zhong xue xi.','Ngoai thu gian, du lich cung la hoc tap.',2);
$g23_2=g($conn,$L23,'Cau truc 以 + V','以 + V + (Muc dich)','De / Nham','以 (yi) chi muc dich, tuong tu 为了 nhung van phong hon.','以体验当地文化为目的 = Nham trai nghiem van hoa ban dia.','Muc dich van phong.',2);
ge($conn,$g23_2,'很多人旅行是为了以放松心情。','Hen duo ren lv xing shi wei le yi fang song xin qing.','Nhieu nguoi di du lich de thu gian tam trang.',1);
ge($conn,$g23_2,'我们应该以开放的心态去感受不同的文化。','Wo men ying gai yi kai fang de xin tai qu gan shou bu tong de wen hua.','Ta nen voi tam the mo de cam nhan van hoa khac.',2);
$g23_3=g($conn,$L23,'Cau truc 从而','DK + 从而 + Ket qua','Do do / Tu do','从而 (cong er) dan ket qua tich cuc. Mang tinh van phong.','旅行让我们开阔眼界，从而更好地理解世界 = Du lich mo rong tam nhin, do do hieu the gioi.','Ket qua van phong.',3);
ge($conn,$g23_3,'旅行能让我们看到不同的生活方式，从而更加珍惜自己的生活。','Lv xing neng rang wo men kan dao bu tong de sheng huo fang shi, cong er geng jia zhen xi zi ji de sheng huo.','Du lich cho ta thay cach song khac, do do tran trong cuoc song minh hon.',1);
ge($conn,$g23_3,'通过旅行获得新的体验，从而丰富自己的人生。','Tong guo lv xing huo de xin de ti yan, cong er feng fu zi ji de ren sheng.','Qua du lich co trai nghiem moi, tu do phong phu doi minh.',2);
$g23_4=g($conn,$L23,'Cau truc 并不/并没有 + V','并不/并没有 + V + (DK)','Thuc ra khong','并不/并没有 nhan manh su trai nguoc voi suy nghi hoac ky vong. Nhan manh tinh xac thuc.','旅行并不只是玩儿 = Du lich thuc ra ko chi la choi.','Nhan manh thuc te.',4);
ge($conn,$g23_4,'旅行并不只是看风景，更重要的是体验当地生活。','Lv xing bing bu zhi shi kan feng jing, geng zhong yao de shi ti yan dang di sheng huo.','Du lich thuc ra ko chi xem canh, ma con la trai nghiem cuoc song ban dia.',1);
ge($conn,$g23_4,'他并没有去过很多地方，但对每个地方都了解得很深。','Ta bing mei you qu guo hen duo di fang, dan dui mei ge di fang dou liao jie de hen shen.','Anh ay thuc ra ko di nhieu noi, nhung hieu rat sau ve moi noi.',2);
$d23_1=d($conn,$L23,'Loi ich du lich','Loi ich cua du lich.',1);
ds($conn,$d23_1,'Lan','你最近有旅行的计划吗？','Ni zui jin you lv xing de ji hua ma?','Gan day ban co ke hoach du lich ko?',1);
ds($conn,$d23_1,'Minh','有啊，我打算下个月去云南。','You a, wo da suan xia ge yue qu Yun Nan.','Co, toi du thang sau di Van Nam.',2);
ds($conn,$d23_1,'Lan','听说那边的风景特别美。','Ting shuo na bian de feng jing te bie mei.','Nghe noi phong canh ben do dep lam.',3);
ds($conn,$d23_1,'Minh','是啊，除了欣赏自然风景以外，我还想体验当地的民族文化。','Shi a, chu le xin shang zi ran feng jing yi wai, wo hai xiang ti yan dang di de min zu wen hua.','Ngoai ngam canh tu nhien, toi con muon trai nghiem van hoa dan toc.',4);
ds($conn,$d23_1,'Lan','这样一来，旅行就更精彩了。','Zhe yang yi lai, lv xing jiu geng jing cai le.','Nhu vay du lich cang tuyet hon.',5);
$d23_2=d($conn,$L23,'Trai nghiem du lich','Chia se trai nghiem.',2);
ds($conn,$d23_2,'Minh','上次去西安我收获很大。','Shang ci qu Xi An wo shou huo hen da.','Lan truoc di Tay An toi thu hoach lon.',1);
ds($conn,$d23_2,'Lan','除了看兵马俑以外，还做了什么？','Chu le kan bing ma yong yi wai, hai zuo le shen me?','Ngoai xem binh ma dung, con lam gi?',2);
ds($conn,$d23_2,'Minh','我品尝了很多当地美食，还学了做面食。','Wo pin chang le hen duo dang di mei shi, hai xue le zuo mian shi.','Toi thuong thuc am thuc ban dia, hoc lam mon mian.',3);
ds($conn,$d23_2,'Lan','真有意思！旅行能让我们学到很多东西。','Zhen you yi si! Lv xing neng rang wo men xue dao hen duo dong xi.','Thu vi! Du lich cho ta hoc duoc nhieu.',4);
ds($conn,$d23_2,'Minh','对，旅行并不只是玩，更是一种学习。','Dui, lv xing bing bu zhi shi wan, geng shi yi zhong xue xi.','Dung, du lich ko chi la choi ma la hoc.',5);
$d23_3=d($conn,$L23,'Ky niem du lich','Luu giu ky niem.',3);
ds($conn,$d23_3,'Lan','你每次旅行都会买纪念品吗？','Ni mei ci lv xing dou hui mai ji nian pin ma?','Moi lan du lich ban deu mua qua luu niem?',1);
ds($conn,$d23_3,'Minh','会的。我会买一些当地特色的东西。','Hui de. Wo hui mai yi xie dang di te se de dong xi.','Co. Toi mua do dac trung ban dia.',2);
ds($conn,$d23_3,'Lan','我更喜欢用照片记录回忆。','Wo geng xi huan yong zhao pian ji lu hui yi.','Toi thich chup anh luu lai ky uc hon.',3);
ds($conn,$d23_3,'Minh','照片和纪念品都能留下美好的回忆。','Zhao pian he ji nian pin dou neng liu xia mei hao de hui yi.','Anh va qua deu luu ky uc dep.',4);
ds($conn,$d23_3,'Lan','每次看到这些，就会想起旅行的快乐。','Mei ci kan dao zhe xie, jiu hui xiang qi lv xing de kuai le.','Moi lan thay deu nho niem vui du lich.',5);
ds($conn,$d23_3,'Minh','这就是旅行的意义。','Zhe jiu shi lv xing de yi yi.','Do la y nghia du lich.',6);
r($conn,$L23,'Du lich va cuoc song','旅行对我来说不仅仅是一种休闲方式，更是一种生活态度。通过旅行，我们可以看到不同的风景，体验不同的文化，感受不一样的人生。除了放松心情以外，旅行还能让我们开阔眼界，从而更好地认识自己和世界。每一次旅行都是一次成长。我记得第一次一个人去旅行的时候，心里很紧张，但到了目的地以后，发现当地人都很友好。我品尝了当地的美食，了解了他们的生活习惯。那次经历让我变得更加独立和自信。旅行并不需要去很远的地方，重要的是带着一颗开放的心去感受。只要用心，身边也有美丽的风景。','Lv xing dui wo lai shuo bu jin jin shi yi zhong xiu xian fang shi, geng shi yi zhong sheng huo tai du. Tong guo lv xing, wo men ke yi kan dao bu tong de feng jing, ti yan bu tong de wen hua, gan shou bu yi yang de ren sheng. Chu le fang song xin qing yi wai, lv xing hai neng rang wo men kai kuo yan jie, cong er geng hao di ren shi zi ji he shi jie. Mei yi ci lv xing dou shi yi ci cheng zhang. Wo ji de di yi ci yi ge ren qu lv xing de shi hou, xin li hen jin zhang, dan dao le mu di di yi hou, fa xian dang di ren dou hen you hao. Wo pin chang le dang di de mei shi, liao jie le ta men de sheng huo xi guan. Na ci jing li rang wo bian de geng jia du li he zi xin. Lv xing bing bu xu yao qu hen yuan de di fang, zhong yao de shi dai zhe yi ke kai fang de xin qu gan shou. Zhi yao yong xin, shen bian ye you mei li de feng jing.','Du lich ko chi la cach thu gian ma la thai do song. Qua du lich ta thay canh dep, trai nghiem van hoa, cam nhan doi song khac. Ngoai thu gian, du lich mo rong tam nhin, do do hieu minh va the gioi hon. Moi chuyen di la su truong thanh. Toi nho lan dau di mot minh, ho hoi, nhung den noi nguoi dan than thien. Toi thuong thuc am thuc, hieu thoi quen ho. Trai nghiem do giup toi doc lap va tu tin hon. Du lich ko can xa, quan trong la tam the mo don nhan. Chi can tam, canh dep o ngay ben canh.','medium',200,1);
$L23l=l($conn,$L23,'Du lich','A: Ban thich di du lich ko? B: Rat thich. Toi vua di Ha Noi ve. A: O do co gi thu vi? B: Pho co dep, am thuc ngon. Toi da chup nhieu anh. A: Co mua qua luu niem ko? B: Co, mua mot chiec non la. A: Lan sau co dinh di dau? B: Toi muon di Tay Tang de cam nhan thien nhien.','A: Ni xi huan lv xing ma? B: Fei chang xi huan. Wo gang cong Ha Noi hui lai. A: Na li you shen me you qu? B: Gu cheng hen piao liang, mei shi hen hao chi. Wo pai le hen duo zhao. A: Ni mai ji nian pin le ma? B: Mai le yi ding cao mao. A: Xia ci ni da suan qu na er? B: Wo xiang qu Xi Zang gan shou da zi ran.','A: Ban thich di du lich ko? B: Rat thich. Toi vua di Ha Noi ve. A: O do co gi thu vi? B: Pho co dep, am thuc ngon. Toi da chup nhieu anh. A: Co mua qua luu niem ko? B: Co, mua mot chiec non la. A: Lan sau co dinh di dau? B: Toi muon di Tay Tang de cam nhan thien nhien.','1');
lq($conn,$L23l,'B vua di dau ve?','{"A":"Thanh Pho Ho Chi Minh","B":"Ha Noi","C":"Da Lat"}','Ha Noi','Vua di Ha Noi.','multiple_choice',1);
lq($conn,$L23l,'B da mua gi lam qua luu niem?','{"A":"Non la","B":"Ao","C":"Tui xach"}','Non la','Mot chiec non la.','multiple_choice',2);
lq($conn,$L23l,'B muon di dau tiep theo?','{"A":"Bac Kinh","B":"Tay Tang","C":"Thuong Hai"}','Tay Tang','Muon di Tay Tang.','multiple_choice',3);
$E23_1=e($conn,$L23,'Chon dap an','"旅行" la gi?','multiple_choice','medium',1,'B',1);
eo($conn,$E23_1,'Hoc tap','A',0,1); eo($conn,$E23_1,'Du lich','B',1,2); eo($conn,$E23_1,'Lam viec','C',0,3);
$E23_2=e($conn,$L23,'Dich','"Ngoai thu gian, du lich con giup hoc hoi."','translation','medium',1,'除了放松以外，旅行还能帮助学习。',2);
$E23_3=e($conn,$L23,'Dien tu','除了北京以外，我___去过上海。','fill_blank','medium',1,'还',3);
$E23_4=e($conn,$L23,'Sap xep','旅行 / 生活 / 让 / 精彩 / 更','sentence_order','medium',1,'旅行让生活更精彩。',4);
$E23_5=e($conn,$L23,'Dung sai','"体验" la "trai nghiem".','true_false','easy',1,'true',5);
eo($conn,$E23_5,'Dung','A',1,1); eo($conn,$E23_5,'Sai','B',0,2);
$E23_6=e($conn,$L23,'Dien tu','旅行能开阔眼界，从___更好地理解世界。','fill_blank','medium',1,'而',6);
$E23_7=e($conn,$L23,'Chon dap an','"从而" co nghia?','multiple_choice','medium',1,'C',7);
eo($conn,$E23_7,'Nhung','A',0,1); eo($conn,$E23_7,'Vi','B',0,2); eo($conn,$E23_7,'Do do','C',1,3);
$E23_8=e($conn,$L23,'Dien tu','旅行并___只是看风景。','fill_blank','medium',1,'不',8);
$E23_9=e($conn,$L23,'Chon tu','___ shi la am thuc ngon.','multiple_choice','medium',1,'A',9);
eo($conn,$E23_9,'Mei shi','A',1,1); eo($conn,$E23_9,'Feng jing','B',0,2); eo($conn,$E23_9,'Ji nian','C',0,3);
$E23_10=e($conn,$L23,'Dien tu','Ngoai choi, du lich con giup mo rong tam ___.','fill_blank','medium',1,'眼界',10);
foreach ([$v23_1,$v23_2,$v23_3,$v23_4,$v23_5,$v23_6,$v23_7,$v23_8,$v23_9,$v23_10,$v23_11,$v23_12] as $i=>$vid) if ($vid) rv($conn,$L23,$vid,'core',$i+1);
echo " HSK4 L23 done: $v23 vocab, 4 grammar, 3 dialogues, 1 reading, 1 listening, 10 exercises\n";
$L24=createLesson($conn,4,24,'Bai 24: Gou tong de zhong yao xing','Tam quan trong cua giao tiep. Cau truc "zhi suo yi...shi yin wei..." (so di...la vi...). "zai yu" (o cho/la). "gen ben" (can ban/ca thay). "tong guo" (thong qua).','["Giao tiep","Bieu dat","Quan he"]','Giao tiep','medium','HSK4 Bai 24: Tu vung giao tiep. 之所以...是因为... (so di...la vi...). 在于 (o cho/la). 根本 (can ban). 通过 (thong qua).');
$v24=0;
$v24_1=v($conn,$L24,4,'沟通','gou tong','giao tiep','giao tiep','沟通很重要。','Gou tong hen zhong yao.','Giao tiep rat quan trong.','verb','Trao doi y kien.',++$v24);
$v24_2=v($conn,$L24,4,'表达','biao da','bieu dat','bieu dat','表达自己的想法。','Biao da zi ji de xiang fa.','Bieu dat suy nghi cua minh.','verb','Trinh bay.',++$v24);
$v24_3=v($conn,$L24,4,'倾听','qing ting','lang nghe','nghe','学会倾听很重要。','Xue hui qing ting hen zhong yao.','Hoc cach lang nghe rat quan trong.','verb','Chu y nghe.',++$v24);
$v24_4=v($conn,$L24,4,'方式','fang shi','phuong thuc','cach','沟通方式很重要。','Gou tong fang shi hen zhong yao.','Cach giao tiep rat quan trong.','noun','Hinh thuc.',++$v24);
$v24_5=v($conn,$L24,4,'效果','xiao guo','hieu qua','hieu qua','沟通效果很好。','Gou tong xiao guo hen hao.','Hieu qua giao tiep rat tot.','noun','Ket qua mang lai.',++$v24);
$v24_6=v($conn,$L24,4,'误会','wu hui','hieu lam','hieu lam','不要产生误会。','Bu yao chan sheng wu hui.','Dung gay hieu lam.','noun/verb','Hieu sai.',++$v24);
$v24_7=v($conn,$L24,4,'耐心','nai xin','kien nhan','kien nhan','耐心倾听。','Nai xin qing ting.','Kien nhan lang nghe.','noun/adj','Nhan nai.',++$v24);
$v24_8=v($conn,$L24,4,'态度','tai du','thai do','thai do','态度决定一切。','Tai du jue ding yi qie.','Thai do quyet dinh tat ca.','noun','Cach nhin nhan.',++$v24);
$v24_9=v($conn,$L24,4,'有效','you xiao','hieu qua','hieu qua','有效的沟通。','You xiao de gou tong.','Giao tiep hieu qua.','adj','Co tac dung.',++$v24);
$v24_10=v($conn,$L24,4,'矛盾','mao dun','mau thuan','mau thuan','解决矛盾。','Jie jue mao dun.','Giai quyet mau thuan.','noun','Xung dot.',++$v24);
$v24_11=v($conn,$L24,4,'意见','yi jian','y kien','y kien','交换意见。','Jiao huan yi jian.','Trao doi y kien.','noun','Quan diem.',++$v24);
$g24_1=g($conn,$L24,'Cau truc 之所以...是因为...','之所以 + KQ + 是因为 + Nguyen nhan','So di...la vi...','之所以 (zhi suo yi) dua ra ket qua, 是因为 (shi yin wei) giai thich nguyen nhan. Nhan manh nguyen nhan.','之所以成功是因为努力 = So di thanh cong la vi co gang.','Nguyen nhan.',1);
ge($conn,$g24_1,'人与人之间之所以会产生误会，是因为缺乏有效的沟通。','Ren yu ren zhi jian zhi suo yi hui chan sheng wu hui, shi yin wei que fa you xiao de gou tong.','So di nguoi ta hieu lam nhau la vi thieu giao tiep hieu qua.',1);
ge($conn,$g24_1,'沟通之所以重要，是因为它能帮助我们更好地理解对方。','Gou tong zhi suo yi zhong yao, shi yin wei ta neng bang zhu wo men geng hao di li jie dui fang.','Giao tiep so di quan trong la vi no giup ta hieu nhau hon.',2);
$g24_2=g($conn,$L24,'Cau truc 在于','V + 在于 + N/V','O cho / La','在于 (zai yu) chi su phu thuoc hoac ban chat. Thuong dung de giai thich.','沟通的关键在于倾听 = Dich cua giao tiep o lang nghe.','Ban chat.',2);
ge($conn,$g24_2,'沟通的关键在于倾听，而不是只顾着说。','Gou tong de guan jian zai yu qing ting, er bu shi zhi gu zhe shuo.','Dich cua giao tiep o lang nghe, ko phai chi noi.',1);
ge($conn,$g24_2,'有效的沟通方式在于互相尊重。','You xiao de gou tong fang shi zai yu hu xiang zun zhong.','Cach giao tiep hieu qua o ton trong lan nhau.',2);
$g24_3=g($conn,$L24,'Cau truc 根本 (phu dinh)','根本 + V + Phu dinh','Ca thay / Hoan toan khong','根本 (gen ben) truoc phu dinh de nhan manh.','他根本就没听 = Anh ay ca thay ko nghe gi ca.','Phu dinh triet de.',3);
ge($conn,$g24_3,'他根本没有耐心听我把话说完。','Ta gen ben mei you nai xin ting wo ba hua shuo wan.','Anh ay ca thay ko co kien nhan nghe toi noi het.',1);
ge($conn,$g24_3,'如果根本不沟通，问题永远解决不了。','Ru guo gen ben bu gou tong, wen ti yong yuan jie jue bu liao.','Neu ca thay ko giao tiep, van de mai ko giai quyet duoc.',2);
$g24_4=g($conn,$L24,'Cau truc 通过','通过 + N + (lai) + V','Thong qua / Bang cach','通过 (tong guo) chi phuong thuc de dat duoc muc dich.','通过沟通解决问题 = Thong qua giao tiep giai quyet van de.','Phuong thuc.',4);
ge($conn,$g24_4,'通过良好的沟通，我们可以避免很多误会。','Tong guo liang hao de gou tong, wo men ke yi bi mian hen duo wu hui.','Thong qua giao tiep tot, ta co the tranh nhieu hieu lam.',1);
ge($conn,$g24_4,'通过倾听对方的意见，才能找到解决问题的方法。','Tong guo qing ting dui fang de yi jian, cai neng zhao dao jie jue wen ti de fang fa.','Thong qua lang nghe y kien doi phuong, moi tim ra cach giai quyet.',2);
$d24_1=d($conn,$L24,'Tam quan trong giao tiep','Giao tiep trong cuoc song.',1);
ds($conn,$d24_1,'Lan','你觉得沟通对人际关系重要吗？','Ni jue de gou tong dui ren ji guan xi zhong yao ma?','Ban nghi giao tiep co quan trong voi quan he ko?',1);
ds($conn,$d24_1,'Minh','当然重要。很多人之所以关系不好，就是因为沟通不畅。','Dang ran zhong yao. Hen duo ren zhi suo yi guan xi bu hao, jiu shi yin wei gou tong bu chang.','Tat nhien. So di nhieu nguoi ko tot la vi giao tiep ko thong.',2);
ds($conn,$d24_1,'Lan','那你觉得有效沟通的关键是什么？','Na ni jue de you xiao gou tong de guan jian shi shen me?','Ban nghi dich cua giao tiep hieu qua la gi?',3);
ds($conn,$d24_1,'Minh','关键不在于说多少，而在于倾听和理解。','Guan jian bu zai yu shuo duo shao, er zai yu qing ting he li jie.','Dich ko o noi nhieu ma o lang nghe va thau hieu.',4);
ds($conn,$d24_1,'Lan','没错，好的沟通方式能让人际关系更和谐。','Mei cuo, hao de gou tong fang shi neng rang ren ji guan xi geng he xie.','Cach giao tiep tot lam quan he hai hoa hon.',5);
$d24_2=d($conn,$L24,'Hieu lam trong giao tiep','Giai quyet hieu lam.',2);
ds($conn,$d24_2,'Minh','我和同事产生了误会，很不开心。','Wo he tong shi chan sheng le wu hui, hen bu kai xin.','Toi va dong nghiep hieu lam, ko vui.',1);
ds($conn,$d24_2,'Lan','你们沟通了吗？','Ni men gou tong le ma?','Hai ban giao tiep chua?',2);
ds($conn,$d24_2,'Minh','还没有，我不知道怎么开口。','Hai mei you, wo bu zhi dao zen me kai kou.','Chua, toi ko biet mo loi the nao.',3);
ds($conn,$d24_2,'Lan','如果不沟通，误会只会越来越深。通过沟通才能解决问题。','Ru guo bu gou tong, wu hui zhi hui yue lai yue shen. Tong guo gou tong cai neng jie jue wen ti.','Ko giao tiep, hieu lam cang sau. Qua giao tiep moi giai quyet.',4);
ds($conn,$d24_2,'Minh','你说得对，我明天就找他说清楚。','Ni shuo de dui, wo ming tian jiu zhao ta shuo qing chu.','Ban dung, toi mai se noi ro.',5);
$d24_3=d($conn,$L24,'Hoc cach lang nghe','Ren kien nhan lang nghe.',3);
ds($conn,$d24_3,'Lan','我发现自己总是打断别人说话。','Wo fa xian zi ji zong shi da duan bie ren shuo hua.','Toi thay minh hay ngat loi nguoi khac.',1);
ds($conn,$d24_3,'Minh','倾听是一门艺术，需要耐心。','Qing ting shi yi men yi shu, xu yao nai xin.','Lang nghe la nghe thuat, can kien nhan.',2);
ds($conn,$d24_3,'Lan','怎么才能学会倾听？','Zen me cai neng xue hui qing ting?','Lam sao de hoc lang nghe?',3);
ds($conn,$d24_3,'Minh','首先要尊重对方，让对方把话说完。','Shou xian yao zun zhong dui fang, rang dui fang ba hua shuo wan.','Truoc het ton trong, de ho noi het.',4);
ds($conn,$d24_3,'Lan','我明白了。沟通不在于说，而在于听。','Wo ming bai le. Gou tong bu zai yu shuo, er zai yu ting.','Toi hieu. Giao tiep ko o noi ma o nghe.',5);
r($conn,$L24,'Tam quan trong cua giao tiep','沟通是人际关系中最重要的技能之一。很多人之所以和朋友或家人产生矛盾，往往不是因为感情不好，而是因为沟通方式不对。有效的沟通不在于你说得多精彩，而在于你能不能真正倾听对方的想法。通过倾听，你可以了解对方的真实感受，从而避免误会。在表达自己的意见时，也要注意态度和方式。如果根本不考虑对方的感受，只顾自己说，沟通效果一定不好。另外，耐心也很重要。只有双方都愿意耐心倾听，才能达到良好的沟通效果。记住，好的沟通能让关系更亲近，让生活更美好。','Gou tong shi ren ji guan xi zhong zui zhong yao de ji neng zhi yi. Hen duo ren zhi suo yi he peng you huo jia ren chan sheng mao dun, wang wang bu shi yin wei gan qing bu hao, er shi yin wei gou tong fang shi bu dui. You xiao de gou tong bu zai yu ni shuo de duo jing cai, er zai yu ni neng bu neng zhen zheng qing ting dui fang de xiang fa. Tong guo qing ting, ni ke yi liao jie dui fang de zhen shi gan shou, cong er bi mian wu hui. Zai biao da zi ji de yi jian shi, ye yao zhu yi tai du he fang shi. Ru guo gen ben bu kao lv dui fang de gan shou, zhi gu zi ji shuo, gou tong xiao guo yi ding bu hao. Ling wai, nai xin ye hen zhong yao. Zhi you shuang fang dou yuan yi nai xin qing ting, cai neng da dao liang hao de gou tong xiao guo. Ji zhu, hao de gou tong neng rang guan xi geng qin jin, rang sheng huo geng mei hao.','Giao tiep la ky nang quan trong nhat. So di nhieu nguoi mau thuan la vi cach giao tiep ko dung. Hieu qua ko o noi hay ma o lang nghe. Qua lang nghe, ta hieu cam xac thuc cua doi phuong, tranh hieu lam. Khi bieu dat y kien, de y thai do. Ko quan tam cam giac nguoi khac, hieu qua se kem. Kien nhan rat quan trong. Chi khi ca ben lang nghe moi co hieu qua tot. Nho rang giao tiep tot lam quan he gan gui hon.','medium',195,1);
$L24l=l($conn,$L24,'Giao tiep','A: Tai sao ban va me cai nhau? B: Vi me ko hieu toi muon gi. A: Ban co noi ro y muon ko? B: Toi co noi nhung co le cach noi sai. A: Giao tiep can kien nhan. Ban nen lang nghe me truoc. B: Toi se thu. Cam on ban.','A: Wei shen me ni he ma ma zheng chao? B: Yin wei ma ma bu li jie wo xiang yao shen me. A: Ni you qing chu di biao da ni de xiang fa ma? B: Wo shuo le, dan ke shi wo de biao da fang shi bu dui. A: Gou tong xu yao nai xin. Ni ying gai xian qing ting ma ma shuo. B: Wo hui shi shi. Xie xie ni.','A: Tai sao ban va me cai nhau? B: Vi me ko hieu toi muon gi. A: Ban co noi ro y muon ko? B: Toi co noi nhung co le cach noi sai. A: Giao tiep can kien nhan. Ban nen lang nghe me truoc. B: Toi se thu. Cam on ban.','1');
lq($conn,$L24l,'Tai sao ban B va me cai nhau?','{"A":"Me ko hieu B","B":"Vi tien","C":"Vi ban be"}','Me ko hieu B','Vi me ko hieu B muon gi.','multiple_choice',1);
lq($conn,$L24l,'A khuyen B gi?','{"A":"Ko noi gi","B":"Lang nghe me truoc","C":"Bo di"}','Lang nghe me truoc','Hay lang nghe me truoc.','multiple_choice',2);
lq($conn,$L24l,'B se lam gi?','{"A":"Khong lam gi","B":"Se thu","C":"Cai tiep"}','Se thu','Se thu.','multiple_choice',3);
$E24_1=e($conn,$L24,'Chon dap an','"沟通" la gi?','multiple_choice','medium',1,'A',1);
eo($conn,$E24_1,'Giao tiep','A',1,1); eo($conn,$E24_1,'Di lai','B',0,2); eo($conn,$E24_1,'Doc sach','C',0,3);
$E24_2=e($conn,$L24,'Dich','"So di hieu lam la vi thieu giao tiep."','translation','medium',1,'之所以误会是因为缺乏沟通。',2);
$E24_3=e($conn,$L24,'Dien tu','沟通的关键___于倾听。','fill_blank','medium',1,'在',3);
$E24_4=e($conn,$L24,'Sap xep','沟通 / 有效 / 耐心 / 需要','sentence_order','medium',1,'有效沟通需要耐心。',4);
$E24_5=e($conn,$L24,'Dung sai','"态度" la "thai do".','true_false','easy',1,'true',5);
eo($conn,$E24_5,'Dung','A',1,1); eo($conn,$E24_5,'Sai','B',0,2);
$E24_6=e($conn,$L24,'Dien tu','他根___没有听我说话。','fill_blank','medium',1,'本',6);
$E24_7=e($conn,$L24,'Chon dap an','"在于" co nghia la gi?','multiple_choice','medium',1,'B',7);
eo($conn,$E24_7,'Tai','A',0,1); eo($conn,$E24_7,'O cho / La','B',1,2); eo($conn,$E24_7,'Cho nen','C',0,3);
$E24_8=e($conn,$L24,'Dien tu','通___良好沟通可以避免误会。','fill_blank','medium',1,'过',8);
$E24_9=e($conn,$L24,'Chon tu','Bieu dat y kien can chu y ___ do.','multiple_choice','medium',1,'A',9);
eo($conn,$E24_9,'Thai do','A',1,1); eo($conn,$E24_9,'Thoi gian','B',0,2); eo($conn,$E24_9,'Dia diem','C',0,3);
$E24_10=e($conn,$L24,'Dien tu','Hieu qua giao tiep phu thuoc vao cach ___.','fill_blank','medium',1,'表达',10);
foreach ([$v24_1,$v24_2,$v24_3,$v24_4,$v24_5,$v24_6,$v24_7,$v24_8,$v24_9,$v24_10,$v24_11] as $i=>$vid) if ($vid) rv($conn,$L24,$vid,'core',$i+1);
echo " HSK4 L24 done: $v24 vocab, 4 grammar, 3 dialogues, 1 reading, 1 listening, 10 exercises\n";
$L25=createLesson($conn,4,25,'Bai 25: Xue hui shuo bu','Hoc cach tu choi. Cau truc "na pa...ye..." (thu the/tham chi...cung...). "yu" (doi voi/trong). "nan dao bu shi...ma". "dang zuo" (coi nhu).','["Tu choi","Lua chon","Quyen"]','Ky nang song','medium','HSK4 Bai 25: Tu vung tu choi. 哪怕...也... (thu the...cung...). 于 (doi voi/trong). 难道不是...吗 (le nao ko phai...sao). 当作 (coi nhu).');
$v25=0;
$v25_1=v($conn,$L25,4,'拒绝','ju jue','tu choi','tu choi','学会拒绝。','Xue hui ju jue.','Hoc cach tu choi.','verb','Khong dong y.',++$v25);
$v25_2=v($conn,$L25,4,'接受','jie shou','chap nhan','nhan','接受邀请。','Jie shou yao qing.','Nhan loi moi.','verb','Dong y nhan.',++$v25);
$v25_3=v($conn,$L25,4,'选择','xuan ze','lua chon','chon','做出正确的选择。','Zuo chu zheng que de xuan ze.','Dua ra lua chon dung.','verb/noun','Chon.',++$v25);
$v25_4=v($conn,$L25,4,'权利','quan li','quyen','quyen','你有权利拒绝。','Ni you quan li ju jue.','Ban co quyen tu choi.','noun','Quyen loi.',++$v25);
$v25_5=v($conn,$L25,4,'勇气','yong qi','dung khi','dung khi','需要有勇气说不。','Xu yao you yong qi shuo bu.','Can dung khi noi ko.','noun','Gan da.',++$v25);
$v25_6=v($conn,$L25,4,'压力','ya li','ap luc','ap luc','不要给自己太大压力。','Bu yao gei zi ji tai da ya li.','Dung gay ap luc cho ban than.','noun','Suc ep.',++$v25);
$v25_7=v($conn,$L25,4,'为难','wei nan','lam kho','lam kho','不要为难别人。','Bu yao wei nan bie ren.','Dung lam kho nguoi khac.','adj/verb','Gay kho.',++$v25);
$v25_8=v($conn,$L25,4,'勉强','mian qiang','gang gay','mieng cuong','不要勉强自己。','Bu yao mian qiang zi ji.','Dung cuong ep minh.','verb/adj','Go gang.',++$v25);
$v25_9=v($conn,$L25,4,'决定','jue ding','quyet dinh','quyet dinh','自己做决定。','Zi ji zuo jue ding.','Tu quyet dinh.','verb/noun','Dinh doat.',++$v25);
$v25_10=v($conn,$L25,4,'考虑','kao lv','can nhac','can','考虑清楚再做。','Kao lv qing chu zai zuo.','Can nhac ro roi lam.','verb','Suy nghi.',++$v25);
$v25_11=v($conn,$L25,4,'道歉','dao qian','xin loi','xin loi','向对方道歉。','Xiang dui fang dao qian.','Xin loi doi phuong.','verb','Nhan loi.',++$v25);
$g25_1=g($conn,$L25,'Cau truc 哪怕...也...','哪怕 + DK + 也 + V','Thu the / Tham chi...cung...','哪怕 (na pa) gia su nhuong bo nhan manh, mang tinh cuong dieu.','哪怕再难，也不放弃 = Thu the kho may cung ko bo.','Nhuong bo nhan manh.',1);
ge($conn,$g25_1,'哪怕对方不高兴，我们也要学会礼貌地拒绝。','Na pa dui fang bu gao xing, wo men ye yao xue hui li mao di ju jue.','Thu the doi phuong ko vui, ta cung phai hoc tu choi lich su.',1);
ge($conn,$g25_1,'哪怕压力再大，也值得坚持自己的选择。','Na pa ya li zai da, ye zhi de jian chi zi ji de xuan ze.','Thu the ap luc lon, cung dang kien tri lua chon.',2);
$g25_2=g($conn,$L25,'Cau truc 于 (van phong)','V/TT + 于 + N','O / Trong / Doi voi','于 la gioi tu van phong, chi thoi gian (于), noi chon (在), hoac doi tuong (对).','勇于说不 = Dung cam noi ko.','Gioi tu van phong.',2);
ge($conn,$g25_2,'善于拒绝也是一种能力。','Shan yu ju jue ye shi yi zhong neng li.','Kheo tu choi cung la mot nang luc.',1);
ge($conn,$g25_2,'每个人都有权利决定自己的生活。','Mei ge ren dou you quan li jue ding zi ji de sheng huo.','Moi nguoi co quyen quyet dinh cuoc song minh.',2);
$g25_3=g($conn,$L25,'Cau truc 难道不是...吗？','难道 + Khong dinh + ma?','Le nao ko phai...sao?','Hoi tu tu nhan manh y khang dinh.','难道拒绝别人就是不对的吗？ = Le nao tu choi la sai sao?','Nhan manh khang dinh.',3);
ge($conn,$g25_3,'难道拒绝别人的要求就是不对的吗？','Nan dao ju jue bie ren de yao qiu jiu shi bu dui de ma?','Le nao tu choi nguoi khac la sai sao?',1);
ge($conn,$g25_3,'难道我们没有权利说"不"吗？','Nan dao wo men mei you quan li shuo "bu" ma?','Le nao chung ta ko co quyen noi "ko" sao?',2);
$g25_4=g($conn,$L25,'Cau truc 当作','把 + A + 当作 + B','Coi / Xem nhu','当作 (dang zuo) la "coi nhu la". Co the dung 作为.','把他当作朋友 = Coi anh ay nhu ban.','Coi nhu.',4);
ge($conn,$g25_4,'把拒绝当作一种成长的机会。','Ba ju jue dang zuo yi zhong cheng zhang de ji hui.','Coi tu choi nhu co hoi truong thanh.',1);
ge($conn,$g25_4,'把别人的批评当作改进的动力。','Ba bie ren de pi ping dang zuo gai jin de dong li.','Coi phe binh nhu dong luc cai thien.',2);
$d25_1=d($conn,$L25,'Hoc cach tu choi','Tai sao phai tu choi.',1);
ds($conn,$d25_1,'Lan','我最近很累，总是答应别人的要求。','Wo zui jin hen lei, zong shi da ying bie ren de yao qiu.','Toi met, hay dong y yeu cau nguoi khac.',1);
ds($conn,$d25_1,'Minh','你要学会说"不"啊。','Ni yao xue hui shuo "bu" a.','Ban phai hoc noi "ko".',2);
ds($conn,$d25_1,'Lan','可我担心拒绝会让人不高兴。','Ke wo dan xin ju jue hui rang ren bu gao xing.','Nhung toi lo tu choi se gay mat long.',3);
ds($conn,$d25_1,'Minh','每个人都有拒绝的权利。哪怕对方不高兴，也要坚持自己的选择。','Mei ge ren dou you ju jue de quan li. Na pa dui fang bu gao xing, ye yao jian chi zi ji de xuan ze.','Ai cung co quyen tu choi. Thu the ho ko vui, cung kien tri chon cua minh.',4);
ds($conn,$d25_1,'Lan','你说得对。我得学会保护自己的时间。','Ni shuo de dui. Wo dei xue hui bao hu zi ji de shi jian.','Ban dung. Toi phai hoc bao ve thoi gian.',5);
$d25_2=d($conn,$L25,'Dung cuong ep','Tu choi lich su.',2);
ds($conn,$d25_2,'Minh','同事让我帮他做项目，但我自己也很忙。','Tong shi rang wo bang ta zuo xiang mu, dan wo zi ji ye hen mang.','Dong nghiep nho lam du an, nhung toi cung ban.',1);
ds($conn,$d25_2,'Lan','那就礼貌地拒绝吧，不要勉强自己。','Na jiu li mao di ju jue ba, bu yao mian qiang zi ji.','Hay lich su tu choi, dung cuong ep minh.',2);
ds($conn,$d25_2,'Minh','可是我不知道怎么说。','Ke shi wo bu zhi dao zen me shuo.','Nhung toi ko biet noi sao.',3);
ds($conn,$d25_2,'Lan','你可以说：理解你的需要，但我现在实在没有时间。','Ni ke yi shuo: li jie ni de xu yao, dan wo xian zai shi zai mei you shi jian.','Ban co the noi: Hieu nhu cau ban, nhung hien tai toi ko co thoi gian.',4);
ds($conn,$d25_2,'Minh','好方法！我试试看。','Hao fang fa! Wo shi shi kan.','Cach hay! Toi thu xem.',5);
$d25_3=d($conn,$L25,'Quyet dinh cua minh','Tu quyet dinh.',3);
ds($conn,$d25_3,'Lan','父母想让我学医，但我喜欢艺术。','Fu mu xiang rang wo xue yi, dan wo xi huan yi shu.','Bo me muon toi hoc y, nhung toi thich nghe thuat.',1);
ds($conn,$d25_3,'Minh','这是你的人生，应该由你自己选择。','Zhe shi ni de ren sheng, ying gai you ni zi ji xuan ze.','Do la doi ban, ban tu chon.',2);
ds($conn,$d25_3,'Lan','所以我需要有勇气说出自己的想法。','Suo yi wo xu yao you yong qi shuo chu zi ji de xiang fa.','Toi can dung khi noi suy nghi minh.',3);
ds($conn,$d25_3,'Minh','把父母的不同意见当作沟通的机会，而不是压力。','Ba fu mu de bu tong yi jian dang zuo gou tong de ji hui, er bu shi ya li.','Coi y kien khac cua bo me nhu co hoi giao tiep, ko phai ap luc.',4);
ds($conn,$d25_3,'Lan','我明白了，我会好好和他们沟通。','Wo ming bai le, wo hui hao hao he ta men gou tong.','Toi hieu, toi se noi chuyen voi ho.',5);
ds($conn,$d25_3,'Minh','我相信他们会理解你的。','Wo xiang xin ta men hui li jie ni de.','Toi tin ho se hieu ban.',6);
r($conn,$L25,'Hoc cach noi ko','学会说"不"是每个人都需要掌握的能力。很多人不敢拒绝别人，是因为怕让对方失望或者担心影响关系。但事实上，勉强自己去做不愿意做的事情，反而会让你感到更加疲惫和不满。每个人都有权利决定自己的时间和生活。哪怕对方是你最好的朋友或亲人，你也有权利说"不"。当然，拒绝的时候要注意方式，礼貌而真诚地表达自己的难处。把拒绝别人当作一种成长，而不是一件坏事。当你学会合理地拒绝之后，你会发现生活变得更加轻松，人际关系反而会变得更健康。难道学会说"不"不是一种智慧吗？','Xue hui shuo "bu" shi mei ge ren dou xu yao zhang wo de neng li. Hen duo ren bu gan ju jue bie ren, shi yin wei pa rang dui fang shi wang huo zhe dan xin ying xiang guan xi. Dan shi shi shi shang, mian qiang zi ji qu zuo bu yuan yi zuo de shi qing, fan er hui rang ni gan dao geng jia pi bei he bu man. Mei ge ren dou you quan li jue ding zi ji de shi jian he sheng huo. Na pa dui fang shi ni zui hao de peng you huo qin ren, ni ye you quan li shuo "bu". Dang ran, ju jue de shi hou yao zhu yi fang shi, li mao er zhen cheng di biao da zi ji de nan chu. Ba ju jue bie ren dang zuo yi zhong cheng zhang, er bu shi yi jian huai shi. Dang ni xue hui he li di ju jue zhi hou, ni hui fa xian sheng huo bian de geng jia qing song, ren ji guan xi fan er hui bian de geng jian kang. Nan dao xue hui shuo "bu" bu shi yi zhong zhi hui ma?','Hoc noi "ko" la nang luc can thiet. Nhieu nguoi ko dam tu choi vi so mat long. Nhung cuong lam viec ko muon chi met hon. Ai cung co quyen quyet dinh thoi gian va doi minh. Thu do la ban than hay nguoi than, ban co quyen noi "ko". Tu choi can lich su va chan thanh. Coi tu choi nhu su truong thanh. Khi tu choi dung cach, cuoc song nhe nhang, quan he lanh manh hon. Le nao hoc noi "ko" ko phai tri tue sao?','medium',195,1);
$L25l=l($conn,$L25,'Tu choi','A: Ban co biet tu choi nguoi khac ko? B: Truoc day ko, nhung gio da hoc duoc. A: Lam the nao? B: Toi noi "Cam on, nhung toi ko the". A: Co kho ko? B: Ban dau kho, nhung dan quen. A: Nguoi khac co ghet ban ko? B: Ko dau. Ho hieu va ton trong.','A: Ni hui ju jue bie ren ma? B: Yi qian bu hui, dan xian zai xue hui le. A: Zen me zuo? B: Wo hui shuo "Xie xie, dan wo bu neng". A: Nan ma? B: Kai shi hen nan, dan xi guan le jiu hao. A: Ta men hui sheng ni de qi ma? B: Bu hui. Ta men hui li jie he zun zhong.','A: Ban co biet tu choi nguoi khac ko? B: Truoc day ko, nhung gio da hoc duoc. A: Lam the nao? B: Toi noi "Cam on, nhung toi ko the". A: Co kho ko? B: Ban dau kho, nhung dan quen. A: Nguoi khac co ghet ban ko? B: Ko dau. Ho hieu va ton trong.','1');
lq($conn,$L25l,'Truoc day B co biet tu choi ko?','{"A":"Co","B":"Ko","C":"Thinh thoang"}','Ko','Truoc day ko biet tu choi.','multiple_choice',1);
lq($conn,$L25l,'B tu choi bang cach nao?','{"A":"Noi Ko","B":"Noi Cam on nhung ko the","C":"Im lang"}','Noi Cam on nhung ko the','Noi "Cam on nhung toi ko the".','multiple_choice',2);
lq($conn,$L25l,'Nguoi khac phan ung the nao?','{"A":"Ghet","B":"Hieu va ton trong","C":"Buon"}','Hieu va ton trong','Ho hieu va ton trong.','multiple_choice',3);
$E25_1=e($conn,$L25,'Chon dap an','"拒绝" la?','multiple_choice','medium',1,'B',1);
eo($conn,$E25_1,'Chap nhan','A',0,1); eo($conn,$E25_1,'Tu choi','B',1,2); eo($conn,$E25_1,'Yeu cau','C',0,3);
$E25_2=e($conn,$L25,'Dich','"Hoc cach noi ko la mot tri tue."','translation','medium',1,'学会说不是一种智慧。',2);
$E25_3=e($conn,$L25,'Dien tu','___ pa kho, toi cung kien tri.','fill_blank','medium',1,'哪',3);
$E25_4=e($conn,$L25,'Sap xep','学会 / 不 / 说 / 要 / 勇气','sentence_order','medium',1,'学会说要勇气。',4);
$E25_5=e($conn,$L25,'Dung sai','"权利" la "nghia vu".','true_false','easy',1,'false',5);
eo($conn,$E25_5,'Dung','A',0,1); eo($conn,$E25_5,'Sai','B',1,2);
$E25_6=e($conn,$L25,'Dien tu','每个人都有拒绝的权___。','fill_blank','medium',1,'利',6);
$E25_7=e($conn,$L25,'Chon dap an','"哪怕" co nghia?','multiple_choice','medium',1,'C',7);
eo($conn,$E25_7,'Neu','A',0,1); eo($conn,$E25_7,'Vi','B',0,2); eo($conn,$E25_7,'Thu the/Tham chi','C',1,3);
$E25_8=e($conn,$L25,'Dien tu','把拒绝当___成长的机会。','fill_blank','medium',1,'作',8);
$E25_9=e($conn,$L25,'Chon tu','Tu choi can ___ khi.','multiple_choice','medium',1,'A',9);
eo($conn,$E25_9,'Dung khi','A',1,1); eo($conn,$E25_9,'Lo so','B',0,2); eo($conn,$E25_9,'Do du','C',0,3);
$E25_10=e($conn,$L25,'Dien tu','Dung ___ ep lam viec minh ko muon.','fill_blank','medium',1,'勉强',10);
foreach ([$v25_1,$v25_2,$v25_3,$v25_4,$v25_5,$v25_6,$v25_7,$v25_8,$v25_9,$v25_10,$v25_11] as $i=>$vid) if ($vid) rv($conn,$L25,$vid,'core',$i+1);
echo " HSK4 L25 done: $v25 vocab, 4 grammar, 3 dialogues, 1 reading, 1 listening, 10 exercises\n";
$conn->exec("SET FOREIGN_KEY_CHECKS=1");
echo "\n HSK4 Lessons 21-25 seeding complete!\n";
