<!doctype html>
<html lang="vi">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Mua khóa học HSK | HànNgữ</title><link rel="stylesheet" href="style.css">
<style>
.course-page{max-width:1200px;margin:auto;padding:108px 24px 70px}.sale-hero{text-align:center;max-width:760px;margin:0 auto 42px}.sale-hero__tag{display:inline-block;background:#ccfbf1;color:#0f766e;font-size:.82rem;font-weight:800;letter-spacing:.06em;padding:8px 14px;border-radius:99px}.sale-hero h1{font-size:clamp(2rem,5vw,3.2rem);margin:14px 0 12px;color:#102a56}.sale-hero p{color:#64748b;font-size:1.05rem;line-height:1.7}.course-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:22px}.course-card{position:relative;background:#fff;border:1px solid #e2e8f0;border-radius:22px;padding:26px;box-shadow:0 10px 28px rgba(15,23,42,.08);display:flex;flex-direction:column;overflow:hidden}.course-card::before{content:'';position:absolute;inset:0 0 auto;height:5px;background:var(--accent)}.course-card--featured{border:2px solid #f59e0b;transform:translateY(-7px);box-shadow:0 18px 38px rgba(245,158,11,.22)}.course-card__top{display:flex;justify-content:space-between;align-items:center;gap:10px}.level{font-size:1.45rem;font-weight:900;color:var(--accent)}.level-note{font-size:.8rem;background:var(--soft);color:var(--accent);font-weight:800;border-radius:99px;padding:6px 10px}.ribbon{position:absolute;right:16px;top:16px;background:#f59e0b;color:#fff;border-radius:99px;padding:6px 10px;font-size:.76rem;font-weight:800}.course-card h2{font-size:1.2rem;color:#0f172a;margin:16px 0 8px}.desc{color:#64748b;line-height:1.55;min-height:72px}.price{margin:20px 0 3px;font-size:1.8rem;color:#102a56;font-weight:900}.price small{font-size:.85rem;color:#94a3b8;font-weight:600}.old-price{color:#94a3b8;text-decoration:line-through;font-size:.9rem}.list{list-style:none;padding:0;margin:20px 0}.list li{border-top:1px solid #f1f5f9;padding:10px 0;color:#475569;font-size:.92rem}.list li::before{content:'✓';display:inline-grid;place-items:center;width:19px;height:19px;margin-right:8px;border-radius:50%;background:var(--soft);color:var(--accent);font-weight:900}.course-card .btn{margin-top:auto;text-align:center}.secure{margin:35px auto 0;max-width:850px;display:flex;justify-content:center;gap:28px;flex-wrap:wrap;color:#475569;font-size:.92rem}.secure strong{color:#0f766e}@media(max-width:900px){.course-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.course-card--featured{transform:none}}@media(max-width:580px){.course-page{padding:90px 16px 40px}.course-grid{grid-template-columns:1fr}.course-card{padding:22px}}
</style>
</head>
<body>
<?php include 'sidebar.php'; ?>
<main class="course-page">
  <header class="sale-hero"><span class="sale-hero__tag">LỘ TRÌNH HSK TRỌN GÓI</span><h1>Chọn khóa học tiếng Trung phù hợp</h1><p>Học theo lộ trình HSK 1 đến HSK 6. Giá đã bao gồm tài liệu số, bài luyện tập, theo dõi tiến độ và hóa đơn điện tử sau thanh toán.</p></header>
  <section class="course-grid">
    <article class="course-card" style="--accent:#0d9488;--soft:#ccfbf1"><div class="course-card__top"><span class="level">HSK 1</span><span class="level-note">Mới bắt đầu</span></div><h2>Nền tảng tiếng Trung</h2><p class="desc">Làm quen Pinyin, phát âm chuẩn, chữ Hán và giao tiếp căn bản.</p><div class="price">1.490.000đ</div><div class="old-price">Giá tham khảo 2.000.000đ</div><ul class="list"><li>30 bài học nền tảng</li><li>150 từ vựng và 40 mẫu câu</li><li>Kiểm tra cuối khóa</li></ul><a class="btn btn--primary" href="course.php?slug=hsk-1-nen-tang">Mua khóa HSK 1</a></article>
    <article class="course-card" style="--accent:#0284c7;--soft:#e0f2fe"><div class="course-card__top"><span class="level">HSK 2</span><span class="level-note">Cơ bản</span></div><h2>Giao tiếp cơ bản</h2><p class="desc">Mở rộng phản xạ giao tiếp trong các tình huống hằng ngày.</p><div class="price">1.790.000đ</div><div class="old-price">Giá tham khảo 2.400.000đ</div><ul class="list"><li>38 bài học theo chủ đề</li><li>300 từ vựng trọng tâm</li><li>Luyện nghe – nói thực tế</li></ul><a class="btn btn--primary" href="course.php?slug=hsk-2-giao-tiep">Mua khóa HSK 2</a></article>
    <article class="course-card course-card--featured" style="--accent:#d97706;--soft:#fef3c7"><span class="ribbon">Được chọn nhiều</span><div class="course-card__top"><span class="level">HSK 3</span><span class="level-note">Sơ cấp</span></div><h2>Sơ cấp nâng cao</h2><p class="desc">Hoàn thiện ngữ pháp và bốn kỹ năng để tự tin thi HSK 3.</p><div class="price">2.190.000đ</div><div class="old-price">Giá tham khảo 3.000.000đ</div><ul class="list"><li>45 bài học chuyên sâu</li><li>600 từ vựng cốt lõi</li><li>Đề thi thử và chấm điểm</li></ul><a class="btn btn--primary" href="course.php?slug=hsk-3-so-cap">Mua khóa HSK 3</a></article>
    <article class="course-card" style="--accent:#7c3aed;--soft:#ede9fe"><div class="course-card__top"><span class="level">HSK 4</span><span class="level-note">Trung cấp</span></div><h2>Trung cấp toàn diện</h2><p class="desc">Nâng khả năng giao tiếp, đọc hiểu và viết đoạn văn tiếng Trung.</p><div class="price">2.790.000đ</div><div class="old-price">Giá tham khảo 4.500.000đ</div><ul class="list"><li>48 bài học và chuyên đề</li><li>1.200 từ vựng thiết yếu</li><li>Luyện đề HSK 4</li></ul><a class="btn btn--primary" href="course.php?slug=hsk-4-trung-cap">Mua khóa HSK 4</a></article>
    <article class="course-card" style="--accent:#db2777;--soft:#fce7f3"><div class="course-card__top"><span class="level">HSK 5</span><span class="level-note">Nâng cao</span></div><h2>Chinh phục HSK 5</h2><p class="desc">Luyện đọc báo, viết bài và sử dụng tiếng Trung trong học tập, công việc.</p><div class="price">3.490.000đ</div><div class="old-price">Giá tham khảo 4.800.000đ</div><ul class="list"><li>50 bài học nâng cao</li><li>2.500 từ vựng học thuật</li><li>Đề luyện thi chuyên sâu</li></ul><a class="btn btn--primary" href="course.php?slug=hsk-5-nang-cao">Mua khóa HSK 5</a></article>
    <article class="course-card" style="--accent:#dc2626;--soft:#fee2e2"><div class="course-card__top"><span class="level">HSK 6</span><span class="level-note">Chuyên sâu</span></div><h2>Luyện thi HSK 6</h2><p class="desc">Phát triển tư duy ngôn ngữ, đọc hiểu chuyên sâu và làm chủ đề thi.</p><div class="price">4.290.000đ</div><div class="old-price">Giá tham khảo 6.000.000đ</div><ul class="list"><li>60 bài học chuyên sâu</li><li>5.000+ từ vựng nâng cao</li><li>Luyện đề và chiến thuật thi</li></ul><a class="btn btn--primary" href="course.php?slug=hsk-6-chuyen-sau">Mua khóa HSK 6</a></article>
  </section>
  <div class="secure"><span><strong>✓ Thanh toán QR MB Bank</strong></span><span>✓ Cấp quyền học sau xác nhận</span><span>✓ Hóa đơn PDF gửi email</span></div>
</main>
</body></html>
